// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CksClusterOidc {
    /**
     * @return The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
     * 
     */
    private @Nullable String adminGroupBinding;
    /**
     * @return The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
     * 
     */
    private @Nullable String ca;
    /**
     * @return The client ID for the OIDC client.
     * 
     */
    private String clientId;
    /**
     * @return The claim to use as the groups.
     * 
     */
    private @Nullable String groupsClaim;
    /**
     * @return The prefix to use for the groups.
     * 
     */
    private @Nullable String groupsPrefix;
    /**
     * @return The URL of the OIDC issuer.
     * 
     */
    private String issuerUrl;
    /**
     * @return The claim to require for authentication.
     * 
     */
    private @Nullable String requiredClaim;
    /**
     * @return A list of signing algorithms that the OpenID Connect discovery endpoint uses.
     * 
     */
    private @Nullable List<String> signingAlgs;
    /**
     * @return The claim to use as the username.
     * 
     */
    private @Nullable String usernameClaim;
    /**
     * @return The prefix to use for the username.
     * 
     */
    private @Nullable String usernamePrefix;

    private CksClusterOidc() {}
    /**
     * @return The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
     * 
     */
    public Optional<String> adminGroupBinding() {
        return Optional.ofNullable(this.adminGroupBinding);
    }
    /**
     * @return The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
     * 
     */
    public Optional<String> ca() {
        return Optional.ofNullable(this.ca);
    }
    /**
     * @return The client ID for the OIDC client.
     * 
     */
    public String clientId() {
        return this.clientId;
    }
    /**
     * @return The claim to use as the groups.
     * 
     */
    public Optional<String> groupsClaim() {
        return Optional.ofNullable(this.groupsClaim);
    }
    /**
     * @return The prefix to use for the groups.
     * 
     */
    public Optional<String> groupsPrefix() {
        return Optional.ofNullable(this.groupsPrefix);
    }
    /**
     * @return The URL of the OIDC issuer.
     * 
     */
    public String issuerUrl() {
        return this.issuerUrl;
    }
    /**
     * @return The claim to require for authentication.
     * 
     */
    public Optional<String> requiredClaim() {
        return Optional.ofNullable(this.requiredClaim);
    }
    /**
     * @return A list of signing algorithms that the OpenID Connect discovery endpoint uses.
     * 
     */
    public List<String> signingAlgs() {
        return this.signingAlgs == null ? List.of() : this.signingAlgs;
    }
    /**
     * @return The claim to use as the username.
     * 
     */
    public Optional<String> usernameClaim() {
        return Optional.ofNullable(this.usernameClaim);
    }
    /**
     * @return The prefix to use for the username.
     * 
     */
    public Optional<String> usernamePrefix() {
        return Optional.ofNullable(this.usernamePrefix);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CksClusterOidc defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String adminGroupBinding;
        private @Nullable String ca;
        private String clientId;
        private @Nullable String groupsClaim;
        private @Nullable String groupsPrefix;
        private String issuerUrl;
        private @Nullable String requiredClaim;
        private @Nullable List<String> signingAlgs;
        private @Nullable String usernameClaim;
        private @Nullable String usernamePrefix;
        public Builder() {}
        public Builder(CksClusterOidc defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.adminGroupBinding = defaults.adminGroupBinding;
    	      this.ca = defaults.ca;
    	      this.clientId = defaults.clientId;
    	      this.groupsClaim = defaults.groupsClaim;
    	      this.groupsPrefix = defaults.groupsPrefix;
    	      this.issuerUrl = defaults.issuerUrl;
    	      this.requiredClaim = defaults.requiredClaim;
    	      this.signingAlgs = defaults.signingAlgs;
    	      this.usernameClaim = defaults.usernameClaim;
    	      this.usernamePrefix = defaults.usernamePrefix;
        }

        @CustomType.Setter
        public Builder adminGroupBinding(@Nullable String adminGroupBinding) {

            this.adminGroupBinding = adminGroupBinding;
            return this;
        }
        @CustomType.Setter
        public Builder ca(@Nullable String ca) {

            this.ca = ca;
            return this;
        }
        @CustomType.Setter
        public Builder clientId(String clientId) {
            if (clientId == null) {
              throw new MissingRequiredPropertyException("CksClusterOidc", "clientId");
            }
            this.clientId = clientId;
            return this;
        }
        @CustomType.Setter
        public Builder groupsClaim(@Nullable String groupsClaim) {

            this.groupsClaim = groupsClaim;
            return this;
        }
        @CustomType.Setter
        public Builder groupsPrefix(@Nullable String groupsPrefix) {

            this.groupsPrefix = groupsPrefix;
            return this;
        }
        @CustomType.Setter
        public Builder issuerUrl(String issuerUrl) {
            if (issuerUrl == null) {
              throw new MissingRequiredPropertyException("CksClusterOidc", "issuerUrl");
            }
            this.issuerUrl = issuerUrl;
            return this;
        }
        @CustomType.Setter
        public Builder requiredClaim(@Nullable String requiredClaim) {

            this.requiredClaim = requiredClaim;
            return this;
        }
        @CustomType.Setter
        public Builder signingAlgs(@Nullable List<String> signingAlgs) {

            this.signingAlgs = signingAlgs;
            return this;
        }
        public Builder signingAlgs(String... signingAlgs) {
            return signingAlgs(List.of(signingAlgs));
        }
        @CustomType.Setter
        public Builder usernameClaim(@Nullable String usernameClaim) {

            this.usernameClaim = usernameClaim;
            return this;
        }
        @CustomType.Setter
        public Builder usernamePrefix(@Nullable String usernamePrefix) {

            this.usernamePrefix = usernamePrefix;
            return this;
        }
        public CksClusterOidc build() {
            final var _resultValue = new CksClusterOidc();
            _resultValue.adminGroupBinding = adminGroupBinding;
            _resultValue.ca = ca;
            _resultValue.clientId = clientId;
            _resultValue.groupsClaim = groupsClaim;
            _resultValue.groupsPrefix = groupsPrefix;
            _resultValue.issuerUrl = issuerUrl;
            _resultValue.requiredClaim = requiredClaim;
            _resultValue.signingAlgs = signingAlgs;
            _resultValue.usernameClaim = usernameClaim;
            _resultValue.usernamePrefix = usernamePrefix;
            return _resultValue;
        }
    }
}
