// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCksClusterAuthzWebhook {
    /**
     * @return The CA certificate of the authorization webhook.
     * 
     */
    private String ca;
    /**
     * @return The server URL of the authorization webhook.
     * 
     */
    private String server;

    private GetCksClusterAuthzWebhook() {}
    /**
     * @return The CA certificate of the authorization webhook.
     * 
     */
    public String ca() {
        return this.ca;
    }
    /**
     * @return The server URL of the authorization webhook.
     * 
     */
    public String server() {
        return this.server;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCksClusterAuthzWebhook defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ca;
        private String server;
        public Builder() {}
        public Builder(GetCksClusterAuthzWebhook defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ca = defaults.ca;
    	      this.server = defaults.server;
        }

        @CustomType.Setter
        public Builder ca(String ca) {
            if (ca == null) {
              throw new MissingRequiredPropertyException("GetCksClusterAuthzWebhook", "ca");
            }
            this.ca = ca;
            return this;
        }
        @CustomType.Setter
        public Builder server(String server) {
            if (server == null) {
              throw new MissingRequiredPropertyException("GetCksClusterAuthzWebhook", "server");
            }
            this.server = server;
            return this;
        }
        public GetCksClusterAuthzWebhook build() {
            final var _resultValue = new GetCksClusterAuthzWebhook();
            _resultValue.ca = ca;
            _resultValue.server = server;
            return _resultValue;
        }
    }
}
