// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.GetCksClusterAuthnWebhook;
import com.pulumi.coreweave.outputs.GetCksClusterAuthzWebhook;
import com.pulumi.coreweave.outputs.GetCksClusterNodePortRange;
import com.pulumi.coreweave.outputs.GetCksClusterOidc;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetCksClusterResult {
    private List<String> additionalServerSans;
    private String apiServerEndpoint;
    private String auditPolicy;
    private GetCksClusterAuthnWebhook authnWebhook;
    private GetCksClusterAuthzWebhook authzWebhook;
    private String id;
    private List<String> internalLbCidrNames;
    private List<String> internalLbCidrNamesV6s;
    private String name;
    private GetCksClusterNodePortRange nodePortRange;
    private GetCksClusterOidc oidc;
    private String podCidrName;
    private String podCidrNameV6;
    private Boolean public_;
    private String serviceAccountOidcIssuerUrl;
    private String serviceCidrName;
    private String serviceCidrNameV6;
    private String sharedStorageClusterId;
    private String status;
    private String version;
    private String vpcId;
    private String zone;

    private GetCksClusterResult() {}
    public List<String> additionalServerSans() {
        return this.additionalServerSans;
    }
    public String apiServerEndpoint() {
        return this.apiServerEndpoint;
    }
    public String auditPolicy() {
        return this.auditPolicy;
    }
    public GetCksClusterAuthnWebhook authnWebhook() {
        return this.authnWebhook;
    }
    public GetCksClusterAuthzWebhook authzWebhook() {
        return this.authzWebhook;
    }
    public String id() {
        return this.id;
    }
    public List<String> internalLbCidrNames() {
        return this.internalLbCidrNames;
    }
    public List<String> internalLbCidrNamesV6s() {
        return this.internalLbCidrNamesV6s;
    }
    public String name() {
        return this.name;
    }
    public GetCksClusterNodePortRange nodePortRange() {
        return this.nodePortRange;
    }
    public GetCksClusterOidc oidc() {
        return this.oidc;
    }
    public String podCidrName() {
        return this.podCidrName;
    }
    public String podCidrNameV6() {
        return this.podCidrNameV6;
    }
    public Boolean public_() {
        return this.public_;
    }
    public String serviceAccountOidcIssuerUrl() {
        return this.serviceAccountOidcIssuerUrl;
    }
    public String serviceCidrName() {
        return this.serviceCidrName;
    }
    public String serviceCidrNameV6() {
        return this.serviceCidrNameV6;
    }
    public String sharedStorageClusterId() {
        return this.sharedStorageClusterId;
    }
    public String status() {
        return this.status;
    }
    public String version() {
        return this.version;
    }
    public String vpcId() {
        return this.vpcId;
    }
    public String zone() {
        return this.zone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCksClusterResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> additionalServerSans;
        private String apiServerEndpoint;
        private String auditPolicy;
        private GetCksClusterAuthnWebhook authnWebhook;
        private GetCksClusterAuthzWebhook authzWebhook;
        private String id;
        private List<String> internalLbCidrNames;
        private List<String> internalLbCidrNamesV6s;
        private String name;
        private GetCksClusterNodePortRange nodePortRange;
        private GetCksClusterOidc oidc;
        private String podCidrName;
        private String podCidrNameV6;
        private Boolean public_;
        private String serviceAccountOidcIssuerUrl;
        private String serviceCidrName;
        private String serviceCidrNameV6;
        private String sharedStorageClusterId;
        private String status;
        private String version;
        private String vpcId;
        private String zone;
        public Builder() {}
        public Builder(GetCksClusterResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additionalServerSans = defaults.additionalServerSans;
    	      this.apiServerEndpoint = defaults.apiServerEndpoint;
    	      this.auditPolicy = defaults.auditPolicy;
    	      this.authnWebhook = defaults.authnWebhook;
    	      this.authzWebhook = defaults.authzWebhook;
    	      this.id = defaults.id;
    	      this.internalLbCidrNames = defaults.internalLbCidrNames;
    	      this.internalLbCidrNamesV6s = defaults.internalLbCidrNamesV6s;
    	      this.name = defaults.name;
    	      this.nodePortRange = defaults.nodePortRange;
    	      this.oidc = defaults.oidc;
    	      this.podCidrName = defaults.podCidrName;
    	      this.podCidrNameV6 = defaults.podCidrNameV6;
    	      this.public_ = defaults.public_;
    	      this.serviceAccountOidcIssuerUrl = defaults.serviceAccountOidcIssuerUrl;
    	      this.serviceCidrName = defaults.serviceCidrName;
    	      this.serviceCidrNameV6 = defaults.serviceCidrNameV6;
    	      this.sharedStorageClusterId = defaults.sharedStorageClusterId;
    	      this.status = defaults.status;
    	      this.version = defaults.version;
    	      this.vpcId = defaults.vpcId;
    	      this.zone = defaults.zone;
        }

        @CustomType.Setter
        public Builder additionalServerSans(List<String> additionalServerSans) {
            if (additionalServerSans == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "additionalServerSans");
            }
            this.additionalServerSans = additionalServerSans;
            return this;
        }
        public Builder additionalServerSans(String... additionalServerSans) {
            return additionalServerSans(List.of(additionalServerSans));
        }
        @CustomType.Setter
        public Builder apiServerEndpoint(String apiServerEndpoint) {
            if (apiServerEndpoint == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "apiServerEndpoint");
            }
            this.apiServerEndpoint = apiServerEndpoint;
            return this;
        }
        @CustomType.Setter
        public Builder auditPolicy(String auditPolicy) {
            if (auditPolicy == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "auditPolicy");
            }
            this.auditPolicy = auditPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder authnWebhook(GetCksClusterAuthnWebhook authnWebhook) {
            if (authnWebhook == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "authnWebhook");
            }
            this.authnWebhook = authnWebhook;
            return this;
        }
        @CustomType.Setter
        public Builder authzWebhook(GetCksClusterAuthzWebhook authzWebhook) {
            if (authzWebhook == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "authzWebhook");
            }
            this.authzWebhook = authzWebhook;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder internalLbCidrNames(List<String> internalLbCidrNames) {
            if (internalLbCidrNames == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "internalLbCidrNames");
            }
            this.internalLbCidrNames = internalLbCidrNames;
            return this;
        }
        public Builder internalLbCidrNames(String... internalLbCidrNames) {
            return internalLbCidrNames(List.of(internalLbCidrNames));
        }
        @CustomType.Setter
        public Builder internalLbCidrNamesV6s(List<String> internalLbCidrNamesV6s) {
            if (internalLbCidrNamesV6s == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "internalLbCidrNamesV6s");
            }
            this.internalLbCidrNamesV6s = internalLbCidrNamesV6s;
            return this;
        }
        public Builder internalLbCidrNamesV6s(String... internalLbCidrNamesV6s) {
            return internalLbCidrNamesV6s(List.of(internalLbCidrNamesV6s));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder nodePortRange(GetCksClusterNodePortRange nodePortRange) {
            if (nodePortRange == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "nodePortRange");
            }
            this.nodePortRange = nodePortRange;
            return this;
        }
        @CustomType.Setter
        public Builder oidc(GetCksClusterOidc oidc) {
            if (oidc == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "oidc");
            }
            this.oidc = oidc;
            return this;
        }
        @CustomType.Setter
        public Builder podCidrName(String podCidrName) {
            if (podCidrName == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "podCidrName");
            }
            this.podCidrName = podCidrName;
            return this;
        }
        @CustomType.Setter
        public Builder podCidrNameV6(String podCidrNameV6) {
            if (podCidrNameV6 == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "podCidrNameV6");
            }
            this.podCidrNameV6 = podCidrNameV6;
            return this;
        }
        @CustomType.Setter("public")
        public Builder public_(Boolean public_) {
            if (public_ == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "public_");
            }
            this.public_ = public_;
            return this;
        }
        @CustomType.Setter
        public Builder serviceAccountOidcIssuerUrl(String serviceAccountOidcIssuerUrl) {
            if (serviceAccountOidcIssuerUrl == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "serviceAccountOidcIssuerUrl");
            }
            this.serviceAccountOidcIssuerUrl = serviceAccountOidcIssuerUrl;
            return this;
        }
        @CustomType.Setter
        public Builder serviceCidrName(String serviceCidrName) {
            if (serviceCidrName == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "serviceCidrName");
            }
            this.serviceCidrName = serviceCidrName;
            return this;
        }
        @CustomType.Setter
        public Builder serviceCidrNameV6(String serviceCidrNameV6) {
            if (serviceCidrNameV6 == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "serviceCidrNameV6");
            }
            this.serviceCidrNameV6 = serviceCidrNameV6;
            return this;
        }
        @CustomType.Setter
        public Builder sharedStorageClusterId(String sharedStorageClusterId) {
            if (sharedStorageClusterId == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "sharedStorageClusterId");
            }
            this.sharedStorageClusterId = sharedStorageClusterId;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder version(String version) {
            if (version == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "version");
            }
            this.version = version;
            return this;
        }
        @CustomType.Setter
        public Builder vpcId(String vpcId) {
            if (vpcId == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "vpcId");
            }
            this.vpcId = vpcId;
            return this;
        }
        @CustomType.Setter
        public Builder zone(String zone) {
            if (zone == null) {
              throw new MissingRequiredPropertyException("GetCksClusterResult", "zone");
            }
            this.zone = zone;
            return this;
        }
        public GetCksClusterResult build() {
            final var _resultValue = new GetCksClusterResult();
            _resultValue.additionalServerSans = additionalServerSans;
            _resultValue.apiServerEndpoint = apiServerEndpoint;
            _resultValue.auditPolicy = auditPolicy;
            _resultValue.authnWebhook = authnWebhook;
            _resultValue.authzWebhook = authzWebhook;
            _resultValue.id = id;
            _resultValue.internalLbCidrNames = internalLbCidrNames;
            _resultValue.internalLbCidrNamesV6s = internalLbCidrNamesV6s;
            _resultValue.name = name;
            _resultValue.nodePortRange = nodePortRange;
            _resultValue.oidc = oidc;
            _resultValue.podCidrName = podCidrName;
            _resultValue.podCidrNameV6 = podCidrNameV6;
            _resultValue.public_ = public_;
            _resultValue.serviceAccountOidcIssuerUrl = serviceAccountOidcIssuerUrl;
            _resultValue.serviceCidrName = serviceCidrName;
            _resultValue.serviceCidrNameV6 = serviceCidrNameV6;
            _resultValue.sharedStorageClusterId = sharedStorageClusterId;
            _resultValue.status = status;
            _resultValue.version = version;
            _resultValue.vpcId = vpcId;
            _resultValue.zone = zone;
            return _resultValue;
        }
    }
}
