// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNetworkingVpcHostPrefixIpam {
    /**
     * @return Describes which IP address from the prefix is allocated to the network gateway.
     * 
     */
    private String gatewayAddressPolicy;
    /**
     * @return The desired length for each Node&#39;s allocation from the VPC-wide aggregate prefix.
     * 
     */
    private Integer prefixLength;

    private GetNetworkingVpcHostPrefixIpam() {}
    /**
     * @return Describes which IP address from the prefix is allocated to the network gateway.
     * 
     */
    public String gatewayAddressPolicy() {
        return this.gatewayAddressPolicy;
    }
    /**
     * @return The desired length for each Node&#39;s allocation from the VPC-wide aggregate prefix.
     * 
     */
    public Integer prefixLength() {
        return this.prefixLength;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkingVpcHostPrefixIpam defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String gatewayAddressPolicy;
        private Integer prefixLength;
        public Builder() {}
        public Builder(GetNetworkingVpcHostPrefixIpam defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.gatewayAddressPolicy = defaults.gatewayAddressPolicy;
    	      this.prefixLength = defaults.prefixLength;
        }

        @CustomType.Setter
        public Builder gatewayAddressPolicy(String gatewayAddressPolicy) {
            if (gatewayAddressPolicy == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefixIpam", "gatewayAddressPolicy");
            }
            this.gatewayAddressPolicy = gatewayAddressPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder prefixLength(Integer prefixLength) {
            if (prefixLength == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefixIpam", "prefixLength");
            }
            this.prefixLength = prefixLength;
            return this;
        }
        public GetNetworkingVpcHostPrefixIpam build() {
            final var _resultValue = new GetNetworkingVpcHostPrefixIpam();
            _resultValue.gatewayAddressPolicy = gatewayAddressPolicy;
            _resultValue.prefixLength = prefixLength;
            return _resultValue;
        }
    }
}
