// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.GetNetworkingVpcHostPrefixIpam;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNetworkingVpcHostPrefix {
    /**
     * @return The configuration for a secondary host prefix.
     * 
     */
    private GetNetworkingVpcHostPrefixIpam ipam;
    /**
     * @return The user-specified name of the host prefix.
     * 
     */
    private String name;
    /**
     * @return The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
     * 
     */
    private List<String> prefixes;
    /**
     * @return Controls network connectivity from the prefix to the host.
     * 
     */
    private String type;

    private GetNetworkingVpcHostPrefix() {}
    /**
     * @return The configuration for a secondary host prefix.
     * 
     */
    public GetNetworkingVpcHostPrefixIpam ipam() {
        return this.ipam;
    }
    /**
     * @return The user-specified name of the host prefix.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
     * 
     */
    public List<String> prefixes() {
        return this.prefixes;
    }
    /**
     * @return Controls network connectivity from the prefix to the host.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkingVpcHostPrefix defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetNetworkingVpcHostPrefixIpam ipam;
        private String name;
        private List<String> prefixes;
        private String type;
        public Builder() {}
        public Builder(GetNetworkingVpcHostPrefix defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipam = defaults.ipam;
    	      this.name = defaults.name;
    	      this.prefixes = defaults.prefixes;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder ipam(GetNetworkingVpcHostPrefixIpam ipam) {
            if (ipam == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefix", "ipam");
            }
            this.ipam = ipam;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefix", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder prefixes(List<String> prefixes) {
            if (prefixes == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefix", "prefixes");
            }
            this.prefixes = prefixes;
            return this;
        }
        public Builder prefixes(String... prefixes) {
            return prefixes(List.of(prefixes));
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcHostPrefix", "type");
            }
            this.type = type;
            return this;
        }
        public GetNetworkingVpcHostPrefix build() {
            final var _resultValue = new GetNetworkingVpcHostPrefix();
            _resultValue.ipam = ipam;
            _resultValue.name = name;
            _resultValue.prefixes = prefixes;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
