// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.GetNetworkingVpcDhcp;
import com.pulumi.coreweave.outputs.GetNetworkingVpcEgress;
import com.pulumi.coreweave.outputs.GetNetworkingVpcHostPrefix;
import com.pulumi.coreweave.outputs.GetNetworkingVpcIngress;
import com.pulumi.coreweave.outputs.GetNetworkingVpcVpcPrefix;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetNetworkingVpcResult {
    private GetNetworkingVpcDhcp dhcp;
    private GetNetworkingVpcEgress egress;
    /**
     * @deprecated
     * Configure hostPrefixes instead.
     * 
     */
    @Deprecated /* Configure hostPrefixes instead. */
    private String hostPrefix;
    private List<GetNetworkingVpcHostPrefix> hostPrefixes;
    private String id;
    private GetNetworkingVpcIngress ingress;
    private String name;
    private List<GetNetworkingVpcVpcPrefix> vpcPrefixes;
    private String zone;

    private GetNetworkingVpcResult() {}
    public GetNetworkingVpcDhcp dhcp() {
        return this.dhcp;
    }
    public GetNetworkingVpcEgress egress() {
        return this.egress;
    }
    /**
     * @deprecated
     * Configure hostPrefixes instead.
     * 
     */
    @Deprecated /* Configure hostPrefixes instead. */
    public String hostPrefix() {
        return this.hostPrefix;
    }
    public List<GetNetworkingVpcHostPrefix> hostPrefixes() {
        return this.hostPrefixes;
    }
    public String id() {
        return this.id;
    }
    public GetNetworkingVpcIngress ingress() {
        return this.ingress;
    }
    public String name() {
        return this.name;
    }
    public List<GetNetworkingVpcVpcPrefix> vpcPrefixes() {
        return this.vpcPrefixes;
    }
    public String zone() {
        return this.zone;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNetworkingVpcResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetNetworkingVpcDhcp dhcp;
        private GetNetworkingVpcEgress egress;
        private String hostPrefix;
        private List<GetNetworkingVpcHostPrefix> hostPrefixes;
        private String id;
        private GetNetworkingVpcIngress ingress;
        private String name;
        private List<GetNetworkingVpcVpcPrefix> vpcPrefixes;
        private String zone;
        public Builder() {}
        public Builder(GetNetworkingVpcResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dhcp = defaults.dhcp;
    	      this.egress = defaults.egress;
    	      this.hostPrefix = defaults.hostPrefix;
    	      this.hostPrefixes = defaults.hostPrefixes;
    	      this.id = defaults.id;
    	      this.ingress = defaults.ingress;
    	      this.name = defaults.name;
    	      this.vpcPrefixes = defaults.vpcPrefixes;
    	      this.zone = defaults.zone;
        }

        @CustomType.Setter
        public Builder dhcp(GetNetworkingVpcDhcp dhcp) {
            if (dhcp == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "dhcp");
            }
            this.dhcp = dhcp;
            return this;
        }
        @CustomType.Setter
        public Builder egress(GetNetworkingVpcEgress egress) {
            if (egress == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "egress");
            }
            this.egress = egress;
            return this;
        }
        @CustomType.Setter
        public Builder hostPrefix(String hostPrefix) {
            if (hostPrefix == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "hostPrefix");
            }
            this.hostPrefix = hostPrefix;
            return this;
        }
        @CustomType.Setter
        public Builder hostPrefixes(List<GetNetworkingVpcHostPrefix> hostPrefixes) {
            if (hostPrefixes == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "hostPrefixes");
            }
            this.hostPrefixes = hostPrefixes;
            return this;
        }
        public Builder hostPrefixes(GetNetworkingVpcHostPrefix... hostPrefixes) {
            return hostPrefixes(List.of(hostPrefixes));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ingress(GetNetworkingVpcIngress ingress) {
            if (ingress == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "ingress");
            }
            this.ingress = ingress;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder vpcPrefixes(List<GetNetworkingVpcVpcPrefix> vpcPrefixes) {
            if (vpcPrefixes == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "vpcPrefixes");
            }
            this.vpcPrefixes = vpcPrefixes;
            return this;
        }
        public Builder vpcPrefixes(GetNetworkingVpcVpcPrefix... vpcPrefixes) {
            return vpcPrefixes(List.of(vpcPrefixes));
        }
        @CustomType.Setter
        public Builder zone(String zone) {
            if (zone == null) {
              throw new MissingRequiredPropertyException("GetNetworkingVpcResult", "zone");
            }
            this.zone = zone;
            return this;
        }
        public GetNetworkingVpcResult build() {
            final var _resultValue = new GetNetworkingVpcResult();
            _resultValue.dhcp = dhcp;
            _resultValue.egress = egress;
            _resultValue.hostPrefix = hostPrefix;
            _resultValue.hostPrefixes = hostPrefixes;
            _resultValue.id = id;
            _resultValue.ingress = ingress;
            _resultValue.name = name;
            _resultValue.vpcPrefixes = vpcPrefixes;
            _resultValue.zone = zone;
            return _resultValue;
        }
    }
}
