// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.GetObjectStorageBucketPolicyDocumentStatement;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetObjectStorageBucketPolicyDocumentResult {
    private @Nullable String id;
    private String json;
    private @Nullable List<GetObjectStorageBucketPolicyDocumentStatement> statements;
    private @Nullable String version;

    private GetObjectStorageBucketPolicyDocumentResult() {}
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public String json() {
        return this.json;
    }
    public List<GetObjectStorageBucketPolicyDocumentStatement> statements() {
        return this.statements == null ? List.of() : this.statements;
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetObjectStorageBucketPolicyDocumentResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private String json;
        private @Nullable List<GetObjectStorageBucketPolicyDocumentStatement> statements;
        private @Nullable String version;
        public Builder() {}
        public Builder(GetObjectStorageBucketPolicyDocumentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.json = defaults.json;
    	      this.statements = defaults.statements;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder json(String json) {
            if (json == null) {
              throw new MissingRequiredPropertyException("GetObjectStorageBucketPolicyDocumentResult", "json");
            }
            this.json = json;
            return this;
        }
        @CustomType.Setter
        public Builder statements(@Nullable List<GetObjectStorageBucketPolicyDocumentStatement> statements) {

            this.statements = statements;
            return this;
        }
        public Builder statements(GetObjectStorageBucketPolicyDocumentStatement... statements) {
            return statements(List.of(statements));
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public GetObjectStorageBucketPolicyDocumentResult build() {
            final var _resultValue = new GetObjectStorageBucketPolicyDocumentResult();
            _resultValue.id = id;
            _resultValue.json = json;
            _resultValue.statements = statements;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
