// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkingVpcHostPrefixIpam {
    /**
     * @return Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
     * 
     */
    private @Nullable String gatewayAddressPolicy;
    /**
     * @return The desired length for each Node&#39;s allocation from the VPC-wide aggregate prefix.
     * 
     */
    private Integer prefixLength;

    private NetworkingVpcHostPrefixIpam() {}
    /**
     * @return Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
     * 
     */
    public Optional<String> gatewayAddressPolicy() {
        return Optional.ofNullable(this.gatewayAddressPolicy);
    }
    /**
     * @return The desired length for each Node&#39;s allocation from the VPC-wide aggregate prefix.
     * 
     */
    public Integer prefixLength() {
        return this.prefixLength;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkingVpcHostPrefixIpam defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String gatewayAddressPolicy;
        private Integer prefixLength;
        public Builder() {}
        public Builder(NetworkingVpcHostPrefixIpam defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.gatewayAddressPolicy = defaults.gatewayAddressPolicy;
    	      this.prefixLength = defaults.prefixLength;
        }

        @CustomType.Setter
        public Builder gatewayAddressPolicy(@Nullable String gatewayAddressPolicy) {

            this.gatewayAddressPolicy = gatewayAddressPolicy;
            return this;
        }
        @CustomType.Setter
        public Builder prefixLength(Integer prefixLength) {
            if (prefixLength == null) {
              throw new MissingRequiredPropertyException("NetworkingVpcHostPrefixIpam", "prefixLength");
            }
            this.prefixLength = prefixLength;
            return this;
        }
        public NetworkingVpcHostPrefixIpam build() {
            final var _resultValue = new NetworkingVpcHostPrefixIpam();
            _resultValue.gatewayAddressPolicy = gatewayAddressPolicy;
            _resultValue.prefixLength = prefixLength;
            return _resultValue;
        }
    }
}
