// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkingVpcIngress {
    /**
     * @return Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
     * 
     */
    private @Nullable Boolean disablePublicServices;

    private NetworkingVpcIngress() {}
    /**
     * @return Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
     * 
     */
    public Optional<Boolean> disablePublicServices() {
        return Optional.ofNullable(this.disablePublicServices);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkingVpcIngress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disablePublicServices;
        public Builder() {}
        public Builder(NetworkingVpcIngress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disablePublicServices = defaults.disablePublicServices;
        }

        @CustomType.Setter
        public Builder disablePublicServices(@Nullable Boolean disablePublicServices) {

            this.disablePublicServices = disablePublicServices;
            return this;
        }
        public NetworkingVpcIngress build() {
            final var _resultValue = new NetworkingVpcIngress();
            _resultValue.disablePublicServices = disablePublicServices;
            return _resultValue;
        }
    }
}
