// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkingVpcEgress {
    /**
     * @return Specifies whether the VPC should be blocked from consuming public Internet.
     * 
     */
    private @Nullable Boolean disablePublicAccess;

    private NetworkingVpcEgress() {}
    /**
     * @return Specifies whether the VPC should be blocked from consuming public Internet.
     * 
     */
    public Optional<Boolean> disablePublicAccess() {
        return Optional.ofNullable(this.disablePublicAccess);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkingVpcEgress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean disablePublicAccess;
        public Builder() {}
        public Builder(NetworkingVpcEgress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.disablePublicAccess = defaults.disablePublicAccess;
        }

        @CustomType.Setter
        public Builder disablePublicAccess(@Nullable Boolean disablePublicAccess) {

            this.disablePublicAccess = disablePublicAccess;
            return this;
        }
        public NetworkingVpcEgress build() {
            final var _resultValue = new NetworkingVpcEgress();
            _resultValue.disablePublicAccess = disablePublicAccess;
            return _resultValue;
        }
    }
}
