// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.NetworkingVpcDhcpDns;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class NetworkingVpcDhcp {
    /**
     * @return Settings affecting DNS for DHCP within the VPC
     * 
     */
    private @Nullable NetworkingVpcDhcpDns dns;

    private NetworkingVpcDhcp() {}
    /**
     * @return Settings affecting DNS for DHCP within the VPC
     * 
     */
    public Optional<NetworkingVpcDhcpDns> dns() {
        return Optional.ofNullable(this.dns);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkingVpcDhcp defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable NetworkingVpcDhcpDns dns;
        public Builder() {}
        public Builder(NetworkingVpcDhcp defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dns = defaults.dns;
        }

        @CustomType.Setter
        public Builder dns(@Nullable NetworkingVpcDhcpDns dns) {

            this.dns = dns;
            return this;
        }
        public NetworkingVpcDhcp build() {
            final var _resultValue = new NetworkingVpcDhcp();
            _resultValue.dns = dns;
            return _resultValue;
        }
    }
}
