// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class ObjectStorageOrganizationAccessPolicyStatement {
    /**
     * @return Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
     * 
     */
    private List<String> actions;
    /**
     * @return Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
     * 
     */
    private String effect;
    /**
     * @return A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
     * 
     */
    private String name;
    /**
     * @return Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining principals.
     * 
     */
    private List<String> principals;
    /**
     * @return Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining resources.
     * 
     */
    private List<String> resources;

    private ObjectStorageOrganizationAccessPolicyStatement() {}
    /**
     * @return Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
     * 
     */
    public List<String> actions() {
        return this.actions;
    }
    /**
     * @return Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
     * 
     */
    public String effect() {
        return this.effect;
    }
    /**
     * @return A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining principals.
     * 
     */
    public List<String> principals() {
        return this.principals;
    }
    /**
     * @return Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining resources.
     * 
     */
    public List<String> resources() {
        return this.resources;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageOrganizationAccessPolicyStatement defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> actions;
        private String effect;
        private String name;
        private List<String> principals;
        private List<String> resources;
        public Builder() {}
        public Builder(ObjectStorageOrganizationAccessPolicyStatement defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.actions = defaults.actions;
    	      this.effect = defaults.effect;
    	      this.name = defaults.name;
    	      this.principals = defaults.principals;
    	      this.resources = defaults.resources;
        }

        @CustomType.Setter
        public Builder actions(List<String> actions) {
            if (actions == null) {
              throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyStatement", "actions");
            }
            this.actions = actions;
            return this;
        }
        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }
        @CustomType.Setter
        public Builder effect(String effect) {
            if (effect == null) {
              throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyStatement", "effect");
            }
            this.effect = effect;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyStatement", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder principals(List<String> principals) {
            if (principals == null) {
              throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyStatement", "principals");
            }
            this.principals = principals;
            return this;
        }
        public Builder principals(String... principals) {
            return principals(List.of(principals));
        }
        @CustomType.Setter
        public Builder resources(List<String> resources) {
            if (resources == null) {
              throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyStatement", "resources");
            }
            this.resources = resources;
            return this;
        }
        public Builder resources(String... resources) {
            return resources(List.of(resources));
        }
        public ObjectStorageOrganizationAccessPolicyStatement build() {
            final var _resultValue = new ObjectStorageOrganizationAccessPolicyStatement();
            _resultValue.actions = actions;
            _resultValue.effect = effect;
            _resultValue.name = name;
            _resultValue.principals = principals;
            _resultValue.resources = resources;
            return _resultValue;
        }
    }
}
