// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload {
    /**
     * @return Days after initiation to abort multipart uploads
     * 
     */
    private @Nullable Integer daysAfterInitiation;

    private ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload() {}
    /**
     * @return Days after initiation to abort multipart uploads
     * 
     */
    public Optional<Integer> daysAfterInitiation() {
        return Optional.ofNullable(this.daysAfterInitiation);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer daysAfterInitiation;
        public Builder() {}
        public Builder(ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.daysAfterInitiation = defaults.daysAfterInitiation;
        }

        @CustomType.Setter
        public Builder daysAfterInitiation(@Nullable Integer daysAfterInitiation) {

            this.daysAfterInitiation = daysAfterInitiation;
            return this;
        }
        public ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload build() {
            final var _resultValue = new ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload();
            _resultValue.daysAfterInitiation = daysAfterInitiation;
            return _resultValue;
        }
    }
}
