// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ObjectStorageBucketLifecycleConfigurationRuleTransition {
    /**
     * @return ISO8601 date when objects transition
     * 
     */
    private @Nullable String date;
    /**
     * @return Number of days after object creation for transition
     * 
     */
    private @Nullable Integer days;
    /**
     * @return Storage class to transition objects to
     * 
     */
    private String storageClass;

    private ObjectStorageBucketLifecycleConfigurationRuleTransition() {}
    /**
     * @return ISO8601 date when objects transition
     * 
     */
    public Optional<String> date() {
        return Optional.ofNullable(this.date);
    }
    /**
     * @return Number of days after object creation for transition
     * 
     */
    public Optional<Integer> days() {
        return Optional.ofNullable(this.days);
    }
    /**
     * @return Storage class to transition objects to
     * 
     */
    public String storageClass() {
        return this.storageClass;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageBucketLifecycleConfigurationRuleTransition defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String date;
        private @Nullable Integer days;
        private String storageClass;
        public Builder() {}
        public Builder(ObjectStorageBucketLifecycleConfigurationRuleTransition defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.date = defaults.date;
    	      this.days = defaults.days;
    	      this.storageClass = defaults.storageClass;
        }

        @CustomType.Setter
        public Builder date(@Nullable String date) {

            this.date = date;
            return this;
        }
        @CustomType.Setter
        public Builder days(@Nullable Integer days) {

            this.days = days;
            return this;
        }
        @CustomType.Setter
        public Builder storageClass(String storageClass) {
            if (storageClass == null) {
              throw new MissingRequiredPropertyException("ObjectStorageBucketLifecycleConfigurationRuleTransition", "storageClass");
            }
            this.storageClass = storageClass;
            return this;
        }
        public ObjectStorageBucketLifecycleConfigurationRuleTransition build() {
            final var _resultValue = new ObjectStorageBucketLifecycleConfigurationRuleTransition();
            _resultValue.date = date;
            _resultValue.days = days;
            _resultValue.storageClass = storageClass;
            return _resultValue;
        }
    }
}
