// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ObjectStorageBucketLifecycleConfigurationRule {
    private @Nullable ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload abortIncompleteMultipartUpload;
    private @Nullable ObjectStorageBucketLifecycleConfigurationRuleExpiration expiration;
    private @Nullable ObjectStorageBucketLifecycleConfigurationRuleFilter filter;
    /**
     * @return Unique identifier for the rule
     * 
     */
    private @Nullable String id;
    private @Nullable ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration noncurrentVersionExpiration;
    private @Nullable List<ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> noncurrentVersionTransitions;
    /**
     * @return Object key prefix to which the rule applies
     * 
     */
    private @Nullable String prefix;
    /**
     * @return Rule status: Enabled or Disabled
     * 
     */
    private String status;
    private @Nullable List<ObjectStorageBucketLifecycleConfigurationRuleTransition> transitions;

    private ObjectStorageBucketLifecycleConfigurationRule() {}
    public Optional<ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload> abortIncompleteMultipartUpload() {
        return Optional.ofNullable(this.abortIncompleteMultipartUpload);
    }
    public Optional<ObjectStorageBucketLifecycleConfigurationRuleExpiration> expiration() {
        return Optional.ofNullable(this.expiration);
    }
    public Optional<ObjectStorageBucketLifecycleConfigurationRuleFilter> filter() {
        return Optional.ofNullable(this.filter);
    }
    /**
     * @return Unique identifier for the rule
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration> noncurrentVersionExpiration() {
        return Optional.ofNullable(this.noncurrentVersionExpiration);
    }
    public List<ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> noncurrentVersionTransitions() {
        return this.noncurrentVersionTransitions == null ? List.of() : this.noncurrentVersionTransitions;
    }
    /**
     * @return Object key prefix to which the rule applies
     * 
     */
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }
    /**
     * @return Rule status: Enabled or Disabled
     * 
     */
    public String status() {
        return this.status;
    }
    public List<ObjectStorageBucketLifecycleConfigurationRuleTransition> transitions() {
        return this.transitions == null ? List.of() : this.transitions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ObjectStorageBucketLifecycleConfigurationRule defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload abortIncompleteMultipartUpload;
        private @Nullable ObjectStorageBucketLifecycleConfigurationRuleExpiration expiration;
        private @Nullable ObjectStorageBucketLifecycleConfigurationRuleFilter filter;
        private @Nullable String id;
        private @Nullable ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration noncurrentVersionExpiration;
        private @Nullable List<ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> noncurrentVersionTransitions;
        private @Nullable String prefix;
        private String status;
        private @Nullable List<ObjectStorageBucketLifecycleConfigurationRuleTransition> transitions;
        public Builder() {}
        public Builder(ObjectStorageBucketLifecycleConfigurationRule defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.abortIncompleteMultipartUpload = defaults.abortIncompleteMultipartUpload;
    	      this.expiration = defaults.expiration;
    	      this.filter = defaults.filter;
    	      this.id = defaults.id;
    	      this.noncurrentVersionExpiration = defaults.noncurrentVersionExpiration;
    	      this.noncurrentVersionTransitions = defaults.noncurrentVersionTransitions;
    	      this.prefix = defaults.prefix;
    	      this.status = defaults.status;
    	      this.transitions = defaults.transitions;
        }

        @CustomType.Setter
        public Builder abortIncompleteMultipartUpload(@Nullable ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload abortIncompleteMultipartUpload) {

            this.abortIncompleteMultipartUpload = abortIncompleteMultipartUpload;
            return this;
        }
        @CustomType.Setter
        public Builder expiration(@Nullable ObjectStorageBucketLifecycleConfigurationRuleExpiration expiration) {

            this.expiration = expiration;
            return this;
        }
        @CustomType.Setter
        public Builder filter(@Nullable ObjectStorageBucketLifecycleConfigurationRuleFilter filter) {

            this.filter = filter;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder noncurrentVersionExpiration(@Nullable ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration noncurrentVersionExpiration) {

            this.noncurrentVersionExpiration = noncurrentVersionExpiration;
            return this;
        }
        @CustomType.Setter
        public Builder noncurrentVersionTransitions(@Nullable List<ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> noncurrentVersionTransitions) {

            this.noncurrentVersionTransitions = noncurrentVersionTransitions;
            return this;
        }
        public Builder noncurrentVersionTransitions(ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition... noncurrentVersionTransitions) {
            return noncurrentVersionTransitions(List.of(noncurrentVersionTransitions));
        }
        @CustomType.Setter
        public Builder prefix(@Nullable String prefix) {

            this.prefix = prefix;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("ObjectStorageBucketLifecycleConfigurationRule", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder transitions(@Nullable List<ObjectStorageBucketLifecycleConfigurationRuleTransition> transitions) {

            this.transitions = transitions;
            return this;
        }
        public Builder transitions(ObjectStorageBucketLifecycleConfigurationRuleTransition... transitions) {
            return transitions(List.of(transitions));
        }
        public ObjectStorageBucketLifecycleConfigurationRule build() {
            final var _resultValue = new ObjectStorageBucketLifecycleConfigurationRule();
            _resultValue.abortIncompleteMultipartUpload = abortIncompleteMultipartUpload;
            _resultValue.expiration = expiration;
            _resultValue.filter = filter;
            _resultValue.id = id;
            _resultValue.noncurrentVersionExpiration = noncurrentVersionExpiration;
            _resultValue.noncurrentVersionTransitions = noncurrentVersionTransitions;
            _resultValue.prefix = prefix;
            _resultValue.status = status;
            _resultValue.transitions = transitions;
            return _resultValue;
        }
    }
}
