// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave
{
    public static class GetNetworkingVpc
    {
        public static Task<GetNetworkingVpcResult> InvokeAsync(GetNetworkingVpcArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworkingVpcResult>("coreweave:index/getNetworkingVpc:getNetworkingVpc", args ?? new GetNetworkingVpcArgs(), options.WithDefaults());

        public static Output<GetNetworkingVpcResult> Invoke(GetNetworkingVpcInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkingVpcResult>("coreweave:index/getNetworkingVpc:getNetworkingVpc", args ?? new GetNetworkingVpcInvokeArgs(), options.WithDefaults());

        public static Output<GetNetworkingVpcResult> Invoke(GetNetworkingVpcInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworkingVpcResult>("coreweave:index/getNetworkingVpc:getNetworkingVpc", args ?? new GetNetworkingVpcInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetNetworkingVpcArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        public GetNetworkingVpcArgs()
        {
        }
        public static new GetNetworkingVpcArgs Empty => new GetNetworkingVpcArgs();
    }

    public sealed class GetNetworkingVpcInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public GetNetworkingVpcInvokeArgs()
        {
        }
        public static new GetNetworkingVpcInvokeArgs Empty => new GetNetworkingVpcInvokeArgs();
    }


    [OutputType]
    public sealed class GetNetworkingVpcResult
    {
        public readonly Outputs.GetNetworkingVpcDhcpResult Dhcp;
        public readonly Outputs.GetNetworkingVpcEgressResult Egress;
        public readonly string HostPrefix;
        public readonly ImmutableArray<Outputs.GetNetworkingVpcHostPrefixResult> HostPrefixes;
        public readonly string Id;
        public readonly Outputs.GetNetworkingVpcIngressResult Ingress;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetNetworkingVpcVpcPrefixResult> VpcPrefixes;
        public readonly string Zone;

        [OutputConstructor]
        private GetNetworkingVpcResult(
            Outputs.GetNetworkingVpcDhcpResult dhcp,

            Outputs.GetNetworkingVpcEgressResult egress,

            string hostPrefix,

            ImmutableArray<Outputs.GetNetworkingVpcHostPrefixResult> hostPrefixes,

            string id,

            Outputs.GetNetworkingVpcIngressResult ingress,

            string name,

            ImmutableArray<Outputs.GetNetworkingVpcVpcPrefixResult> vpcPrefixes,

            string zone)
        {
            Dhcp = dhcp;
            Egress = egress;
            HostPrefix = hostPrefix;
            HostPrefixes = hostPrefixes;
            Id = id;
            Ingress = ingress;
            Name = name;
            VpcPrefixes = vpcPrefixes;
            Zone = zone;
        }
    }
}
