// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave
{
    [CoreweaveResourceType("coreweave:index/objectStorageBucket:ObjectStorageBucket")]
    public partial class ObjectStorageBucket : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the bucket, must be unique
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Map of tags to assign to the bucket.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>?> Tags { get; private set; } = null!;

        /// <summary>
        /// The Availability Zone in which the bucket is located.
        /// </summary>
        [Output("zone")]
        public Output<string> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageBucket resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageBucket(string name, ObjectStorageBucketArgs args, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucket:ObjectStorageBucket", name, args ?? new ObjectStorageBucketArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageBucket(string name, Input<string> id, ObjectStorageBucketState? state = null, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucket:ObjectStorageBucket", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageBucket resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageBucket Get(string name, Input<string> id, ObjectStorageBucketState? state = null, CustomResourceOptions? options = null)
        {
            return new ObjectStorageBucket(name, id, state, options);
        }
    }

    public sealed class ObjectStorageBucketArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the bucket, must be unique
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Map of tags to assign to the bucket.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The Availability Zone in which the bucket is located.
        /// </summary>
        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public ObjectStorageBucketArgs()
        {
        }
        public static new ObjectStorageBucketArgs Empty => new ObjectStorageBucketArgs();
    }

    public sealed class ObjectStorageBucketState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the bucket, must be unique
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Map of tags to assign to the bucket.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The Availability Zone in which the bucket is located.
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public ObjectStorageBucketState()
        {
        }
        public static new ObjectStorageBucketState Empty => new ObjectStorageBucketState();
    }
}
