// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave
{
    [CoreweaveResourceType("coreweave:index/objectStorageBucketSettings:ObjectStorageBucketSettings")]
    public partial class ObjectStorageBucketSettings : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
        /// </summary>
        [Output("auditLoggingEnabled")]
        public Output<bool> AuditLoggingEnabled { get; private set; } = null!;

        /// <summary>
        /// The name of the bucket to manage settings for.
        /// </summary>
        [Output("bucket")]
        public Output<string> Bucket { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageBucketSettings resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageBucketSettings(string name, ObjectStorageBucketSettingsArgs args, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucketSettings:ObjectStorageBucketSettings", name, args ?? new ObjectStorageBucketSettingsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageBucketSettings(string name, Input<string> id, ObjectStorageBucketSettingsState? state = null, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucketSettings:ObjectStorageBucketSettings", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageBucketSettings resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageBucketSettings Get(string name, Input<string> id, ObjectStorageBucketSettingsState? state = null, CustomResourceOptions? options = null)
        {
            return new ObjectStorageBucketSettings(name, id, state, options);
        }
    }

    public sealed class ObjectStorageBucketSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
        /// </summary>
        [Input("auditLoggingEnabled")]
        public Input<bool>? AuditLoggingEnabled { get; set; }

        /// <summary>
        /// The name of the bucket to manage settings for.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        public ObjectStorageBucketSettingsArgs()
        {
        }
        public static new ObjectStorageBucketSettingsArgs Empty => new ObjectStorageBucketSettingsArgs();
    }

    public sealed class ObjectStorageBucketSettingsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
        /// </summary>
        [Input("auditLoggingEnabled")]
        public Input<bool>? AuditLoggingEnabled { get; set; }

        /// <summary>
        /// The name of the bucket to manage settings for.
        /// </summary>
        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        public ObjectStorageBucketSettingsState()
        {
        }
        public static new ObjectStorageBucketSettingsState Empty => new ObjectStorageBucketSettingsState();
    }
}
