// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave
{
    [CoreweaveResourceType("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration")]
    public partial class ObjectStorageBucketLifecycleConfiguration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the bucket to apply lifecycle configuration to
        /// </summary>
        [Output("bucket")]
        public Output<string> Bucket { get; private set; } = null!;

        /// <summary>
        /// One or more lifecycle rule blocks
        /// </summary>
        [Output("rules")]
        public Output<ImmutableArray<Outputs.ObjectStorageBucketLifecycleConfigurationRule>> Rules { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageBucketLifecycleConfiguration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageBucketLifecycleConfiguration(string name, ObjectStorageBucketLifecycleConfigurationArgs args, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, args ?? new ObjectStorageBucketLifecycleConfigurationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageBucketLifecycleConfiguration(string name, Input<string> id, ObjectStorageBucketLifecycleConfigurationState? state = null, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageBucketLifecycleConfiguration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageBucketLifecycleConfiguration Get(string name, Input<string> id, ObjectStorageBucketLifecycleConfigurationState? state = null, CustomResourceOptions? options = null)
        {
            return new ObjectStorageBucketLifecycleConfiguration(name, id, state, options);
        }
    }

    public sealed class ObjectStorageBucketLifecycleConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the bucket to apply lifecycle configuration to
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        [Input("rules")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleArgs>? _rules;

        /// <summary>
        /// One or more lifecycle rule blocks
        /// </summary>
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleArgs>());
            set => _rules = value;
        }

        public ObjectStorageBucketLifecycleConfigurationArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationArgs Empty => new ObjectStorageBucketLifecycleConfigurationArgs();
    }

    public sealed class ObjectStorageBucketLifecycleConfigurationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the bucket to apply lifecycle configuration to
        /// </summary>
        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        [Input("rules")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleGetArgs>? _rules;

        /// <summary>
        /// One or more lifecycle rule blocks
        /// </summary>
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleGetArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleGetArgs>());
            set => _rules = value;
        }

        public ObjectStorageBucketLifecycleConfigurationState()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationState Empty => new ObjectStorageBucketLifecycleConfigurationState();
    }
}
