// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave
{
    [CoreweaveResourceType("coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy")]
    public partial class ObjectStorageOrganizationAccessPolicy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the organization access policy, must be unique.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The list of access policy statements associated with this policy. At least one statement is required.
        /// </summary>
        [Output("statements")]
        public Output<ImmutableArray<Outputs.ObjectStorageOrganizationAccessPolicyStatement>> Statements { get; private set; } = null!;


        /// <summary>
        /// Create a ObjectStorageOrganizationAccessPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ObjectStorageOrganizationAccessPolicy(string name, ObjectStorageOrganizationAccessPolicyArgs args, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy", name, args ?? new ObjectStorageOrganizationAccessPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ObjectStorageOrganizationAccessPolicy(string name, Input<string> id, ObjectStorageOrganizationAccessPolicyState? state = null, CustomResourceOptions? options = null)
            : base("coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ObjectStorageOrganizationAccessPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ObjectStorageOrganizationAccessPolicy Get(string name, Input<string> id, ObjectStorageOrganizationAccessPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new ObjectStorageOrganizationAccessPolicy(name, id, state, options);
        }
    }

    public sealed class ObjectStorageOrganizationAccessPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the organization access policy, must be unique.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("statements", required: true)]
        private InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementArgs>? _statements;

        /// <summary>
        /// The list of access policy statements associated with this policy. At least one statement is required.
        /// </summary>
        public InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementArgs> Statements
        {
            get => _statements ?? (_statements = new InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementArgs>());
            set => _statements = value;
        }

        public ObjectStorageOrganizationAccessPolicyArgs()
        {
        }
        public static new ObjectStorageOrganizationAccessPolicyArgs Empty => new ObjectStorageOrganizationAccessPolicyArgs();
    }

    public sealed class ObjectStorageOrganizationAccessPolicyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the organization access policy, must be unique.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("statements")]
        private InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementGetArgs>? _statements;

        /// <summary>
        /// The list of access policy statements associated with this policy. At least one statement is required.
        /// </summary>
        public InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementGetArgs> Statements
        {
            get => _statements ?? (_statements = new InputList<Inputs.ObjectStorageOrganizationAccessPolicyStatementGetArgs>());
            set => _statements = value;
        }

        public ObjectStorageOrganizationAccessPolicyState()
        {
        }
        public static new ObjectStorageOrganizationAccessPolicyState Empty => new ObjectStorageOrganizationAccessPolicyState();
    }
}
