# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetCksClusterResult',
    'AwaitableGetCksClusterResult',
    'get_cks_cluster',
    'get_cks_cluster_output',
]

@pulumi.output_type
class GetCksClusterResult:
    """
    A collection of values returned by getCksCluster.
    """
    def __init__(__self__, additional_server_sans=None, api_server_endpoint=None, audit_policy=None, authn_webhook=None, authz_webhook=None, id=None, internal_lb_cidr_names=None, internal_lb_cidr_names_v6s=None, name=None, node_port_range=None, oidc=None, pod_cidr_name=None, pod_cidr_name_v6=None, public=None, service_account_oidc_issuer_url=None, service_cidr_name=None, service_cidr_name_v6=None, shared_storage_cluster_id=None, status=None, version=None, vpc_id=None, zone=None):
        if additional_server_sans and not isinstance(additional_server_sans, list):
            raise TypeError("Expected argument 'additional_server_sans' to be a list")
        pulumi.set(__self__, "additional_server_sans", additional_server_sans)
        if api_server_endpoint and not isinstance(api_server_endpoint, str):
            raise TypeError("Expected argument 'api_server_endpoint' to be a str")
        pulumi.set(__self__, "api_server_endpoint", api_server_endpoint)
        if audit_policy and not isinstance(audit_policy, str):
            raise TypeError("Expected argument 'audit_policy' to be a str")
        pulumi.set(__self__, "audit_policy", audit_policy)
        if authn_webhook and not isinstance(authn_webhook, dict):
            raise TypeError("Expected argument 'authn_webhook' to be a dict")
        pulumi.set(__self__, "authn_webhook", authn_webhook)
        if authz_webhook and not isinstance(authz_webhook, dict):
            raise TypeError("Expected argument 'authz_webhook' to be a dict")
        pulumi.set(__self__, "authz_webhook", authz_webhook)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if internal_lb_cidr_names and not isinstance(internal_lb_cidr_names, list):
            raise TypeError("Expected argument 'internal_lb_cidr_names' to be a list")
        pulumi.set(__self__, "internal_lb_cidr_names", internal_lb_cidr_names)
        if internal_lb_cidr_names_v6s and not isinstance(internal_lb_cidr_names_v6s, list):
            raise TypeError("Expected argument 'internal_lb_cidr_names_v6s' to be a list")
        pulumi.set(__self__, "internal_lb_cidr_names_v6s", internal_lb_cidr_names_v6s)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if node_port_range and not isinstance(node_port_range, dict):
            raise TypeError("Expected argument 'node_port_range' to be a dict")
        pulumi.set(__self__, "node_port_range", node_port_range)
        if oidc and not isinstance(oidc, dict):
            raise TypeError("Expected argument 'oidc' to be a dict")
        pulumi.set(__self__, "oidc", oidc)
        if pod_cidr_name and not isinstance(pod_cidr_name, str):
            raise TypeError("Expected argument 'pod_cidr_name' to be a str")
        pulumi.set(__self__, "pod_cidr_name", pod_cidr_name)
        if pod_cidr_name_v6 and not isinstance(pod_cidr_name_v6, str):
            raise TypeError("Expected argument 'pod_cidr_name_v6' to be a str")
        pulumi.set(__self__, "pod_cidr_name_v6", pod_cidr_name_v6)
        if public and not isinstance(public, bool):
            raise TypeError("Expected argument 'public' to be a bool")
        pulumi.set(__self__, "public", public)
        if service_account_oidc_issuer_url and not isinstance(service_account_oidc_issuer_url, str):
            raise TypeError("Expected argument 'service_account_oidc_issuer_url' to be a str")
        pulumi.set(__self__, "service_account_oidc_issuer_url", service_account_oidc_issuer_url)
        if service_cidr_name and not isinstance(service_cidr_name, str):
            raise TypeError("Expected argument 'service_cidr_name' to be a str")
        pulumi.set(__self__, "service_cidr_name", service_cidr_name)
        if service_cidr_name_v6 and not isinstance(service_cidr_name_v6, str):
            raise TypeError("Expected argument 'service_cidr_name_v6' to be a str")
        pulumi.set(__self__, "service_cidr_name_v6", service_cidr_name_v6)
        if shared_storage_cluster_id and not isinstance(shared_storage_cluster_id, str):
            raise TypeError("Expected argument 'shared_storage_cluster_id' to be a str")
        pulumi.set(__self__, "shared_storage_cluster_id", shared_storage_cluster_id)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)
        if vpc_id and not isinstance(vpc_id, str):
            raise TypeError("Expected argument 'vpc_id' to be a str")
        pulumi.set(__self__, "vpc_id", vpc_id)
        if zone and not isinstance(zone, str):
            raise TypeError("Expected argument 'zone' to be a str")
        pulumi.set(__self__, "zone", zone)

    @_builtins.property
    @pulumi.getter(name="additionalServerSans")
    def additional_server_sans(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "additional_server_sans")

    @_builtins.property
    @pulumi.getter(name="apiServerEndpoint")
    def api_server_endpoint(self) -> _builtins.str:
        return pulumi.get(self, "api_server_endpoint")

    @_builtins.property
    @pulumi.getter(name="auditPolicy")
    def audit_policy(self) -> _builtins.str:
        return pulumi.get(self, "audit_policy")

    @_builtins.property
    @pulumi.getter(name="authnWebhook")
    def authn_webhook(self) -> 'outputs.GetCksClusterAuthnWebhookResult':
        return pulumi.get(self, "authn_webhook")

    @_builtins.property
    @pulumi.getter(name="authzWebhook")
    def authz_webhook(self) -> 'outputs.GetCksClusterAuthzWebhookResult':
        return pulumi.get(self, "authz_webhook")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="internalLbCidrNames")
    def internal_lb_cidr_names(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "internal_lb_cidr_names")

    @_builtins.property
    @pulumi.getter(name="internalLbCidrNamesV6s")
    def internal_lb_cidr_names_v6s(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "internal_lb_cidr_names_v6s")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="nodePortRange")
    def node_port_range(self) -> 'outputs.GetCksClusterNodePortRangeResult':
        return pulumi.get(self, "node_port_range")

    @_builtins.property
    @pulumi.getter
    def oidc(self) -> 'outputs.GetCksClusterOidcResult':
        return pulumi.get(self, "oidc")

    @_builtins.property
    @pulumi.getter(name="podCidrName")
    def pod_cidr_name(self) -> _builtins.str:
        return pulumi.get(self, "pod_cidr_name")

    @_builtins.property
    @pulumi.getter(name="podCidrNameV6")
    def pod_cidr_name_v6(self) -> _builtins.str:
        return pulumi.get(self, "pod_cidr_name_v6")

    @_builtins.property
    @pulumi.getter
    def public(self) -> _builtins.bool:
        return pulumi.get(self, "public")

    @_builtins.property
    @pulumi.getter(name="serviceAccountOidcIssuerUrl")
    def service_account_oidc_issuer_url(self) -> _builtins.str:
        return pulumi.get(self, "service_account_oidc_issuer_url")

    @_builtins.property
    @pulumi.getter(name="serviceCidrName")
    def service_cidr_name(self) -> _builtins.str:
        return pulumi.get(self, "service_cidr_name")

    @_builtins.property
    @pulumi.getter(name="serviceCidrNameV6")
    def service_cidr_name_v6(self) -> _builtins.str:
        return pulumi.get(self, "service_cidr_name_v6")

    @_builtins.property
    @pulumi.getter(name="sharedStorageClusterId")
    def shared_storage_cluster_id(self) -> _builtins.str:
        return pulumi.get(self, "shared_storage_cluster_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> _builtins.str:
        return pulumi.get(self, "vpc_id")

    @_builtins.property
    @pulumi.getter
    def zone(self) -> _builtins.str:
        return pulumi.get(self, "zone")


class AwaitableGetCksClusterResult(GetCksClusterResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetCksClusterResult(
            additional_server_sans=self.additional_server_sans,
            api_server_endpoint=self.api_server_endpoint,
            audit_policy=self.audit_policy,
            authn_webhook=self.authn_webhook,
            authz_webhook=self.authz_webhook,
            id=self.id,
            internal_lb_cidr_names=self.internal_lb_cidr_names,
            internal_lb_cidr_names_v6s=self.internal_lb_cidr_names_v6s,
            name=self.name,
            node_port_range=self.node_port_range,
            oidc=self.oidc,
            pod_cidr_name=self.pod_cidr_name,
            pod_cidr_name_v6=self.pod_cidr_name_v6,
            public=self.public,
            service_account_oidc_issuer_url=self.service_account_oidc_issuer_url,
            service_cidr_name=self.service_cidr_name,
            service_cidr_name_v6=self.service_cidr_name_v6,
            shared_storage_cluster_id=self.shared_storage_cluster_id,
            status=self.status,
            version=self.version,
            vpc_id=self.vpc_id,
            zone=self.zone)


def get_cks_cluster(id: Optional[_builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetCksClusterResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('coreweave:index/getCksCluster:getCksCluster', __args__, opts=opts, typ=GetCksClusterResult).value

    return AwaitableGetCksClusterResult(
        additional_server_sans=pulumi.get(__ret__, 'additional_server_sans'),
        api_server_endpoint=pulumi.get(__ret__, 'api_server_endpoint'),
        audit_policy=pulumi.get(__ret__, 'audit_policy'),
        authn_webhook=pulumi.get(__ret__, 'authn_webhook'),
        authz_webhook=pulumi.get(__ret__, 'authz_webhook'),
        id=pulumi.get(__ret__, 'id'),
        internal_lb_cidr_names=pulumi.get(__ret__, 'internal_lb_cidr_names'),
        internal_lb_cidr_names_v6s=pulumi.get(__ret__, 'internal_lb_cidr_names_v6s'),
        name=pulumi.get(__ret__, 'name'),
        node_port_range=pulumi.get(__ret__, 'node_port_range'),
        oidc=pulumi.get(__ret__, 'oidc'),
        pod_cidr_name=pulumi.get(__ret__, 'pod_cidr_name'),
        pod_cidr_name_v6=pulumi.get(__ret__, 'pod_cidr_name_v6'),
        public=pulumi.get(__ret__, 'public'),
        service_account_oidc_issuer_url=pulumi.get(__ret__, 'service_account_oidc_issuer_url'),
        service_cidr_name=pulumi.get(__ret__, 'service_cidr_name'),
        service_cidr_name_v6=pulumi.get(__ret__, 'service_cidr_name_v6'),
        shared_storage_cluster_id=pulumi.get(__ret__, 'shared_storage_cluster_id'),
        status=pulumi.get(__ret__, 'status'),
        version=pulumi.get(__ret__, 'version'),
        vpc_id=pulumi.get(__ret__, 'vpc_id'),
        zone=pulumi.get(__ret__, 'zone'))
def get_cks_cluster_output(id: Optional[pulumi.Input[_builtins.str]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetCksClusterResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('coreweave:index/getCksCluster:getCksCluster', __args__, opts=opts, typ=GetCksClusterResult)
    return __ret__.apply(lambda __response__: GetCksClusterResult(
        additional_server_sans=pulumi.get(__response__, 'additional_server_sans'),
        api_server_endpoint=pulumi.get(__response__, 'api_server_endpoint'),
        audit_policy=pulumi.get(__response__, 'audit_policy'),
        authn_webhook=pulumi.get(__response__, 'authn_webhook'),
        authz_webhook=pulumi.get(__response__, 'authz_webhook'),
        id=pulumi.get(__response__, 'id'),
        internal_lb_cidr_names=pulumi.get(__response__, 'internal_lb_cidr_names'),
        internal_lb_cidr_names_v6s=pulumi.get(__response__, 'internal_lb_cidr_names_v6s'),
        name=pulumi.get(__response__, 'name'),
        node_port_range=pulumi.get(__response__, 'node_port_range'),
        oidc=pulumi.get(__response__, 'oidc'),
        pod_cidr_name=pulumi.get(__response__, 'pod_cidr_name'),
        pod_cidr_name_v6=pulumi.get(__response__, 'pod_cidr_name_v6'),
        public=pulumi.get(__response__, 'public'),
        service_account_oidc_issuer_url=pulumi.get(__response__, 'service_account_oidc_issuer_url'),
        service_cidr_name=pulumi.get(__response__, 'service_cidr_name'),
        service_cidr_name_v6=pulumi.get(__response__, 'service_cidr_name_v6'),
        shared_storage_cluster_id=pulumi.get(__response__, 'shared_storage_cluster_id'),
        status=pulumi.get(__response__, 'status'),
        version=pulumi.get(__response__, 'version'),
        vpc_id=pulumi.get(__response__, 'vpc_id'),
        zone=pulumi.get(__response__, 'zone')))
