# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'CksClusterAuthnWebhook',
    'CksClusterAuthzWebhook',
    'CksClusterNodePortRange',
    'CksClusterOidc',
    'NetworkingVpcDhcp',
    'NetworkingVpcDhcpDns',
    'NetworkingVpcEgress',
    'NetworkingVpcHostPrefix',
    'NetworkingVpcHostPrefixIpam',
    'NetworkingVpcIngress',
    'NetworkingVpcVpcPrefix',
    'ObjectStorageBucketLifecycleConfigurationRule',
    'ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload',
    'ObjectStorageBucketLifecycleConfigurationRuleExpiration',
    'ObjectStorageBucketLifecycleConfigurationRuleFilter',
    'ObjectStorageBucketLifecycleConfigurationRuleFilterAnd',
    'ObjectStorageBucketLifecycleConfigurationRuleFilterTag',
    'ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration',
    'ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition',
    'ObjectStorageBucketLifecycleConfigurationRuleTransition',
    'ObjectStorageBucketVersioningVersioningConfiguration',
    'ObjectStorageOrganizationAccessPolicyStatement',
    'GetCksClusterAuthnWebhookResult',
    'GetCksClusterAuthzWebhookResult',
    'GetCksClusterNodePortRangeResult',
    'GetCksClusterOidcResult',
    'GetNetworkingVpcDhcpResult',
    'GetNetworkingVpcDhcpDnsResult',
    'GetNetworkingVpcEgressResult',
    'GetNetworkingVpcHostPrefixResult',
    'GetNetworkingVpcHostPrefixIpamResult',
    'GetNetworkingVpcIngressResult',
    'GetNetworkingVpcVpcPrefixResult',
    'GetObjectStorageBucketPolicyDocumentStatementResult',
]

@pulumi.output_type
class CksClusterAuthnWebhook(dict):
    def __init__(__self__, *,
                 server: _builtins.str,
                 ca: Optional[_builtins.str] = None):
        """
        :param _builtins.str server: The URL of the webhook server.
        :param _builtins.str ca: The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
        """
        pulumi.set(__self__, "server", server)
        if ca is not None:
            pulumi.set(__self__, "ca", ca)

    @_builtins.property
    @pulumi.getter
    def server(self) -> _builtins.str:
        """
        The URL of the webhook server.
        """
        return pulumi.get(self, "server")

    @_builtins.property
    @pulumi.getter
    def ca(self) -> Optional[_builtins.str]:
        """
        The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
        """
        return pulumi.get(self, "ca")


@pulumi.output_type
class CksClusterAuthzWebhook(dict):
    def __init__(__self__, *,
                 server: _builtins.str,
                 ca: Optional[_builtins.str] = None):
        """
        :param _builtins.str server: The URL of the webhook server.
        :param _builtins.str ca: The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
        """
        pulumi.set(__self__, "server", server)
        if ca is not None:
            pulumi.set(__self__, "ca", ca)

    @_builtins.property
    @pulumi.getter
    def server(self) -> _builtins.str:
        """
        The URL of the webhook server.
        """
        return pulumi.get(self, "server")

    @_builtins.property
    @pulumi.getter
    def ca(self) -> Optional[_builtins.str]:
        """
        The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
        """
        return pulumi.get(self, "ca")


@pulumi.output_type
class CksClusterNodePortRange(dict):
    def __init__(__self__, *,
                 end: Optional[_builtins.int] = None,
                 start: Optional[_builtins.int] = None):
        if end is not None:
            pulumi.set(__self__, "end", end)
        if start is not None:
            pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "end")

    @_builtins.property
    @pulumi.getter
    def start(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "start")


@pulumi.output_type
class CksClusterOidc(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "clientId":
            suggest = "client_id"
        elif key == "issuerUrl":
            suggest = "issuer_url"
        elif key == "adminGroupBinding":
            suggest = "admin_group_binding"
        elif key == "groupsClaim":
            suggest = "groups_claim"
        elif key == "groupsPrefix":
            suggest = "groups_prefix"
        elif key == "requiredClaim":
            suggest = "required_claim"
        elif key == "signingAlgs":
            suggest = "signing_algs"
        elif key == "usernameClaim":
            suggest = "username_claim"
        elif key == "usernamePrefix":
            suggest = "username_prefix"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CksClusterOidc. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CksClusterOidc.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CksClusterOidc.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 client_id: _builtins.str,
                 issuer_url: _builtins.str,
                 admin_group_binding: Optional[_builtins.str] = None,
                 ca: Optional[_builtins.str] = None,
                 groups_claim: Optional[_builtins.str] = None,
                 groups_prefix: Optional[_builtins.str] = None,
                 required_claim: Optional[_builtins.str] = None,
                 signing_algs: Optional[Sequence[_builtins.str]] = None,
                 username_claim: Optional[_builtins.str] = None,
                 username_prefix: Optional[_builtins.str] = None):
        """
        :param _builtins.str client_id: The client ID for the OIDC client.
        :param _builtins.str issuer_url: The URL of the OIDC issuer.
        :param _builtins.str admin_group_binding: The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
        :param _builtins.str ca: The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
        :param _builtins.str groups_claim: The claim to use as the groups.
        :param _builtins.str groups_prefix: The prefix to use for the groups.
        :param _builtins.str required_claim: The claim to require for authentication.
        :param Sequence[_builtins.str] signing_algs: A list of signing algorithms that the OpenID Connect discovery endpoint uses.
        :param _builtins.str username_claim: The claim to use as the username.
        :param _builtins.str username_prefix: The prefix to use for the username.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "issuer_url", issuer_url)
        if admin_group_binding is not None:
            pulumi.set(__self__, "admin_group_binding", admin_group_binding)
        if ca is not None:
            pulumi.set(__self__, "ca", ca)
        if groups_claim is not None:
            pulumi.set(__self__, "groups_claim", groups_claim)
        if groups_prefix is not None:
            pulumi.set(__self__, "groups_prefix", groups_prefix)
        if required_claim is not None:
            pulumi.set(__self__, "required_claim", required_claim)
        if signing_algs is not None:
            pulumi.set(__self__, "signing_algs", signing_algs)
        if username_claim is not None:
            pulumi.set(__self__, "username_claim", username_claim)
        if username_prefix is not None:
            pulumi.set(__self__, "username_prefix", username_prefix)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> _builtins.str:
        """
        The client ID for the OIDC client.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="issuerUrl")
    def issuer_url(self) -> _builtins.str:
        """
        The URL of the OIDC issuer.
        """
        return pulumi.get(self, "issuer_url")

    @_builtins.property
    @pulumi.getter(name="adminGroupBinding")
    def admin_group_binding(self) -> Optional[_builtins.str]:
        """
        The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
        """
        return pulumi.get(self, "admin_group_binding")

    @_builtins.property
    @pulumi.getter
    def ca(self) -> Optional[_builtins.str]:
        """
        The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
        """
        return pulumi.get(self, "ca")

    @_builtins.property
    @pulumi.getter(name="groupsClaim")
    def groups_claim(self) -> Optional[_builtins.str]:
        """
        The claim to use as the groups.
        """
        return pulumi.get(self, "groups_claim")

    @_builtins.property
    @pulumi.getter(name="groupsPrefix")
    def groups_prefix(self) -> Optional[_builtins.str]:
        """
        The prefix to use for the groups.
        """
        return pulumi.get(self, "groups_prefix")

    @_builtins.property
    @pulumi.getter(name="requiredClaim")
    def required_claim(self) -> Optional[_builtins.str]:
        """
        The claim to require for authentication.
        """
        return pulumi.get(self, "required_claim")

    @_builtins.property
    @pulumi.getter(name="signingAlgs")
    def signing_algs(self) -> Optional[Sequence[_builtins.str]]:
        """
        A list of signing algorithms that the OpenID Connect discovery endpoint uses.
        """
        return pulumi.get(self, "signing_algs")

    @_builtins.property
    @pulumi.getter(name="usernameClaim")
    def username_claim(self) -> Optional[_builtins.str]:
        """
        The claim to use as the username.
        """
        return pulumi.get(self, "username_claim")

    @_builtins.property
    @pulumi.getter(name="usernamePrefix")
    def username_prefix(self) -> Optional[_builtins.str]:
        """
        The prefix to use for the username.
        """
        return pulumi.get(self, "username_prefix")


@pulumi.output_type
class NetworkingVpcDhcp(dict):
    def __init__(__self__, *,
                 dns: Optional['outputs.NetworkingVpcDhcpDns'] = None):
        """
        :param 'NetworkingVpcDhcpDnsArgs' dns: Settings affecting DNS for DHCP within the VPC
        """
        if dns is not None:
            pulumi.set(__self__, "dns", dns)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> Optional['outputs.NetworkingVpcDhcpDns']:
        """
        Settings affecting DNS for DHCP within the VPC
        """
        return pulumi.get(self, "dns")


@pulumi.output_type
class NetworkingVpcDhcpDns(dict):
    def __init__(__self__, *,
                 servers: Optional[Sequence[_builtins.str]] = None):
        """
        :param Sequence[_builtins.str] servers: The DNS servers to be used by DHCP clients within the VPC.
        """
        if servers is not None:
            pulumi.set(__self__, "servers", servers)

    @_builtins.property
    @pulumi.getter
    def servers(self) -> Optional[Sequence[_builtins.str]]:
        """
        The DNS servers to be used by DHCP clients within the VPC.
        """
        return pulumi.get(self, "servers")


@pulumi.output_type
class NetworkingVpcEgress(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "disablePublicAccess":
            suggest = "disable_public_access"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NetworkingVpcEgress. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NetworkingVpcEgress.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NetworkingVpcEgress.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 disable_public_access: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool disable_public_access: Specifies whether the VPC should be blocked from consuming public Internet.
        """
        if disable_public_access is not None:
            pulumi.set(__self__, "disable_public_access", disable_public_access)

    @_builtins.property
    @pulumi.getter(name="disablePublicAccess")
    def disable_public_access(self) -> Optional[_builtins.bool]:
        """
        Specifies whether the VPC should be blocked from consuming public Internet.
        """
        return pulumi.get(self, "disable_public_access")


@pulumi.output_type
class NetworkingVpcHostPrefix(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 prefixes: Sequence[_builtins.str],
                 type: _builtins.str,
                 ipam: Optional['outputs.NetworkingVpcHostPrefixIpam'] = None):
        """
        :param _builtins.str name: The user-specified name of the host prefix.
        :param Sequence[_builtins.str] prefixes: The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        :param _builtins.str type: Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
        :param 'NetworkingVpcHostPrefixIpamArgs' ipam: The configuration for a secondary host prefix.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "prefixes", prefixes)
        pulumi.set(__self__, "type", type)
        if ipam is not None:
            pulumi.set(__self__, "ipam", ipam)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The user-specified name of the host prefix.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def prefixes(self) -> Sequence[_builtins.str]:
        """
        The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        """
        return pulumi.get(self, "prefixes")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def ipam(self) -> Optional['outputs.NetworkingVpcHostPrefixIpam']:
        """
        The configuration for a secondary host prefix.
        """
        return pulumi.get(self, "ipam")


@pulumi.output_type
class NetworkingVpcHostPrefixIpam(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "prefixLength":
            suggest = "prefix_length"
        elif key == "gatewayAddressPolicy":
            suggest = "gateway_address_policy"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NetworkingVpcHostPrefixIpam. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NetworkingVpcHostPrefixIpam.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NetworkingVpcHostPrefixIpam.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 prefix_length: _builtins.int,
                 gateway_address_policy: Optional[_builtins.str] = None):
        """
        :param _builtins.int prefix_length: The desired length for each Node's allocation from the VPC-wide aggregate prefix.
        :param _builtins.str gateway_address_policy: Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
        """
        pulumi.set(__self__, "prefix_length", prefix_length)
        if gateway_address_policy is not None:
            pulumi.set(__self__, "gateway_address_policy", gateway_address_policy)

    @_builtins.property
    @pulumi.getter(name="prefixLength")
    def prefix_length(self) -> _builtins.int:
        """
        The desired length for each Node's allocation from the VPC-wide aggregate prefix.
        """
        return pulumi.get(self, "prefix_length")

    @_builtins.property
    @pulumi.getter(name="gatewayAddressPolicy")
    def gateway_address_policy(self) -> Optional[_builtins.str]:
        """
        Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
        """
        return pulumi.get(self, "gateway_address_policy")


@pulumi.output_type
class NetworkingVpcIngress(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "disablePublicServices":
            suggest = "disable_public_services"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in NetworkingVpcIngress. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        NetworkingVpcIngress.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        NetworkingVpcIngress.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 disable_public_services: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool disable_public_services: Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
        """
        if disable_public_services is not None:
            pulumi.set(__self__, "disable_public_services", disable_public_services)

    @_builtins.property
    @pulumi.getter(name="disablePublicServices")
    def disable_public_services(self) -> Optional[_builtins.bool]:
        """
        Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
        """
        return pulumi.get(self, "disable_public_services")


@pulumi.output_type
class NetworkingVpcVpcPrefix(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 value: _builtins.str):
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        return pulumi.get(self, "value")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRule(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "abortIncompleteMultipartUpload":
            suggest = "abort_incomplete_multipart_upload"
        elif key == "noncurrentVersionExpiration":
            suggest = "noncurrent_version_expiration"
        elif key == "noncurrentVersionTransitions":
            suggest = "noncurrent_version_transitions"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRule. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRule.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRule.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 status: _builtins.str,
                 abort_incomplete_multipart_upload: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload'] = None,
                 expiration: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration'] = None,
                 filter: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter'] = None,
                 id: Optional[_builtins.str] = None,
                 noncurrent_version_expiration: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration'] = None,
                 noncurrent_version_transitions: Optional[Sequence['outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition']] = None,
                 prefix: Optional[_builtins.str] = None,
                 transitions: Optional[Sequence['outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition']] = None):
        """
        :param _builtins.str status: Rule status: Enabled or Disabled
        :param _builtins.str id: Unique identifier for the rule
        :param _builtins.str prefix: Object key prefix to which the rule applies
        """
        pulumi.set(__self__, "status", status)
        if abort_incomplete_multipart_upload is not None:
            pulumi.set(__self__, "abort_incomplete_multipart_upload", abort_incomplete_multipart_upload)
        if expiration is not None:
            pulumi.set(__self__, "expiration", expiration)
        if filter is not None:
            pulumi.set(__self__, "filter", filter)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if noncurrent_version_expiration is not None:
            pulumi.set(__self__, "noncurrent_version_expiration", noncurrent_version_expiration)
        if noncurrent_version_transitions is not None:
            pulumi.set(__self__, "noncurrent_version_transitions", noncurrent_version_transitions)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if transitions is not None:
            pulumi.set(__self__, "transitions", transitions)

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Rule status: Enabled or Disabled
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="abortIncompleteMultipartUpload")
    def abort_incomplete_multipart_upload(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload']:
        return pulumi.get(self, "abort_incomplete_multipart_upload")

    @_builtins.property
    @pulumi.getter
    def expiration(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration']:
        return pulumi.get(self, "expiration")

    @_builtins.property
    @pulumi.getter
    def filter(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter']:
        return pulumi.get(self, "filter")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        """
        Unique identifier for the rule
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="noncurrentVersionExpiration")
    def noncurrent_version_expiration(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration']:
        return pulumi.get(self, "noncurrent_version_expiration")

    @_builtins.property
    @pulumi.getter(name="noncurrentVersionTransitions")
    def noncurrent_version_transitions(self) -> Optional[Sequence['outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition']]:
        return pulumi.get(self, "noncurrent_version_transitions")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[_builtins.str]:
        """
        Object key prefix to which the rule applies
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def transitions(self) -> Optional[Sequence['outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition']]:
        return pulumi.get(self, "transitions")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "daysAfterInitiation":
            suggest = "days_after_initiation"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 days_after_initiation: Optional[_builtins.int] = None):
        """
        :param _builtins.int days_after_initiation: Days after initiation to abort multipart uploads
        """
        if days_after_initiation is not None:
            pulumi.set(__self__, "days_after_initiation", days_after_initiation)

    @_builtins.property
    @pulumi.getter(name="daysAfterInitiation")
    def days_after_initiation(self) -> Optional[_builtins.int]:
        """
        Days after initiation to abort multipart uploads
        """
        return pulumi.get(self, "days_after_initiation")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleExpiration(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "expiredObjectDeleteMarker":
            suggest = "expired_object_delete_marker"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleExpiration. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleExpiration.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleExpiration.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 date: Optional[_builtins.str] = None,
                 days: Optional[_builtins.int] = None,
                 expired_object_delete_marker: Optional[_builtins.bool] = None):
        """
        :param _builtins.str date: ISO8601 date when objects expire
        :param _builtins.int days: Number of days after object creation for expiration
        :param _builtins.bool expired_object_delete_marker: Whether to remove expired delete markers
        """
        if date is not None:
            pulumi.set(__self__, "date", date)
        if days is not None:
            pulumi.set(__self__, "days", days)
        if expired_object_delete_marker is not None:
            pulumi.set(__self__, "expired_object_delete_marker", expired_object_delete_marker)

    @_builtins.property
    @pulumi.getter
    def date(self) -> Optional[_builtins.str]:
        """
        ISO8601 date when objects expire
        """
        return pulumi.get(self, "date")

    @_builtins.property
    @pulumi.getter
    def days(self) -> Optional[_builtins.int]:
        """
        Number of days after object creation for expiration
        """
        return pulumi.get(self, "days")

    @_builtins.property
    @pulumi.getter(name="expiredObjectDeleteMarker")
    def expired_object_delete_marker(self) -> Optional[_builtins.bool]:
        """
        Whether to remove expired delete markers
        """
        return pulumi.get(self, "expired_object_delete_marker")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleFilter(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "and":
            suggest = "and_"
        elif key == "objectSizeGreaterThan":
            suggest = "object_size_greater_than"
        elif key == "objectSizeLessThan":
            suggest = "object_size_less_than"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleFilter. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleFilter.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleFilter.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 and_: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterAnd'] = None,
                 object_size_greater_than: Optional[_builtins.int] = None,
                 object_size_less_than: Optional[_builtins.int] = None,
                 prefix: Optional[_builtins.str] = None,
                 tag: Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterTag'] = None):
        """
        :param 'ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs' and_: Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
        :param _builtins.int object_size_greater_than: Minimum object size (in bytes) to which the rule applies.
        :param _builtins.int object_size_less_than: Maximum object size (in bytes) to which the rule applies.
        :param _builtins.str prefix: Prefix filter
        """
        if and_ is not None:
            pulumi.set(__self__, "and_", and_)
        if object_size_greater_than is not None:
            pulumi.set(__self__, "object_size_greater_than", object_size_greater_than)
        if object_size_less_than is not None:
            pulumi.set(__self__, "object_size_less_than", object_size_less_than)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if tag is not None:
            pulumi.set(__self__, "tag", tag)

    @_builtins.property
    @pulumi.getter(name="and")
    def and_(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterAnd']:
        """
        Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
        """
        return pulumi.get(self, "and_")

    @_builtins.property
    @pulumi.getter(name="objectSizeGreaterThan")
    def object_size_greater_than(self) -> Optional[_builtins.int]:
        """
        Minimum object size (in bytes) to which the rule applies.
        """
        return pulumi.get(self, "object_size_greater_than")

    @_builtins.property
    @pulumi.getter(name="objectSizeLessThan")
    def object_size_less_than(self) -> Optional[_builtins.int]:
        """
        Maximum object size (in bytes) to which the rule applies.
        """
        return pulumi.get(self, "object_size_less_than")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[_builtins.str]:
        """
        Prefix filter
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def tag(self) -> Optional['outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterTag']:
        return pulumi.get(self, "tag")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleFilterAnd(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "objectSizeGreaterThan":
            suggest = "object_size_greater_than"
        elif key == "objectSizeLessThan":
            suggest = "object_size_less_than"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleFilterAnd. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleFilterAnd.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleFilterAnd.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 object_size_greater_than: Optional[_builtins.int] = None,
                 object_size_less_than: Optional[_builtins.int] = None,
                 prefix: Optional[_builtins.str] = None,
                 tags: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param _builtins.int object_size_greater_than: Minimum object size (in bytes) to which the rule applies.
        :param _builtins.int object_size_less_than: Maximum object size (in bytes) to which the rule applies.
        :param _builtins.str prefix: Prefix identifying one or more objects to which the rule applies.
        :param Mapping[str, _builtins.str] tags: Map for specifying tag keys and values.
        """
        if object_size_greater_than is not None:
            pulumi.set(__self__, "object_size_greater_than", object_size_greater_than)
        if object_size_less_than is not None:
            pulumi.set(__self__, "object_size_less_than", object_size_less_than)
        if prefix is not None:
            pulumi.set(__self__, "prefix", prefix)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter(name="objectSizeGreaterThan")
    def object_size_greater_than(self) -> Optional[_builtins.int]:
        """
        Minimum object size (in bytes) to which the rule applies.
        """
        return pulumi.get(self, "object_size_greater_than")

    @_builtins.property
    @pulumi.getter(name="objectSizeLessThan")
    def object_size_less_than(self) -> Optional[_builtins.int]:
        """
        Maximum object size (in bytes) to which the rule applies.
        """
        return pulumi.get(self, "object_size_less_than")

    @_builtins.property
    @pulumi.getter
    def prefix(self) -> Optional[_builtins.str]:
        """
        Prefix identifying one or more objects to which the rule applies.
        """
        return pulumi.get(self, "prefix")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Map for specifying tag keys and values.
        """
        return pulumi.get(self, "tags")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleFilterTag(dict):
    def __init__(__self__, *,
                 key: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str key: Tag key filter
        :param _builtins.str value: Tag value filter
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        """
        Tag key filter
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        Tag value filter
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "newerNoncurrentVersions":
            suggest = "newer_noncurrent_versions"
        elif key == "noncurrentDays":
            suggest = "noncurrent_days"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 newer_noncurrent_versions: Optional[_builtins.int] = None,
                 noncurrent_days: Optional[_builtins.int] = None):
        """
        :param _builtins.int newer_noncurrent_versions: Number of noncurrent versions to retain
        :param _builtins.int noncurrent_days: Days after becoming noncurrent before deletion
        """
        if newer_noncurrent_versions is not None:
            pulumi.set(__self__, "newer_noncurrent_versions", newer_noncurrent_versions)
        if noncurrent_days is not None:
            pulumi.set(__self__, "noncurrent_days", noncurrent_days)

    @_builtins.property
    @pulumi.getter(name="newerNoncurrentVersions")
    def newer_noncurrent_versions(self) -> Optional[_builtins.int]:
        """
        Number of noncurrent versions to retain
        """
        return pulumi.get(self, "newer_noncurrent_versions")

    @_builtins.property
    @pulumi.getter(name="noncurrentDays")
    def noncurrent_days(self) -> Optional[_builtins.int]:
        """
        Days after becoming noncurrent before deletion
        """
        return pulumi.get(self, "noncurrent_days")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "noncurrentDays":
            suggest = "noncurrent_days"
        elif key == "storageClass":
            suggest = "storage_class"
        elif key == "newerNoncurrentVersions":
            suggest = "newer_noncurrent_versions"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 noncurrent_days: _builtins.int,
                 storage_class: _builtins.str,
                 newer_noncurrent_versions: Optional[_builtins.int] = None):
        """
        :param _builtins.int noncurrent_days: Number of days after object becomes noncurrent before the transition may occur
        :param _builtins.str storage_class: Storage class to transition noncurrent objects to
        :param _builtins.int newer_noncurrent_versions: Number of noncurrent versions to retain
        """
        pulumi.set(__self__, "noncurrent_days", noncurrent_days)
        pulumi.set(__self__, "storage_class", storage_class)
        if newer_noncurrent_versions is not None:
            pulumi.set(__self__, "newer_noncurrent_versions", newer_noncurrent_versions)

    @_builtins.property
    @pulumi.getter(name="noncurrentDays")
    def noncurrent_days(self) -> _builtins.int:
        """
        Number of days after object becomes noncurrent before the transition may occur
        """
        return pulumi.get(self, "noncurrent_days")

    @_builtins.property
    @pulumi.getter(name="storageClass")
    def storage_class(self) -> _builtins.str:
        """
        Storage class to transition noncurrent objects to
        """
        return pulumi.get(self, "storage_class")

    @_builtins.property
    @pulumi.getter(name="newerNoncurrentVersions")
    def newer_noncurrent_versions(self) -> Optional[_builtins.int]:
        """
        Number of noncurrent versions to retain
        """
        return pulumi.get(self, "newer_noncurrent_versions")


@pulumi.output_type
class ObjectStorageBucketLifecycleConfigurationRuleTransition(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "storageClass":
            suggest = "storage_class"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ObjectStorageBucketLifecycleConfigurationRuleTransition. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleTransition.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ObjectStorageBucketLifecycleConfigurationRuleTransition.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 storage_class: _builtins.str,
                 date: Optional[_builtins.str] = None,
                 days: Optional[_builtins.int] = None):
        """
        :param _builtins.str storage_class: Storage class to transition objects to
        :param _builtins.str date: ISO8601 date when objects transition
        :param _builtins.int days: Number of days after object creation for transition
        """
        pulumi.set(__self__, "storage_class", storage_class)
        if date is not None:
            pulumi.set(__self__, "date", date)
        if days is not None:
            pulumi.set(__self__, "days", days)

    @_builtins.property
    @pulumi.getter(name="storageClass")
    def storage_class(self) -> _builtins.str:
        """
        Storage class to transition objects to
        """
        return pulumi.get(self, "storage_class")

    @_builtins.property
    @pulumi.getter
    def date(self) -> Optional[_builtins.str]:
        """
        ISO8601 date when objects transition
        """
        return pulumi.get(self, "date")

    @_builtins.property
    @pulumi.getter
    def days(self) -> Optional[_builtins.int]:
        """
        Number of days after object creation for transition
        """
        return pulumi.get(self, "days")


@pulumi.output_type
class ObjectStorageBucketVersioningVersioningConfiguration(dict):
    def __init__(__self__, *,
                 status: _builtins.str):
        """
        :param _builtins.str status: Versioning state of the bucket. Valid values: Enabled, Suspended, or Disabled. Disabled should only be used when creating or importing resources that correspond to unversioned S3 buckets since the S3 API does not allow setting an Enabled/Suspended bucket to Disabled.
        """
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        Versioning state of the bucket. Valid values: Enabled, Suspended, or Disabled. Disabled should only be used when creating or importing resources that correspond to unversioned S3 buckets since the S3 API does not allow setting an Enabled/Suspended bucket to Disabled.
        """
        return pulumi.get(self, "status")


@pulumi.output_type
class ObjectStorageOrganizationAccessPolicyStatement(dict):
    def __init__(__self__, *,
                 actions: Sequence[_builtins.str],
                 effect: _builtins.str,
                 name: _builtins.str,
                 principals: Sequence[_builtins.str],
                 resources: Sequence[_builtins.str]):
        """
        :param Sequence[_builtins.str] actions: Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
        :param _builtins.str effect: Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
        :param _builtins.str name: A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
        :param Sequence[_builtins.str] principals: Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining principals.
        :param Sequence[_builtins.str] resources: Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining resources.
        """
        pulumi.set(__self__, "actions", actions)
        pulumi.set(__self__, "effect", effect)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "principals", principals)
        pulumi.set(__self__, "resources", resources)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> Sequence[_builtins.str]:
        """
        Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
        """
        return pulumi.get(self, "actions")

    @_builtins.property
    @pulumi.getter
    def effect(self) -> _builtins.str:
        """
        Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
        """
        return pulumi.get(self, "effect")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def principals(self) -> Sequence[_builtins.str]:
        """
        Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining principals.
        """
        return pulumi.get(self, "principals")

    @_builtins.property
    @pulumi.getter
    def resources(self) -> Sequence[_builtins.str]:
        """
        Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining resources.
        """
        return pulumi.get(self, "resources")


@pulumi.output_type
class GetCksClusterAuthnWebhookResult(dict):
    def __init__(__self__, *,
                 ca: _builtins.str,
                 server: _builtins.str):
        """
        :param _builtins.str ca: The CA certificate of the authentication webhook.
        :param _builtins.str server: The server URL of the authentication webhook.
        """
        pulumi.set(__self__, "ca", ca)
        pulumi.set(__self__, "server", server)

    @_builtins.property
    @pulumi.getter
    def ca(self) -> _builtins.str:
        """
        The CA certificate of the authentication webhook.
        """
        return pulumi.get(self, "ca")

    @_builtins.property
    @pulumi.getter
    def server(self) -> _builtins.str:
        """
        The server URL of the authentication webhook.
        """
        return pulumi.get(self, "server")


@pulumi.output_type
class GetCksClusterAuthzWebhookResult(dict):
    def __init__(__self__, *,
                 ca: _builtins.str,
                 server: _builtins.str):
        """
        :param _builtins.str ca: The CA certificate of the authorization webhook.
        :param _builtins.str server: The server URL of the authorization webhook.
        """
        pulumi.set(__self__, "ca", ca)
        pulumi.set(__self__, "server", server)

    @_builtins.property
    @pulumi.getter
    def ca(self) -> _builtins.str:
        """
        The CA certificate of the authorization webhook.
        """
        return pulumi.get(self, "ca")

    @_builtins.property
    @pulumi.getter
    def server(self) -> _builtins.str:
        """
        The server URL of the authorization webhook.
        """
        return pulumi.get(self, "server")


@pulumi.output_type
class GetCksClusterNodePortRangeResult(dict):
    def __init__(__self__, *,
                 end: _builtins.int,
                 start: _builtins.int):
        """
        :param _builtins.int end: End of the NodePort range.
        :param _builtins.int start: Start of the NodePort range.
        """
        pulumi.set(__self__, "end", end)
        pulumi.set(__self__, "start", start)

    @_builtins.property
    @pulumi.getter
    def end(self) -> _builtins.int:
        """
        End of the NodePort range.
        """
        return pulumi.get(self, "end")

    @_builtins.property
    @pulumi.getter
    def start(self) -> _builtins.int:
        """
        Start of the NodePort range.
        """
        return pulumi.get(self, "start")


@pulumi.output_type
class GetCksClusterOidcResult(dict):
    def __init__(__self__, *,
                 client_id: _builtins.str,
                 issuer_url: _builtins.str):
        """
        :param _builtins.str client_id: The client ID of the OIDC configuration.
        :param _builtins.str issuer_url: The issuer URL of the OIDC configuration.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "issuer_url", issuer_url)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> _builtins.str:
        """
        The client ID of the OIDC configuration.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="issuerUrl")
    def issuer_url(self) -> _builtins.str:
        """
        The issuer URL of the OIDC configuration.
        """
        return pulumi.get(self, "issuer_url")


@pulumi.output_type
class GetNetworkingVpcDhcpResult(dict):
    def __init__(__self__, *,
                 dns: 'outputs.GetNetworkingVpcDhcpDnsResult'):
        """
        :param 'GetNetworkingVpcDhcpDnsArgs' dns: Settings affecting DNS for DHCP within the VPC
        """
        pulumi.set(__self__, "dns", dns)

    @_builtins.property
    @pulumi.getter
    def dns(self) -> 'outputs.GetNetworkingVpcDhcpDnsResult':
        """
        Settings affecting DNS for DHCP within the VPC
        """
        return pulumi.get(self, "dns")


@pulumi.output_type
class GetNetworkingVpcDhcpDnsResult(dict):
    def __init__(__self__, *,
                 servers: Optional[Sequence[_builtins.str]] = None):
        """
        :param Sequence[_builtins.str] servers: The DNS servers advertised to DHCP clients within the VPC.
        """
        if servers is not None:
            pulumi.set(__self__, "servers", servers)

    @_builtins.property
    @pulumi.getter
    def servers(self) -> Optional[Sequence[_builtins.str]]:
        """
        The DNS servers advertised to DHCP clients within the VPC.
        """
        return pulumi.get(self, "servers")


@pulumi.output_type
class GetNetworkingVpcEgressResult(dict):
    def __init__(__self__, *,
                 disable_public_access: _builtins.bool):
        """
        :param _builtins.bool disable_public_access: True if the VPC is blocked from consuming public Internet. False otherwise.
        """
        pulumi.set(__self__, "disable_public_access", disable_public_access)

    @_builtins.property
    @pulumi.getter(name="disablePublicAccess")
    def disable_public_access(self) -> _builtins.bool:
        """
        True if the VPC is blocked from consuming public Internet. False otherwise.
        """
        return pulumi.get(self, "disable_public_access")


@pulumi.output_type
class GetNetworkingVpcHostPrefixResult(dict):
    def __init__(__self__, *,
                 ipam: 'outputs.GetNetworkingVpcHostPrefixIpamResult',
                 name: _builtins.str,
                 prefixes: Sequence[_builtins.str],
                 type: _builtins.str):
        """
        :param 'GetNetworkingVpcHostPrefixIpamArgs' ipam: The configuration for a secondary host prefix.
        :param _builtins.str name: The user-specified name of the host prefix.
        :param Sequence[_builtins.str] prefixes: The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        :param _builtins.str type: Controls network connectivity from the prefix to the host.
        """
        pulumi.set(__self__, "ipam", ipam)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "prefixes", prefixes)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def ipam(self) -> 'outputs.GetNetworkingVpcHostPrefixIpamResult':
        """
        The configuration for a secondary host prefix.
        """
        return pulumi.get(self, "ipam")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The user-specified name of the host prefix.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def prefixes(self) -> Sequence[_builtins.str]:
        """
        The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        """
        return pulumi.get(self, "prefixes")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Controls network connectivity from the prefix to the host.
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class GetNetworkingVpcHostPrefixIpamResult(dict):
    def __init__(__self__, *,
                 gateway_address_policy: _builtins.str,
                 prefix_length: _builtins.int):
        """
        :param _builtins.str gateway_address_policy: Describes which IP address from the prefix is allocated to the network gateway.
        :param _builtins.int prefix_length: The desired length for each Node's allocation from the VPC-wide aggregate prefix.
        """
        pulumi.set(__self__, "gateway_address_policy", gateway_address_policy)
        pulumi.set(__self__, "prefix_length", prefix_length)

    @_builtins.property
    @pulumi.getter(name="gatewayAddressPolicy")
    def gateway_address_policy(self) -> _builtins.str:
        """
        Describes which IP address from the prefix is allocated to the network gateway.
        """
        return pulumi.get(self, "gateway_address_policy")

    @_builtins.property
    @pulumi.getter(name="prefixLength")
    def prefix_length(self) -> _builtins.int:
        """
        The desired length for each Node's allocation from the VPC-wide aggregate prefix.
        """
        return pulumi.get(self, "prefix_length")


@pulumi.output_type
class GetNetworkingVpcIngressResult(dict):
    def __init__(__self__, *,
                 disable_public_services: _builtins.bool):
        """
        :param _builtins.bool disable_public_services: True if the VPC will prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet. False otherwise.
        """
        pulumi.set(__self__, "disable_public_services", disable_public_services)

    @_builtins.property
    @pulumi.getter(name="disablePublicServices")
    def disable_public_services(self) -> _builtins.bool:
        """
        True if the VPC will prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet. False otherwise.
        """
        return pulumi.get(self, "disable_public_services")


@pulumi.output_type
class GetNetworkingVpcVpcPrefixResult(dict):
    def __init__(__self__, *,
                 name: _builtins.str,
                 value: _builtins.str):
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def value(self) -> _builtins.str:
        return pulumi.get(self, "value")


@pulumi.output_type
class GetObjectStorageBucketPolicyDocumentStatementResult(dict):
    def __init__(__self__, *,
                 actions: Optional[Sequence[_builtins.str]] = None,
                 condition: Optional[Mapping[str, Mapping[str, _builtins.str]]] = None,
                 effect: Optional[_builtins.str] = None,
                 principal: Optional[Mapping[str, Sequence[_builtins.str]]] = None,
                 resources: Optional[Sequence[_builtins.str]] = None,
                 sid: Optional[_builtins.str] = None):
        """
        :param Sequence[_builtins.str] actions: List of action strings, e.g. `["s3:PutObject"]`
        :param Mapping[str, Mapping[str, _builtins.str]] condition: Map of condition operators to JSON expressions
        :param _builtins.str effect: `Allow` or `Deny`
        :param Mapping[str, Sequence[_builtins.str]] principal: Map of principal types to ARNs
        :param Sequence[_builtins.str] resources: List of resource ARNs, e.g. `["arn:aws:s3:::bucket/*"]`
        :param _builtins.str sid: An optional statement identifier
        """
        if actions is not None:
            pulumi.set(__self__, "actions", actions)
        if condition is not None:
            pulumi.set(__self__, "condition", condition)
        if effect is not None:
            pulumi.set(__self__, "effect", effect)
        if principal is not None:
            pulumi.set(__self__, "principal", principal)
        if resources is not None:
            pulumi.set(__self__, "resources", resources)
        if sid is not None:
            pulumi.set(__self__, "sid", sid)

    @_builtins.property
    @pulumi.getter
    def actions(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of action strings, e.g. `["s3:PutObject"]`
        """
        return pulumi.get(self, "actions")

    @_builtins.property
    @pulumi.getter
    def condition(self) -> Optional[Mapping[str, Mapping[str, _builtins.str]]]:
        """
        Map of condition operators to JSON expressions
        """
        return pulumi.get(self, "condition")

    @_builtins.property
    @pulumi.getter
    def effect(self) -> Optional[_builtins.str]:
        """
        `Allow` or `Deny`
        """
        return pulumi.get(self, "effect")

    @_builtins.property
    @pulumi.getter
    def principal(self) -> Optional[Mapping[str, Sequence[_builtins.str]]]:
        """
        Map of principal types to ARNs
        """
        return pulumi.get(self, "principal")

    @_builtins.property
    @pulumi.getter
    def resources(self) -> Optional[Sequence[_builtins.str]]:
        """
        List of resource ARNs, e.g. `["arn:aws:s3:::bucket/*"]`
        """
        return pulumi.get(self, "resources")

    @_builtins.property
    @pulumi.getter
    def sid(self) -> Optional[_builtins.str]:
        """
        An optional statement identifier
        """
        return pulumi.get(self, "sid")


