// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.coreweave.NetworkingVpcArgs;
import com.pulumi.coreweave.Utilities;
import com.pulumi.coreweave.inputs.NetworkingVpcState;
import com.pulumi.coreweave.outputs.NetworkingVpcDhcp;
import com.pulumi.coreweave.outputs.NetworkingVpcEgress;
import com.pulumi.coreweave.outputs.NetworkingVpcHostPrefix;
import com.pulumi.coreweave.outputs.NetworkingVpcIngress;
import com.pulumi.coreweave.outputs.NetworkingVpcVpcPrefix;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Create and manage VPCs. Learn more about [CoreWeave VPCs](https://docs.coreweave.com/products/networking/vpc/about-vpcs).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.coreweave.NetworkingVpc;
 * import com.pulumi.coreweave.NetworkingVpcArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcHostPrefixArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcHostPrefixIpamArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcVpcPrefixArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcEgressArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcIngressArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcDhcpArgs;
 * import com.pulumi.coreweave.inputs.NetworkingVpcDhcpDnsArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new NetworkingVpc("example", NetworkingVpcArgs.builder()
 *             .name("default")
 *             .zone("US-EAST-04A")
 *             .hostPrefixes(            
 *                 NetworkingVpcHostPrefixArgs.builder()
 *                     .name("primary")
 *                     .type("PRIMARY")
 *                     .prefixes(                    
 *                         "10.16.192.0/18",
 *                         "2601:db8:aaaa::/48")
 *                     .build(),
 *                 NetworkingVpcHostPrefixArgs.builder()
 *                     .name("container-network")
 *                     .type("ROUTED")
 *                     .prefixes("2601:db8:bbbb::/48")
 *                     .ipam(NetworkingVpcHostPrefixIpamArgs.builder()
 *                         .prefixLength(%!v(PANIC=Format method: fatal: A failure has occurred: unexpected literal type in GenLiteralValueExpression: cty.NumberIntVal(80) (example.pp:12,30-32)))
 *                         .gatewayAddressPolicy("FIRST_IP")
 *                         .build())
 *                     .build(),
 *                 NetworkingVpcHostPrefixArgs.builder()
 *                     .name("attached-network")
 *                     .type("ATTACHED")
 *                     .prefixes("2601:db8:cccc::/48")
 *                     .ipam(NetworkingVpcHostPrefixIpamArgs.builder()
 *                         .prefixLength(%!v(PANIC=Format method: fatal: A failure has occurred: unexpected literal type in GenLiteralValueExpression: cty.NumberIntVal(64) (example.pp:20,22-24)))
 *                         .build())
 *                     .build())
 *             .vpcPrefixes(            
 *                 NetworkingVpcVpcPrefixArgs.builder()
 *                     .name("pod cidr")
 *                     .value("10.0.0.0/13")
 *                     .build(),
 *                 NetworkingVpcVpcPrefixArgs.builder()
 *                     .name("service cidr")
 *                     .value("10.16.0.0/22")
 *                     .build(),
 *                 NetworkingVpcVpcPrefixArgs.builder()
 *                     .name("internal lb cidr")
 *                     .value("10.32.4.0/22")
 *                     .build())
 *             .egress(NetworkingVpcEgressArgs.builder()
 *                 .disablePublicAccess(false)
 *                 .build())
 *             .ingress(NetworkingVpcIngressArgs.builder()
 *                 .disablePublicServices(false)
 *                 .build())
 *             .dhcp(NetworkingVpcDhcpArgs.builder()
 *                 .dns(NetworkingVpcDhcpDnsArgs.builder()
 *                     .servers(                    
 *                         "1.1.1.1",
 *                         "8.8.8.8")
 *                     .build())
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import coreweave:index/networkingVpc:NetworkingVpc default {{id}}
 * ```
 * 
 */
@ResourceType(type="coreweave:index/networkingVpc:NetworkingVpc")
public class NetworkingVpc extends com.pulumi.resources.CustomResource {
    /**
     * Settings affecting DHCP behavior within the VPC.
     * 
     */
    @Export(name="dhcp", refs={NetworkingVpcDhcp.class}, tree="[0]")
    private Output</* @Nullable */ NetworkingVpcDhcp> dhcp;

    /**
     * @return Settings affecting DHCP behavior within the VPC.
     * 
     */
    public Output<Optional<NetworkingVpcDhcp>> dhcp() {
        return Codegen.optional(this.dhcp);
    }
    /**
     * Settings affecting traffic leaving the VPC.
     * 
     */
    @Export(name="egress", refs={NetworkingVpcEgress.class}, tree="[0]")
    private Output<NetworkingVpcEgress> egress;

    /**
     * @return Settings affecting traffic leaving the VPC.
     * 
     */
    public Output<NetworkingVpcEgress> egress() {
        return this.egress;
    }
    /**
     * An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
     * This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
     * This field is immutable once set.
     * 
     * @deprecated
     * `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
     * 
     */
    @Deprecated /* `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`. */
    @Export(name="hostPrefix", refs={String.class}, tree="[0]")
    private Output<String> hostPrefix;

    /**
     * @return An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
     * This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
     * This field is immutable once set.
     * 
     */
    public Output<String> hostPrefix() {
        return this.hostPrefix;
    }
    /**
     * The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
     * 
     */
    @Export(name="hostPrefixes", refs={List.class,NetworkingVpcHostPrefix.class}, tree="[0,1]")
    private Output<List<NetworkingVpcHostPrefix>> hostPrefixes;

    /**
     * @return The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
     * 
     */
    public Output<List<NetworkingVpcHostPrefix>> hostPrefixes() {
        return this.hostPrefixes;
    }
    /**
     * Settings affecting traffic entering the VPC.
     * 
     */
    @Export(name="ingress", refs={NetworkingVpcIngress.class}, tree="[0]")
    private Output<NetworkingVpcIngress> ingress;

    /**
     * @return Settings affecting traffic entering the VPC.
     * 
     */
    public Output<NetworkingVpcIngress> ingress() {
        return this.ingress;
    }
    /**
     * The name of the VPC. Must not be longer than 30 characters.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the VPC. Must not be longer than 30 characters.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
     * 
     */
    @Export(name="vpcPrefixes", refs={List.class,NetworkingVpcVpcPrefix.class}, tree="[0,1]")
    private Output</* @Nullable */ List<NetworkingVpcVpcPrefix>> vpcPrefixes;

    /**
     * @return A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
     * 
     */
    public Output<Optional<List<NetworkingVpcVpcPrefix>>> vpcPrefixes() {
        return Codegen.optional(this.vpcPrefixes);
    }
    /**
     * The Availability Zone in which the VPC is located.
     * 
     */
    @Export(name="zone", refs={String.class}, tree="[0]")
    private Output<String> zone;

    /**
     * @return The Availability Zone in which the VPC is located.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public NetworkingVpc(java.lang.String name) {
        this(name, NetworkingVpcArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public NetworkingVpc(java.lang.String name, NetworkingVpcArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public NetworkingVpc(java.lang.String name, NetworkingVpcArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/networkingVpc:NetworkingVpc", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private NetworkingVpc(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkingVpcState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/networkingVpc:NetworkingVpc", name, state, makeResourceOptions(options, id), false);
    }

    private static NetworkingVpcArgs makeArgs(NetworkingVpcArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NetworkingVpcArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static NetworkingVpc get(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkingVpcState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new NetworkingVpc(name, id, state, options);
    }
}
