// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.coreweave.ObjectStorageBucketLifecycleConfigurationArgs;
import com.pulumi.coreweave.Utilities;
import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationState;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRule;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Lifecycle configurations automate object management by defining actions applied to objects over time, such as expiring objects after a specified period or transitioning them to different storage tiers. This helps optimize storage costs and maintain data hygiene. Lifecycle configurations automate object management by defining actions applied to objects over time, such as expiring objects after a specified period or transitioning them to different storage tiers. This helps optimize storage costs and maintain data hygiene. [Learn more about S3-compatible lifecycle bucket configurations](https://docs.coreweave.com/products/storage/object-storage/reference/object-storage-s3#bucket-lifecycles).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.coreweave.ObjectStorageBucket;
 * import com.pulumi.coreweave.ObjectStorageBucketArgs;
 * import com.pulumi.coreweave.ObjectStorageBucketVersioning;
 * import com.pulumi.coreweave.ObjectStorageBucketVersioningArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketVersioningVersioningConfigurationArgs;
 * import com.pulumi.coreweave.ObjectStorageBucketLifecycleConfiguration;
 * import com.pulumi.coreweave.ObjectStorageBucketLifecycleConfigurationArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleExpirationArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs;
 * import com.pulumi.resources.CustomResourceOptions;
 * import java.util.ArrayList;
 * import java.util.Arrays;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var default_ = new ObjectStorageBucket("default", ObjectStorageBucketArgs.builder()
 *             .name("bucket-lifecycle-example")
 *             .zone("US-EAST-04A")
 *             .build());
 * 
 *         var defaultObjectStorageBucketVersioning = new ObjectStorageBucketVersioning("defaultObjectStorageBucketVersioning", ObjectStorageBucketVersioningArgs.builder()
 *             .bucket(default_.name())
 *             .versioningConfiguration(ObjectStorageBucketVersioningVersioningConfigurationArgs.builder()
 *                 .status("Enabled")
 *                 .build())
 *             .build());
 * 
 *         var defaultObjectStorageBucketLifecycleConfiguration = new ObjectStorageBucketLifecycleConfiguration("defaultObjectStorageBucketLifecycleConfiguration", ObjectStorageBucketLifecycleConfigurationArgs.builder()
 *             .bucket(default_.name())
 *             .rules(            
 *                 ObjectStorageBucketLifecycleConfigurationRuleArgs.builder()
 *                     .id("cleanup-logs")
 *                     .status("Enabled")
 *                     .filter(ObjectStorageBucketLifecycleConfigurationRuleFilterArgs.builder()
 *                         .and(ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs.builder()
 *                             .prefix("logs/")
 *                             .objectSizeGreaterThan(1000000)
 *                             .tags(Map.of("env", "prod"))
 *                             .build())
 *                         .build())
 *                     .expiration(ObjectStorageBucketLifecycleConfigurationRuleExpirationArgs.builder()
 *                         .days(30)
 *                         .build())
 *                     .noncurrentVersionExpiration(ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs.builder()
 *                         .noncurrentDays(7)
 *                         .newerNoncurrentVersions(2)
 *                         .build())
 *                     .build(),
 *                 ObjectStorageBucketLifecycleConfigurationRuleArgs.builder()
 *                     .id("expire-traces")
 *                     .prefix("traces/")
 *                     .status("Enabled")
 *                     .abortIncompleteMultipartUpload(ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs.builder()
 *                         .daysAfterInitiation(5)
 *                         .build())
 *                     .expiration(ObjectStorageBucketLifecycleConfigurationRuleExpirationArgs.builder()
 *                         .date("2026-01-01T00:00:00Z")
 *                         .build())
 *                     .build())
 *             .build(), CustomResourceOptions.builder()
 *                 .dependsOn(defaultObjectStorageBucketVersioning)
 *                 .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration default {{bucket_name}}
 * ```
 * 
 */
@ResourceType(type="coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration")
public class ObjectStorageBucketLifecycleConfiguration extends com.pulumi.resources.CustomResource {
    /**
     * Name of the bucket to apply lifecycle configuration to
     * 
     */
    @Export(name="bucket", refs={String.class}, tree="[0]")
    private Output<String> bucket;

    /**
     * @return Name of the bucket to apply lifecycle configuration to
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }
    /**
     * One or more lifecycle rule blocks
     * 
     */
    @Export(name="rules", refs={List.class,ObjectStorageBucketLifecycleConfigurationRule.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ObjectStorageBucketLifecycleConfigurationRule>> rules;

    /**
     * @return One or more lifecycle rule blocks
     * 
     */
    public Output<Optional<List<ObjectStorageBucketLifecycleConfigurationRule>>> rules() {
        return Codegen.optional(this.rules);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name) {
        this(name, ObjectStorageBucketLifecycleConfigurationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name, ObjectStorageBucketLifecycleConfigurationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name, ObjectStorageBucketLifecycleConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageBucketLifecycleConfiguration(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketLifecycleConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, state, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageBucketLifecycleConfigurationArgs makeArgs(ObjectStorageBucketLifecycleConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageBucketLifecycleConfigurationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageBucketLifecycleConfiguration get(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketLifecycleConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageBucketLifecycleConfiguration(name, id, state, options);
    }
}
