// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.coreweave.ObjectStorageBucketLifecycleConfigurationArgs;
import com.pulumi.coreweave.Utilities;
import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationState;
import com.pulumi.coreweave.outputs.ObjectStorageBucketLifecycleConfigurationRule;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration")
public class ObjectStorageBucketLifecycleConfiguration extends com.pulumi.resources.CustomResource {
    /**
     * Name of the bucket to apply lifecycle configuration to
     * 
     */
    @Export(name="bucket", refs={String.class}, tree="[0]")
    private Output<String> bucket;

    /**
     * @return Name of the bucket to apply lifecycle configuration to
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }
    /**
     * One or more lifecycle rule blocks
     * 
     */
    @Export(name="rules", refs={List.class,ObjectStorageBucketLifecycleConfigurationRule.class}, tree="[0,1]")
    private Output</* @Nullable */ List<ObjectStorageBucketLifecycleConfigurationRule>> rules;

    /**
     * @return One or more lifecycle rule blocks
     * 
     */
    public Output<Optional<List<ObjectStorageBucketLifecycleConfigurationRule>>> rules() {
        return Codegen.optional(this.rules);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name) {
        this(name, ObjectStorageBucketLifecycleConfigurationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name, ObjectStorageBucketLifecycleConfigurationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageBucketLifecycleConfiguration(java.lang.String name, ObjectStorageBucketLifecycleConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageBucketLifecycleConfiguration(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketLifecycleConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration", name, state, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageBucketLifecycleConfigurationArgs makeArgs(ObjectStorageBucketLifecycleConfigurationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageBucketLifecycleConfigurationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageBucketLifecycleConfiguration get(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketLifecycleConfigurationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageBucketLifecycleConfiguration(name, id, state, options);
    }
}
