// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.coreweave.ObjectStorageBucketVersioningArgs;
import com.pulumi.coreweave.Utilities;
import com.pulumi.coreweave.inputs.ObjectStorageBucketVersioningState;
import com.pulumi.coreweave.outputs.ObjectStorageBucketVersioningVersioningConfiguration;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Versioning protects your data by preserving all versions of objects and preventing permanent deletion. When objects are deleted, they are &#34;soft deleted&#34; with delete markers, allowing you to restore previous versions and recover data. After creating a versioned bucket with Terraform, [use `rclone` to manage versioned objects and delete markers](https://docs.coreweave.com/products/storage/object-storage/buckets/rclone-versioned-buckets).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.coreweave.ObjectStorageBucket;
 * import com.pulumi.coreweave.ObjectStorageBucketArgs;
 * import com.pulumi.coreweave.ObjectStorageBucketVersioning;
 * import com.pulumi.coreweave.ObjectStorageBucketVersioningArgs;
 * import com.pulumi.coreweave.inputs.ObjectStorageBucketVersioningVersioningConfigurationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var default_ = new ObjectStorageBucket("default", ObjectStorageBucketArgs.builder()
 *             .name("bucket-versioning-example")
 *             .zone("US-EAST-04A")
 *             .build());
 * 
 *         var defaultObjectStorageBucketVersioning = new ObjectStorageBucketVersioning("defaultObjectStorageBucketVersioning", ObjectStorageBucketVersioningArgs.builder()
 *             .bucket(default_.name())
 *             .versioningConfiguration(ObjectStorageBucketVersioningVersioningConfigurationArgs.builder()
 *                 .status("Enabled")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning default {{bucket_name}}
 * ```
 * 
 */
@ResourceType(type="coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning")
public class ObjectStorageBucketVersioning extends com.pulumi.resources.CustomResource {
    /**
     * The bucket on which to enable or suspend versioning.
     * 
     */
    @Export(name="bucket", refs={String.class}, tree="[0]")
    private Output<String> bucket;

    /**
     * @return The bucket on which to enable or suspend versioning.
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }
    @Export(name="versioningConfiguration", refs={ObjectStorageBucketVersioningVersioningConfiguration.class}, tree="[0]")
    private Output</* @Nullable */ ObjectStorageBucketVersioningVersioningConfiguration> versioningConfiguration;

    public Output<Optional<ObjectStorageBucketVersioningVersioningConfiguration>> versioningConfiguration() {
        return Codegen.optional(this.versioningConfiguration);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageBucketVersioning(java.lang.String name) {
        this(name, ObjectStorageBucketVersioningArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageBucketVersioning(java.lang.String name, ObjectStorageBucketVersioningArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageBucketVersioning(java.lang.String name, ObjectStorageBucketVersioningArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageBucketVersioning(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketVersioningState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning", name, state, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageBucketVersioningArgs makeArgs(ObjectStorageBucketVersioningArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageBucketVersioningArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageBucketVersioning get(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketVersioningState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageBucketVersioning(name, id, state, options);
    }
}
