// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ObjectStorageBucketPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObjectStorageBucketPolicyArgs Empty = new ObjectStorageBucketPolicyArgs();

    /**
     * The name of the bucket for which to apply this policy.
     * 
     */
    @Import(name="bucket", required=true)
    private Output<String> bucket;

    /**
     * @return The name of the bucket for which to apply this policy.
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }

    /**
     * Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
     * 
     */
    @Import(name="policy", required=true)
    private Output<String> policy;

    /**
     * @return Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
     * 
     */
    public Output<String> policy() {
        return this.policy;
    }

    private ObjectStorageBucketPolicyArgs() {}

    private ObjectStorageBucketPolicyArgs(ObjectStorageBucketPolicyArgs $) {
        this.bucket = $.bucket;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObjectStorageBucketPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObjectStorageBucketPolicyArgs $;

        public Builder() {
            $ = new ObjectStorageBucketPolicyArgs();
        }

        public Builder(ObjectStorageBucketPolicyArgs defaults) {
            $ = new ObjectStorageBucketPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucket The name of the bucket for which to apply this policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The name of the bucket for which to apply this policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param policy Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
         * 
         * @return builder
         * 
         */
        public Builder policy(Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public ObjectStorageBucketPolicyArgs build() {
            if ($.bucket == null) {
                throw new MissingRequiredPropertyException("ObjectStorageBucketPolicyArgs", "bucket");
            }
            if ($.policy == null) {
                throw new MissingRequiredPropertyException("ObjectStorageBucketPolicyArgs", "policy");
            }
            return $;
        }
    }

}
