// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.coreweave.ObjectStorageBucketArgs;
import com.pulumi.coreweave.Utilities;
import com.pulumi.coreweave.inputs.ObjectStorageBucketState;
import java.lang.String;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Buckets are the primary organizational containers for your data in CoreWeave AI Object Storage. Bucket names must be globally-unique and not begin with `cw-` or `vip-`, which are reserved for internal use. Learn more about [creating buckets](https://docs.coreweave.com/products/storage/object-storage/buckets/create-bucket).
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.coreweave.ObjectStorageBucket;
 * import com.pulumi.coreweave.ObjectStorageBucketArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var default_ = new ObjectStorageBucket("default", ObjectStorageBucketArgs.builder()
 *             .name("my-tf-test-bucket")
 *             .zone("US-EAST-04A")
 *             .tags(Map.of("foo", "bar"))
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import coreweave:index/objectStorageBucket:ObjectStorageBucket default {{name}}
 * ```
 * 
 */
@ResourceType(type="coreweave:index/objectStorageBucket:ObjectStorageBucket")
public class ObjectStorageBucket extends com.pulumi.resources.CustomResource {
    /**
     * The name of the bucket, must be unique
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the bucket, must be unique
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Map of tags to assign to the bucket.
     * 
     */
    @Export(name="tags", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> tags;

    /**
     * @return Map of tags to assign to the bucket.
     * 
     */
    public Output<Optional<Map<String,String>>> tags() {
        return Codegen.optional(this.tags);
    }
    /**
     * The Availability Zone in which the bucket is located.
     * 
     */
    @Export(name="zone", refs={String.class}, tree="[0]")
    private Output<String> zone;

    /**
     * @return The Availability Zone in which the bucket is located.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ObjectStorageBucket(java.lang.String name) {
        this(name, ObjectStorageBucketArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ObjectStorageBucket(java.lang.String name, ObjectStorageBucketArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ObjectStorageBucket(java.lang.String name, ObjectStorageBucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucket:ObjectStorageBucket", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ObjectStorageBucket(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("coreweave:index/objectStorageBucket:ObjectStorageBucket", name, state, makeResourceOptions(options, id), false);
    }

    private static ObjectStorageBucketArgs makeArgs(ObjectStorageBucketArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ObjectStorageBucketArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ObjectStorageBucket get(java.lang.String name, Output<java.lang.String> id, @Nullable ObjectStorageBucketState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ObjectStorageBucket(name, id, state, options);
    }
}
