// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.coreweave.inputs.ObjectStorageOrganizationAccessPolicyStatementArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObjectStorageOrganizationAccessPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObjectStorageOrganizationAccessPolicyArgs Empty = new ObjectStorageOrganizationAccessPolicyArgs();

    /**
     * The name of the organization access policy, must be unique.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the organization access policy, must be unique.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The list of access policy statements associated with this policy. At least one statement is required.
     * 
     */
    @Import(name="statements", required=true)
    private Output<List<ObjectStorageOrganizationAccessPolicyStatementArgs>> statements;

    /**
     * @return The list of access policy statements associated with this policy. At least one statement is required.
     * 
     */
    public Output<List<ObjectStorageOrganizationAccessPolicyStatementArgs>> statements() {
        return this.statements;
    }

    private ObjectStorageOrganizationAccessPolicyArgs() {}

    private ObjectStorageOrganizationAccessPolicyArgs(ObjectStorageOrganizationAccessPolicyArgs $) {
        this.name = $.name;
        this.statements = $.statements;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObjectStorageOrganizationAccessPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObjectStorageOrganizationAccessPolicyArgs $;

        public Builder() {
            $ = new ObjectStorageOrganizationAccessPolicyArgs();
        }

        public Builder(ObjectStorageOrganizationAccessPolicyArgs defaults) {
            $ = new ObjectStorageOrganizationAccessPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the organization access policy, must be unique.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the organization access policy, must be unique.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param statements The list of access policy statements associated with this policy. At least one statement is required.
         * 
         * @return builder
         * 
         */
        public Builder statements(Output<List<ObjectStorageOrganizationAccessPolicyStatementArgs>> statements) {
            $.statements = statements;
            return this;
        }

        /**
         * @param statements The list of access policy statements associated with this policy. At least one statement is required.
         * 
         * @return builder
         * 
         */
        public Builder statements(List<ObjectStorageOrganizationAccessPolicyStatementArgs> statements) {
            return statements(Output.of(statements));
        }

        /**
         * @param statements The list of access policy statements associated with this policy. At least one statement is required.
         * 
         * @return builder
         * 
         */
        public Builder statements(ObjectStorageOrganizationAccessPolicyStatementArgs... statements) {
            return statements(List.of(statements));
        }

        public ObjectStorageOrganizationAccessPolicyArgs build() {
            if ($.statements == null) {
                throw new MissingRequiredPropertyException("ObjectStorageOrganizationAccessPolicyArgs", "statements");
            }
            return $;
        }
    }

}
