// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * CoreWeave API Endpoint. This can also be set via the COREWEAVE_API_ENDPOINT environment variable, which takes precedence. Defaults to `https://api.coreweave.com/`
     * 
     */
    @Import(name="endpoint")
    private @Nullable Output<String> endpoint;

    /**
     * @return CoreWeave API Endpoint. This can also be set via the COREWEAVE_API_ENDPOINT environment variable, which takes precedence. Defaults to `https://api.coreweave.com/`
     * 
     */
    public Optional<Output<String>> endpoint() {
        return Optional.ofNullable(this.endpoint);
    }

    /**
     * Timeout duration for the HTTP client to use. This can also be set via the COREWEAVE_HTTP_TIMEOUT environment variable, which takes precedence. If unset, defaults to 10 seconds
     * 
     */
    @Import(name="httpTimeout")
    private @Nullable Output<String> httpTimeout;

    /**
     * @return Timeout duration for the HTTP client to use. This can also be set via the COREWEAVE_HTTP_TIMEOUT environment variable, which takes precedence. If unset, defaults to 10 seconds
     * 
     */
    public Optional<Output<String>> httpTimeout() {
        return Optional.ofNullable(this.httpTimeout);
    }

    /**
     * CoreWeave S3 Endpoint, used for CoreWeave Object Storage. This can also be set via the COREWEAVE_S3_ENDPOINT environment variable, which takes precedence. Defaults to `https://cwobject.com`
     * 
     */
    @Import(name="s3Endpoint")
    private @Nullable Output<String> s3Endpoint;

    /**
     * @return CoreWeave S3 Endpoint, used for CoreWeave Object Storage. This can also be set via the COREWEAVE_S3_ENDPOINT environment variable, which takes precedence. Defaults to `https://cwobject.com`
     * 
     */
    public Optional<Output<String>> s3Endpoint() {
        return Optional.ofNullable(this.s3Endpoint);
    }

    /**
     * CoreWeave API Token in the form `CW-SECRET-&lt;secret&gt;`. This can also be set via the COREWEAVE_API_TOKEN environment variable, which takes precedence.
     * 
     */
    @Import(name="token")
    private @Nullable Output<String> token;

    /**
     * @return CoreWeave API Token in the form `CW-SECRET-&lt;secret&gt;`. This can also be set via the COREWEAVE_API_TOKEN environment variable, which takes precedence.
     * 
     */
    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.endpoint = $.endpoint;
        this.httpTimeout = $.httpTimeout;
        this.s3Endpoint = $.s3Endpoint;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param endpoint CoreWeave API Endpoint. This can also be set via the COREWEAVE_API_ENDPOINT environment variable, which takes precedence. Defaults to `https://api.coreweave.com/`
         * 
         * @return builder
         * 
         */
        public Builder endpoint(@Nullable Output<String> endpoint) {
            $.endpoint = endpoint;
            return this;
        }

        /**
         * @param endpoint CoreWeave API Endpoint. This can also be set via the COREWEAVE_API_ENDPOINT environment variable, which takes precedence. Defaults to `https://api.coreweave.com/`
         * 
         * @return builder
         * 
         */
        public Builder endpoint(String endpoint) {
            return endpoint(Output.of(endpoint));
        }

        /**
         * @param httpTimeout Timeout duration for the HTTP client to use. This can also be set via the COREWEAVE_HTTP_TIMEOUT environment variable, which takes precedence. If unset, defaults to 10 seconds
         * 
         * @return builder
         * 
         */
        public Builder httpTimeout(@Nullable Output<String> httpTimeout) {
            $.httpTimeout = httpTimeout;
            return this;
        }

        /**
         * @param httpTimeout Timeout duration for the HTTP client to use. This can also be set via the COREWEAVE_HTTP_TIMEOUT environment variable, which takes precedence. If unset, defaults to 10 seconds
         * 
         * @return builder
         * 
         */
        public Builder httpTimeout(String httpTimeout) {
            return httpTimeout(Output.of(httpTimeout));
        }

        /**
         * @param s3Endpoint CoreWeave S3 Endpoint, used for CoreWeave Object Storage. This can also be set via the COREWEAVE_S3_ENDPOINT environment variable, which takes precedence. Defaults to `https://cwobject.com`
         * 
         * @return builder
         * 
         */
        public Builder s3Endpoint(@Nullable Output<String> s3Endpoint) {
            $.s3Endpoint = s3Endpoint;
            return this;
        }

        /**
         * @param s3Endpoint CoreWeave S3 Endpoint, used for CoreWeave Object Storage. This can also be set via the COREWEAVE_S3_ENDPOINT environment variable, which takes precedence. Defaults to `https://cwobject.com`
         * 
         * @return builder
         * 
         */
        public Builder s3Endpoint(String s3Endpoint) {
            return s3Endpoint(Output.of(s3Endpoint));
        }

        /**
         * @param token CoreWeave API Token in the form `CW-SECRET-&lt;secret&gt;`. This can also be set via the COREWEAVE_API_TOKEN environment variable, which takes precedence.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token CoreWeave API Token in the form `CW-SECRET-&lt;secret&gt;`. This can also be set via the COREWEAVE_API_TOKEN environment variable, which takes precedence.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
