// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class CksClusterNodePortRange
    {
        public readonly int? End;
        public readonly int? Start;

        [OutputConstructor]
        private CksClusterNodePortRange(
            int? end,

            int? start)
        {
            End = end;
            Start = start;
        }
    }
}
