// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class GetNetworkingVpcEgressResult
    {
        /// <summary>
        /// True if the VPC is blocked from consuming public Internet. False otherwise.
        /// </summary>
        public readonly bool DisablePublicAccess;

        [OutputConstructor]
        private GetNetworkingVpcEgressResult(bool disablePublicAccess)
        {
            DisablePublicAccess = disablePublicAccess;
        }
    }
}
