// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class GetNetworkingVpcIngressResult
    {
        /// <summary>
        /// True if the VPC will prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet. False otherwise.
        /// </summary>
        public readonly bool DisablePublicServices;

        [OutputConstructor]
        private GetNetworkingVpcIngressResult(bool disablePublicServices)
        {
            DisablePublicServices = disablePublicServices;
        }
    }
}
