// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class GetNetworkingVpcHostPrefixResult
    {
        /// <summary>
        /// The configuration for a secondary host prefix.
        /// </summary>
        public readonly Outputs.GetNetworkingVpcHostPrefixIpamResult Ipam;
        /// <summary>
        /// The user-specified name of the host prefix.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        /// </summary>
        public readonly ImmutableArray<string> Prefixes;
        /// <summary>
        /// Controls network connectivity from the prefix to the host.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetNetworkingVpcHostPrefixResult(
            Outputs.GetNetworkingVpcHostPrefixIpamResult ipam,

            string name,

            ImmutableArray<string> prefixes,

            string type)
        {
            Ipam = ipam;
            Name = name;
            Prefixes = prefixes;
            Type = type;
        }
    }
}
