// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class GetObjectStorageBucketPolicyDocumentStatementResult
    {
        /// <summary>
        /// List of action strings, e.g. `["s3:PutObject"]`
        /// </summary>
        public readonly ImmutableArray<string> Actions;
        /// <summary>
        /// Map of condition operators to JSON expressions
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableDictionary<string, string>>? Condition;
        /// <summary>
        /// `Allow` or `Deny`
        /// </summary>
        public readonly string? Effect;
        /// <summary>
        /// Map of principal types to ARNs
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableArray<string>>? Principal;
        /// <summary>
        /// List of resource ARNs, e.g. `["arn:aws:s3:::bucket/*"]`
        /// </summary>
        public readonly ImmutableArray<string> Resources;
        /// <summary>
        /// An optional statement identifier
        /// </summary>
        public readonly string? Sid;

        [OutputConstructor]
        private GetObjectStorageBucketPolicyDocumentStatementResult(
            ImmutableArray<string> actions,

            ImmutableDictionary<string, ImmutableDictionary<string, string>>? condition,

            string? effect,

            ImmutableDictionary<string, ImmutableArray<string>>? principal,

            ImmutableArray<string> resources,

            string? sid)
        {
            Actions = actions;
            Condition = condition;
            Effect = effect;
            Principal = principal;
            Resources = resources;
            Sid = sid;
        }
    }
}
