// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class NetworkingVpcHostPrefixIpam
    {
        /// <summary>
        /// Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
        /// </summary>
        public readonly string? GatewayAddressPolicy;
        /// <summary>
        /// The desired length for each Node's allocation from the VPC-wide aggregate prefix.
        /// </summary>
        public readonly int PrefixLength;

        [OutputConstructor]
        private NetworkingVpcHostPrefixIpam(
            string? gatewayAddressPolicy,

            int prefixLength)
        {
            GatewayAddressPolicy = gatewayAddressPolicy;
            PrefixLength = prefixLength;
        }
    }
}
