// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class NetworkingVpcEgress
    {
        /// <summary>
        /// Specifies whether the VPC should be blocked from consuming public Internet.
        /// </summary>
        public readonly bool? DisablePublicAccess;

        [OutputConstructor]
        private NetworkingVpcEgress(bool? disablePublicAccess)
        {
            DisablePublicAccess = disablePublicAccess;
        }
    }
}
