// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class ObjectStorageBucketLifecycleConfigurationRule
    {
        public readonly Outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload? AbortIncompleteMultipartUpload;
        public readonly Outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration? Expiration;
        public readonly Outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter? Filter;
        /// <summary>
        /// Unique identifier for the rule
        /// </summary>
        public readonly string? Id;
        public readonly Outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration? NoncurrentVersionExpiration;
        public readonly ImmutableArray<Outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> NoncurrentVersionTransitions;
        /// <summary>
        /// Object key prefix to which the rule applies
        /// </summary>
        public readonly string? Prefix;
        /// <summary>
        /// Rule status: Enabled or Disabled
        /// </summary>
        public readonly string Status;
        public readonly ImmutableArray<Outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition> Transitions;

        [OutputConstructor]
        private ObjectStorageBucketLifecycleConfigurationRule(
            Outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload? abortIncompleteMultipartUpload,

            Outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration? expiration,

            Outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter? filter,

            string? id,

            Outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration? noncurrentVersionExpiration,

            ImmutableArray<Outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition> noncurrentVersionTransitions,

            string? prefix,

            string status,

            ImmutableArray<Outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition> transitions)
        {
            AbortIncompleteMultipartUpload = abortIncompleteMultipartUpload;
            Expiration = expiration;
            Filter = filter;
            Id = id;
            NoncurrentVersionExpiration = noncurrentVersionExpiration;
            NoncurrentVersionTransitions = noncurrentVersionTransitions;
            Prefix = prefix;
            Status = status;
            Transitions = transitions;
        }
    }
}
