// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class ObjectStorageBucketLifecycleConfigurationRuleTransition
    {
        /// <summary>
        /// ISO8601 date when objects transition
        /// </summary>
        public readonly string? Date;
        /// <summary>
        /// Number of days after object creation for transition
        /// </summary>
        public readonly int? Days;
        /// <summary>
        /// Storage class to transition objects to
        /// </summary>
        public readonly string StorageClass;

        [OutputConstructor]
        private ObjectStorageBucketLifecycleConfigurationRuleTransition(
            string? date,

            int? days,

            string storageClass)
        {
            Date = date;
            Days = days;
            StorageClass = storageClass;
        }
    }
}
