// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Outputs
{

    [OutputType]
    public sealed class ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration
    {
        /// <summary>
        /// Number of noncurrent versions to retain
        /// </summary>
        public readonly int? NewerNoncurrentVersions;
        /// <summary>
        /// Days after becoming noncurrent before deletion
        /// </summary>
        public readonly int? NoncurrentDays;

        [OutputConstructor]
        private ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration(
            int? newerNoncurrentVersions,

            int? noncurrentDays)
        {
            NewerNoncurrentVersions = newerNoncurrentVersions;
            NoncurrentDays = noncurrentDays;
        }
    }
}
