// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.coreweave.inputs.GetObjectStorageBucketPolicyDocumentStatement;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetObjectStorageBucketPolicyDocumentPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetObjectStorageBucketPolicyDocumentPlainArgs Empty = new GetObjectStorageBucketPolicyDocumentPlainArgs();

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="statements")
    private @Nullable List<GetObjectStorageBucketPolicyDocumentStatement> statements;

    public Optional<List<GetObjectStorageBucketPolicyDocumentStatement>> statements() {
        return Optional.ofNullable(this.statements);
    }

    @Import(name="version")
    private @Nullable String version;

    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    private GetObjectStorageBucketPolicyDocumentPlainArgs() {}

    private GetObjectStorageBucketPolicyDocumentPlainArgs(GetObjectStorageBucketPolicyDocumentPlainArgs $) {
        this.id = $.id;
        this.statements = $.statements;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetObjectStorageBucketPolicyDocumentPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetObjectStorageBucketPolicyDocumentPlainArgs $;

        public Builder() {
            $ = new GetObjectStorageBucketPolicyDocumentPlainArgs();
        }

        public Builder(GetObjectStorageBucketPolicyDocumentPlainArgs defaults) {
            $ = new GetObjectStorageBucketPolicyDocumentPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public Builder statements(@Nullable List<GetObjectStorageBucketPolicyDocumentStatement> statements) {
            $.statements = statements;
            return this;
        }

        public Builder statements(GetObjectStorageBucketPolicyDocumentStatement... statements) {
            return statements(List.of(statements));
        }

        public Builder version(@Nullable String version) {
            $.version = version;
            return this;
        }

        public GetObjectStorageBucketPolicyDocumentPlainArgs build() {
            return $;
        }
    }

}
