// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetObjectStorageBucketPolicyDocumentStatementArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetObjectStorageBucketPolicyDocumentStatementArgs Empty = new GetObjectStorageBucketPolicyDocumentStatementArgs();

    /**
     * List of action strings, e.g. `[&#34;s3:PutObject&#34;]`
     * 
     */
    @Import(name="actions")
    private @Nullable Output<List<String>> actions;

    /**
     * @return List of action strings, e.g. `[&#34;s3:PutObject&#34;]`
     * 
     */
    public Optional<Output<List<String>>> actions() {
        return Optional.ofNullable(this.actions);
    }

    /**
     * Map of condition operators to JSON expressions
     * 
     */
    @Import(name="condition")
    private @Nullable Output<Map<String,Map<String,String>>> condition;

    /**
     * @return Map of condition operators to JSON expressions
     * 
     */
    public Optional<Output<Map<String,Map<String,String>>>> condition() {
        return Optional.ofNullable(this.condition);
    }

    /**
     * `Allow` or `Deny`
     * 
     */
    @Import(name="effect")
    private @Nullable Output<String> effect;

    /**
     * @return `Allow` or `Deny`
     * 
     */
    public Optional<Output<String>> effect() {
        return Optional.ofNullable(this.effect);
    }

    /**
     * Map of principal types to ARNs
     * 
     */
    @Import(name="principal")
    private @Nullable Output<Map<String,List<String>>> principal;

    /**
     * @return Map of principal types to ARNs
     * 
     */
    public Optional<Output<Map<String,List<String>>>> principal() {
        return Optional.ofNullable(this.principal);
    }

    /**
     * List of resource ARNs, e.g. `[&#34;arn:aws:s3:::bucket/*&#34;]`
     * 
     */
    @Import(name="resources")
    private @Nullable Output<List<String>> resources;

    /**
     * @return List of resource ARNs, e.g. `[&#34;arn:aws:s3:::bucket/*&#34;]`
     * 
     */
    public Optional<Output<List<String>>> resources() {
        return Optional.ofNullable(this.resources);
    }

    /**
     * An optional statement identifier
     * 
     */
    @Import(name="sid")
    private @Nullable Output<String> sid;

    /**
     * @return An optional statement identifier
     * 
     */
    public Optional<Output<String>> sid() {
        return Optional.ofNullable(this.sid);
    }

    private GetObjectStorageBucketPolicyDocumentStatementArgs() {}

    private GetObjectStorageBucketPolicyDocumentStatementArgs(GetObjectStorageBucketPolicyDocumentStatementArgs $) {
        this.actions = $.actions;
        this.condition = $.condition;
        this.effect = $.effect;
        this.principal = $.principal;
        this.resources = $.resources;
        this.sid = $.sid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetObjectStorageBucketPolicyDocumentStatementArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetObjectStorageBucketPolicyDocumentStatementArgs $;

        public Builder() {
            $ = new GetObjectStorageBucketPolicyDocumentStatementArgs();
        }

        public Builder(GetObjectStorageBucketPolicyDocumentStatementArgs defaults) {
            $ = new GetObjectStorageBucketPolicyDocumentStatementArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions List of action strings, e.g. `[&#34;s3:PutObject&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder actions(@Nullable Output<List<String>> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions List of action strings, e.g. `[&#34;s3:PutObject&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder actions(List<String> actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param actions List of action strings, e.g. `[&#34;s3:PutObject&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        /**
         * @param condition Map of condition operators to JSON expressions
         * 
         * @return builder
         * 
         */
        public Builder condition(@Nullable Output<Map<String,Map<String,String>>> condition) {
            $.condition = condition;
            return this;
        }

        /**
         * @param condition Map of condition operators to JSON expressions
         * 
         * @return builder
         * 
         */
        public Builder condition(Map<String,Map<String,String>> condition) {
            return condition(Output.of(condition));
        }

        /**
         * @param effect `Allow` or `Deny`
         * 
         * @return builder
         * 
         */
        public Builder effect(@Nullable Output<String> effect) {
            $.effect = effect;
            return this;
        }

        /**
         * @param effect `Allow` or `Deny`
         * 
         * @return builder
         * 
         */
        public Builder effect(String effect) {
            return effect(Output.of(effect));
        }

        /**
         * @param principal Map of principal types to ARNs
         * 
         * @return builder
         * 
         */
        public Builder principal(@Nullable Output<Map<String,List<String>>> principal) {
            $.principal = principal;
            return this;
        }

        /**
         * @param principal Map of principal types to ARNs
         * 
         * @return builder
         * 
         */
        public Builder principal(Map<String,List<String>> principal) {
            return principal(Output.of(principal));
        }

        /**
         * @param resources List of resource ARNs, e.g. `[&#34;arn:aws:s3:::bucket/*&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder resources(@Nullable Output<List<String>> resources) {
            $.resources = resources;
            return this;
        }

        /**
         * @param resources List of resource ARNs, e.g. `[&#34;arn:aws:s3:::bucket/*&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder resources(List<String> resources) {
            return resources(Output.of(resources));
        }

        /**
         * @param resources List of resource ARNs, e.g. `[&#34;arn:aws:s3:::bucket/*&#34;]`
         * 
         * @return builder
         * 
         */
        public Builder resources(String... resources) {
            return resources(List.of(resources));
        }

        /**
         * @param sid An optional statement identifier
         * 
         * @return builder
         * 
         */
        public Builder sid(@Nullable Output<String> sid) {
            $.sid = sid;
            return this;
        }

        /**
         * @param sid An optional statement identifier
         * 
         * @return builder
         * 
         */
        public Builder sid(String sid) {
            return sid(Output.of(sid));
        }

        public GetObjectStorageBucketPolicyDocumentStatementArgs build() {
            return $;
        }
    }

}
