// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkingVpcDhcpDnsArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkingVpcDhcpDnsArgs Empty = new NetworkingVpcDhcpDnsArgs();

    /**
     * The DNS servers to be used by DHCP clients within the VPC.
     * 
     */
    @Import(name="servers")
    private @Nullable Output<List<String>> servers;

    /**
     * @return The DNS servers to be used by DHCP clients within the VPC.
     * 
     */
    public Optional<Output<List<String>>> servers() {
        return Optional.ofNullable(this.servers);
    }

    private NetworkingVpcDhcpDnsArgs() {}

    private NetworkingVpcDhcpDnsArgs(NetworkingVpcDhcpDnsArgs $) {
        this.servers = $.servers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkingVpcDhcpDnsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkingVpcDhcpDnsArgs $;

        public Builder() {
            $ = new NetworkingVpcDhcpDnsArgs();
        }

        public Builder(NetworkingVpcDhcpDnsArgs defaults) {
            $ = new NetworkingVpcDhcpDnsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param servers The DNS servers to be used by DHCP clients within the VPC.
         * 
         * @return builder
         * 
         */
        public Builder servers(@Nullable Output<List<String>> servers) {
            $.servers = servers;
            return this;
        }

        /**
         * @param servers The DNS servers to be used by DHCP clients within the VPC.
         * 
         * @return builder
         * 
         */
        public Builder servers(List<String> servers) {
            return servers(Output.of(servers));
        }

        /**
         * @param servers The DNS servers to be used by DHCP clients within the VPC.
         * 
         * @return builder
         * 
         */
        public Builder servers(String... servers) {
            return servers(List.of(servers));
        }

        public NetworkingVpcDhcpDnsArgs build() {
            return $;
        }
    }

}
