// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObjectStorageBucketPolicyState extends com.pulumi.resources.ResourceArgs {

    public static final ObjectStorageBucketPolicyState Empty = new ObjectStorageBucketPolicyState();

    /**
     * The name of the bucket for which to apply this policy.
     * 
     */
    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    /**
     * @return The name of the bucket for which to apply this policy.
     * 
     */
    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    /**
     * Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
     * 
     */
    @Import(name="policy")
    private @Nullable Output<String> policy;

    /**
     * @return Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
     * 
     */
    public Optional<Output<String>> policy() {
        return Optional.ofNullable(this.policy);
    }

    private ObjectStorageBucketPolicyState() {}

    private ObjectStorageBucketPolicyState(ObjectStorageBucketPolicyState $) {
        this.bucket = $.bucket;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObjectStorageBucketPolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObjectStorageBucketPolicyState $;

        public Builder() {
            $ = new ObjectStorageBucketPolicyState();
        }

        public Builder(ObjectStorageBucketPolicyState defaults) {
            $ = new ObjectStorageBucketPolicyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucket The name of the bucket for which to apply this policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The name of the bucket for which to apply this policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param policy Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
         * 
         * @return builder
         * 
         */
        public Builder policy(@Nullable Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy Text of the policy. Must be valid JSON. The coreweave.getObjectStorageBucketPolicyDocument data source may be used, simply reference the `.json` attribute of the data source.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public ObjectStorageBucketPolicyState build() {
            return $;
        }
    }

}
