// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs;
import com.pulumi.coreweave.inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterTagArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObjectStorageBucketLifecycleConfigurationRuleFilterArgs extends com.pulumi.resources.ResourceArgs {

    public static final ObjectStorageBucketLifecycleConfigurationRuleFilterArgs Empty = new ObjectStorageBucketLifecycleConfigurationRuleFilterArgs();

    /**
     * Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
     * 
     */
    @Import(name="and")
    private @Nullable Output<ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs> and;

    /**
     * @return Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
     * 
     */
    public Optional<Output<ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs>> and() {
        return Optional.ofNullable(this.and);
    }

    /**
     * Minimum object size (in bytes) to which the rule applies.
     * 
     */
    @Import(name="objectSizeGreaterThan")
    private @Nullable Output<Integer> objectSizeGreaterThan;

    /**
     * @return Minimum object size (in bytes) to which the rule applies.
     * 
     */
    public Optional<Output<Integer>> objectSizeGreaterThan() {
        return Optional.ofNullable(this.objectSizeGreaterThan);
    }

    /**
     * Maximum object size (in bytes) to which the rule applies.
     * 
     */
    @Import(name="objectSizeLessThan")
    private @Nullable Output<Integer> objectSizeLessThan;

    /**
     * @return Maximum object size (in bytes) to which the rule applies.
     * 
     */
    public Optional<Output<Integer>> objectSizeLessThan() {
        return Optional.ofNullable(this.objectSizeLessThan);
    }

    /**
     * Prefix filter
     * 
     */
    @Import(name="prefix")
    private @Nullable Output<String> prefix;

    /**
     * @return Prefix filter
     * 
     */
    public Optional<Output<String>> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    @Import(name="tag")
    private @Nullable Output<ObjectStorageBucketLifecycleConfigurationRuleFilterTagArgs> tag;

    public Optional<Output<ObjectStorageBucketLifecycleConfigurationRuleFilterTagArgs>> tag() {
        return Optional.ofNullable(this.tag);
    }

    private ObjectStorageBucketLifecycleConfigurationRuleFilterArgs() {}

    private ObjectStorageBucketLifecycleConfigurationRuleFilterArgs(ObjectStorageBucketLifecycleConfigurationRuleFilterArgs $) {
        this.and = $.and;
        this.objectSizeGreaterThan = $.objectSizeGreaterThan;
        this.objectSizeLessThan = $.objectSizeLessThan;
        this.prefix = $.prefix;
        this.tag = $.tag;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObjectStorageBucketLifecycleConfigurationRuleFilterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObjectStorageBucketLifecycleConfigurationRuleFilterArgs $;

        public Builder() {
            $ = new ObjectStorageBucketLifecycleConfigurationRuleFilterArgs();
        }

        public Builder(ObjectStorageBucketLifecycleConfigurationRuleFilterArgs defaults) {
            $ = new ObjectStorageBucketLifecycleConfigurationRuleFilterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param and Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
         * 
         * @return builder
         * 
         */
        public Builder and(@Nullable Output<ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs> and) {
            $.and = and;
            return this;
        }

        /**
         * @param and Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
         * 
         * @return builder
         * 
         */
        public Builder and(ObjectStorageBucketLifecycleConfigurationRuleFilterAndArgs and) {
            return and(Output.of(and));
        }

        /**
         * @param objectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
         * 
         * @return builder
         * 
         */
        public Builder objectSizeGreaterThan(@Nullable Output<Integer> objectSizeGreaterThan) {
            $.objectSizeGreaterThan = objectSizeGreaterThan;
            return this;
        }

        /**
         * @param objectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
         * 
         * @return builder
         * 
         */
        public Builder objectSizeGreaterThan(Integer objectSizeGreaterThan) {
            return objectSizeGreaterThan(Output.of(objectSizeGreaterThan));
        }

        /**
         * @param objectSizeLessThan Maximum object size (in bytes) to which the rule applies.
         * 
         * @return builder
         * 
         */
        public Builder objectSizeLessThan(@Nullable Output<Integer> objectSizeLessThan) {
            $.objectSizeLessThan = objectSizeLessThan;
            return this;
        }

        /**
         * @param objectSizeLessThan Maximum object size (in bytes) to which the rule applies.
         * 
         * @return builder
         * 
         */
        public Builder objectSizeLessThan(Integer objectSizeLessThan) {
            return objectSizeLessThan(Output.of(objectSizeLessThan));
        }

        /**
         * @param prefix Prefix filter
         * 
         * @return builder
         * 
         */
        public Builder prefix(@Nullable Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param prefix Prefix filter
         * 
         * @return builder
         * 
         */
        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        public Builder tag(@Nullable Output<ObjectStorageBucketLifecycleConfigurationRuleFilterTagArgs> tag) {
            $.tag = tag;
            return this;
        }

        public Builder tag(ObjectStorageBucketLifecycleConfigurationRuleFilterTagArgs tag) {
            return tag(Output.of(tag));
        }

        public ObjectStorageBucketLifecycleConfigurationRuleFilterArgs build() {
            return $;
        }
    }

}
