// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.coreweave.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ObjectStorageBucketSettingsState extends com.pulumi.resources.ResourceArgs {

    public static final ObjectStorageBucketSettingsState Empty = new ObjectStorageBucketSettingsState();

    /**
     * Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
     * 
     */
    @Import(name="auditLoggingEnabled")
    private @Nullable Output<Boolean> auditLoggingEnabled;

    /**
     * @return Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
     * 
     */
    public Optional<Output<Boolean>> auditLoggingEnabled() {
        return Optional.ofNullable(this.auditLoggingEnabled);
    }

    /**
     * The name of the bucket to manage settings for.
     * 
     */
    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    /**
     * @return The name of the bucket to manage settings for.
     * 
     */
    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    private ObjectStorageBucketSettingsState() {}

    private ObjectStorageBucketSettingsState(ObjectStorageBucketSettingsState $) {
        this.auditLoggingEnabled = $.auditLoggingEnabled;
        this.bucket = $.bucket;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ObjectStorageBucketSettingsState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ObjectStorageBucketSettingsState $;

        public Builder() {
            $ = new ObjectStorageBucketSettingsState();
        }

        public Builder(ObjectStorageBucketSettingsState defaults) {
            $ = new ObjectStorageBucketSettingsState(Objects.requireNonNull(defaults));
        }

        /**
         * @param auditLoggingEnabled Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
         * 
         * @return builder
         * 
         */
        public Builder auditLoggingEnabled(@Nullable Output<Boolean> auditLoggingEnabled) {
            $.auditLoggingEnabled = auditLoggingEnabled;
            return this;
        }

        /**
         * @param auditLoggingEnabled Whether audit logging is enabled for the bucket. Note: please contact support to enable audit logging for your organization before enabling.
         * 
         * @return builder
         * 
         */
        public Builder auditLoggingEnabled(Boolean auditLoggingEnabled) {
            return auditLoggingEnabled(Output.of(auditLoggingEnabled));
        }

        /**
         * @param bucket The name of the bucket to manage settings for.
         * 
         * @return builder
         * 
         */
        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The name of the bucket to manage settings for.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        public ObjectStorageBucketSettingsState build() {
            return $;
        }
    }

}
