// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coreweave

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Query information about an existing VPC by ID. See the [CoreWeave VPC API reference](https://docs.coreweave.com/products/networking/vpc/vpc-api).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coreweave.GetNetworkingVpc(ctx, &coreweave.LookupNetworkingVpcArgs{
//				Id: "1063bce6-6e5b-4b0a-b73a-7e6106b2a77c",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupNetworkingVpc(ctx *pulumi.Context, args *LookupNetworkingVpcArgs, opts ...pulumi.InvokeOption) (*LookupNetworkingVpcResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetworkingVpcResult
	err := ctx.Invoke("coreweave:index/getNetworkingVpc:getNetworkingVpc", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkingVpc.
type LookupNetworkingVpcArgs struct {
	// The ID of the VPC.
	Id string `pulumi:"id"`
}

// A collection of values returned by getNetworkingVpc.
type LookupNetworkingVpcResult struct {
	// Settings affecting DHCP behavior within the VPC.
	Dhcp GetNetworkingVpcDhcp `pulumi:"dhcp"`
	// Settings affecting traffic leaving the VPC.
	Egress GetNetworkingVpcEgress `pulumi:"egress"`
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	//
	// Deprecated: Configure hostPrefixes instead.
	HostPrefix string `pulumi:"hostPrefix"`
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes []GetNetworkingVpcHostPrefix `pulumi:"hostPrefixes"`
	// The ID of the VPC.
	Id string `pulumi:"id"`
	// Settings affecting traffic entering the VPC.
	Ingress GetNetworkingVpcIngress `pulumi:"ingress"`
	// The name of the VPC.
	Name string `pulumi:"name"`
	// A list of additional named IPv4 prefixes for the VPC.
	VpcPrefixes []GetNetworkingVpcVpcPrefix `pulumi:"vpcPrefixes"`
	// The Availability Zone in which the VPC is located.
	Zone string `pulumi:"zone"`
}

func LookupNetworkingVpcOutput(ctx *pulumi.Context, args LookupNetworkingVpcOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkingVpcResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("coreweave:index/getNetworkingVpc:getNetworkingVpc", args, LookupNetworkingVpcResultOutput{}, options).(LookupNetworkingVpcResultOutput)
}

// A collection of arguments for invoking getNetworkingVpc.
type LookupNetworkingVpcOutputArgs struct {
	// The ID of the VPC.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupNetworkingVpcOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkingVpcArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkingVpc.
type LookupNetworkingVpcResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkingVpcResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkingVpcResult)(nil)).Elem()
}

func (o LookupNetworkingVpcResultOutput) ToLookupNetworkingVpcResultOutput() LookupNetworkingVpcResultOutput {
	return o
}

func (o LookupNetworkingVpcResultOutput) ToLookupNetworkingVpcResultOutputWithContext(ctx context.Context) LookupNetworkingVpcResultOutput {
	return o
}

// Settings affecting DHCP behavior within the VPC.
func (o LookupNetworkingVpcResultOutput) Dhcp() GetNetworkingVpcDhcpOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) GetNetworkingVpcDhcp { return v.Dhcp }).(GetNetworkingVpcDhcpOutput)
}

// Settings affecting traffic leaving the VPC.
func (o LookupNetworkingVpcResultOutput) Egress() GetNetworkingVpcEgressOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) GetNetworkingVpcEgress { return v.Egress }).(GetNetworkingVpcEgressOutput)
}

// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
//
// Deprecated: Configure hostPrefixes instead.
func (o LookupNetworkingVpcResultOutput) HostPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) string { return v.HostPrefix }).(pulumi.StringOutput)
}

// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
func (o LookupNetworkingVpcResultOutput) HostPrefixes() GetNetworkingVpcHostPrefixArrayOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) []GetNetworkingVpcHostPrefix { return v.HostPrefixes }).(GetNetworkingVpcHostPrefixArrayOutput)
}

// The ID of the VPC.
func (o LookupNetworkingVpcResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) string { return v.Id }).(pulumi.StringOutput)
}

// Settings affecting traffic entering the VPC.
func (o LookupNetworkingVpcResultOutput) Ingress() GetNetworkingVpcIngressOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) GetNetworkingVpcIngress { return v.Ingress }).(GetNetworkingVpcIngressOutput)
}

// The name of the VPC.
func (o LookupNetworkingVpcResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) string { return v.Name }).(pulumi.StringOutput)
}

// A list of additional named IPv4 prefixes for the VPC.
func (o LookupNetworkingVpcResultOutput) VpcPrefixes() GetNetworkingVpcVpcPrefixArrayOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) []GetNetworkingVpcVpcPrefix { return v.VpcPrefixes }).(GetNetworkingVpcVpcPrefixArrayOutput)
}

// The Availability Zone in which the VPC is located.
func (o LookupNetworkingVpcResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkingVpcResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkingVpcResultOutput{})
}
