// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coreweave

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// [Bucket access policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/bucket-policies) allow you to define precise, S3-compatible access control for one bucket. They are evaluated after organization access policies. See [Manage Bucket Policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/manage-bucket-policies#example-policies) for examples and further information. This data source provides a type-safe data structure for creating an S3-compatible JSON bucket policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := coreweave.GetObjectStorageBucketPolicyDocument(ctx, &coreweave.GetObjectStorageBucketPolicyDocumentArgs{
//				Version: pulumi.StringRef("2012-10-17"),
//				Statements: []coreweave.GetObjectStorageBucketPolicyDocumentStatement{
//					{
//						Sid:    pulumi.StringRef("allow-all"),
//						Effect: pulumi.StringRef("Allow"),
//						Actions: []string{
//							"s3:*",
//						},
//						Resources: []string{
//							"arn:aws:s3:::*",
//						},
//						Principal: {
//							"CW": []string{
//								"*",
//							},
//						},
//					},
//				},
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetObjectStorageBucketPolicyDocument(ctx *pulumi.Context, args *GetObjectStorageBucketPolicyDocumentArgs, opts ...pulumi.InvokeOption) (*GetObjectStorageBucketPolicyDocumentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetObjectStorageBucketPolicyDocumentResult
	err := ctx.Invoke("coreweave:index/getObjectStorageBucketPolicyDocument:getObjectStorageBucketPolicyDocument", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorageBucketPolicyDocument.
type GetObjectStorageBucketPolicyDocumentArgs struct {
	// An optional policy identifier
	Id *string `pulumi:"id"`
	// The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
	Statements []GetObjectStorageBucketPolicyDocumentStatement `pulumi:"statements"`
	// The policy version, e.g. `"2012-10-17"`
	Version *string `pulumi:"version"`
}

// A collection of values returned by getObjectStorageBucketPolicyDocument.
type GetObjectStorageBucketPolicyDocumentResult struct {
	// An optional policy identifier
	Id *string `pulumi:"id"`
	// The rendered policy document as JSON
	Json string `pulumi:"json"`
	// The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
	Statements []GetObjectStorageBucketPolicyDocumentStatement `pulumi:"statements"`
	// The policy version, e.g. `"2012-10-17"`
	Version *string `pulumi:"version"`
}

func GetObjectStorageBucketPolicyDocumentOutput(ctx *pulumi.Context, args GetObjectStorageBucketPolicyDocumentOutputArgs, opts ...pulumi.InvokeOption) GetObjectStorageBucketPolicyDocumentResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetObjectStorageBucketPolicyDocumentResultOutput, error) {
			args := v.(GetObjectStorageBucketPolicyDocumentArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("coreweave:index/getObjectStorageBucketPolicyDocument:getObjectStorageBucketPolicyDocument", args, GetObjectStorageBucketPolicyDocumentResultOutput{}, options).(GetObjectStorageBucketPolicyDocumentResultOutput), nil
		}).(GetObjectStorageBucketPolicyDocumentResultOutput)
}

// A collection of arguments for invoking getObjectStorageBucketPolicyDocument.
type GetObjectStorageBucketPolicyDocumentOutputArgs struct {
	// An optional policy identifier
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
	Statements GetObjectStorageBucketPolicyDocumentStatementArrayInput `pulumi:"statements"`
	// The policy version, e.g. `"2012-10-17"`
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (GetObjectStorageBucketPolicyDocumentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageBucketPolicyDocumentArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorageBucketPolicyDocument.
type GetObjectStorageBucketPolicyDocumentResultOutput struct{ *pulumi.OutputState }

func (GetObjectStorageBucketPolicyDocumentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageBucketPolicyDocumentResult)(nil)).Elem()
}

func (o GetObjectStorageBucketPolicyDocumentResultOutput) ToGetObjectStorageBucketPolicyDocumentResultOutput() GetObjectStorageBucketPolicyDocumentResultOutput {
	return o
}

func (o GetObjectStorageBucketPolicyDocumentResultOutput) ToGetObjectStorageBucketPolicyDocumentResultOutputWithContext(ctx context.Context) GetObjectStorageBucketPolicyDocumentResultOutput {
	return o
}

// An optional policy identifier
func (o GetObjectStorageBucketPolicyDocumentResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetObjectStorageBucketPolicyDocumentResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The rendered policy document as JSON
func (o GetObjectStorageBucketPolicyDocumentResultOutput) Json() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageBucketPolicyDocumentResult) string { return v.Json }).(pulumi.StringOutput)
}

// The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
func (o GetObjectStorageBucketPolicyDocumentResultOutput) Statements() GetObjectStorageBucketPolicyDocumentStatementArrayOutput {
	return o.ApplyT(func(v GetObjectStorageBucketPolicyDocumentResult) []GetObjectStorageBucketPolicyDocumentStatement {
		return v.Statements
	}).(GetObjectStorageBucketPolicyDocumentStatementArrayOutput)
}

// The policy version, e.g. `"2012-10-17"`
func (o GetObjectStorageBucketPolicyDocumentResultOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetObjectStorageBucketPolicyDocumentResult) *string { return v.Version }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetObjectStorageBucketPolicyDocumentResultOutput{})
}
