// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coreweave

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "coreweave:index/cksCluster:CksCluster":
		r = &CksCluster{}
	case "coreweave:index/networkingVpc:NetworkingVpc":
		r = &NetworkingVpc{}
	case "coreweave:index/objectStorageBucket:ObjectStorageBucket":
		r = &ObjectStorageBucket{}
	case "coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration":
		r = &ObjectStorageBucketLifecycleConfiguration{}
	case "coreweave:index/objectStorageBucketPolicy:ObjectStorageBucketPolicy":
		r = &ObjectStorageBucketPolicy{}
	case "coreweave:index/objectStorageBucketSettings:ObjectStorageBucketSettings":
		r = &ObjectStorageBucketSettings{}
	case "coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning":
		r = &ObjectStorageBucketVersioning{}
	case "coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy":
		r = &ObjectStorageOrganizationAccessPolicy{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:coreweave" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/cksCluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/networkingVpc",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageBucket",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageBucketLifecycleConfiguration",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageBucketPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageBucketSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageBucketVersioning",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"coreweave",
		"index/objectStorageOrganizationAccessPolicy",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"coreweave",
		&pkg{version},
	)
}
