// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coreweave

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkingVpc struct {
	pulumi.CustomResourceState

	// Settings affecting DHCP behavior within the VPC.
	Dhcp NetworkingVpcDhcpPtrOutput `pulumi:"dhcp"`
	// Settings affecting traffic leaving the VPC.
	Egress NetworkingVpcEgressOutput `pulumi:"egress"`
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
	// This field is immutable once set.
	//
	// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
	HostPrefix pulumi.StringOutput `pulumi:"hostPrefix"`
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes NetworkingVpcHostPrefixArrayOutput `pulumi:"hostPrefixes"`
	// Settings affecting traffic entering the VPC.
	Ingress NetworkingVpcIngressOutput `pulumi:"ingress"`
	// The name of the VPC. Must not be longer than 30 characters.
	Name pulumi.StringOutput `pulumi:"name"`
	// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
	VpcPrefixes NetworkingVpcVpcPrefixArrayOutput `pulumi:"vpcPrefixes"`
	// The Availability Zone in which the VPC is located.
	Zone pulumi.StringOutput `pulumi:"zone"`
}

// NewNetworkingVpc registers a new resource with the given unique name, arguments, and options.
func NewNetworkingVpc(ctx *pulumi.Context,
	name string, args *NetworkingVpcArgs, opts ...pulumi.ResourceOption) (*NetworkingVpc, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Zone == nil {
		return nil, errors.New("invalid value for required argument 'Zone'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NetworkingVpc
	err := ctx.RegisterResource("coreweave:index/networkingVpc:NetworkingVpc", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkingVpc gets an existing NetworkingVpc resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkingVpc(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkingVpcState, opts ...pulumi.ResourceOption) (*NetworkingVpc, error) {
	var resource NetworkingVpc
	err := ctx.ReadResource("coreweave:index/networkingVpc:NetworkingVpc", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkingVpc resources.
type networkingVpcState struct {
	// Settings affecting DHCP behavior within the VPC.
	Dhcp *NetworkingVpcDhcp `pulumi:"dhcp"`
	// Settings affecting traffic leaving the VPC.
	Egress *NetworkingVpcEgress `pulumi:"egress"`
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
	// This field is immutable once set.
	//
	// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
	HostPrefix *string `pulumi:"hostPrefix"`
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes []NetworkingVpcHostPrefix `pulumi:"hostPrefixes"`
	// Settings affecting traffic entering the VPC.
	Ingress *NetworkingVpcIngress `pulumi:"ingress"`
	// The name of the VPC. Must not be longer than 30 characters.
	Name *string `pulumi:"name"`
	// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
	VpcPrefixes []NetworkingVpcVpcPrefix `pulumi:"vpcPrefixes"`
	// The Availability Zone in which the VPC is located.
	Zone *string `pulumi:"zone"`
}

type NetworkingVpcState struct {
	// Settings affecting DHCP behavior within the VPC.
	Dhcp NetworkingVpcDhcpPtrInput
	// Settings affecting traffic leaving the VPC.
	Egress NetworkingVpcEgressPtrInput
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
	// This field is immutable once set.
	//
	// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
	HostPrefix pulumi.StringPtrInput
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes NetworkingVpcHostPrefixArrayInput
	// Settings affecting traffic entering the VPC.
	Ingress NetworkingVpcIngressPtrInput
	// The name of the VPC. Must not be longer than 30 characters.
	Name pulumi.StringPtrInput
	// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
	VpcPrefixes NetworkingVpcVpcPrefixArrayInput
	// The Availability Zone in which the VPC is located.
	Zone pulumi.StringPtrInput
}

func (NetworkingVpcState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkingVpcState)(nil)).Elem()
}

type networkingVpcArgs struct {
	// Settings affecting DHCP behavior within the VPC.
	Dhcp *NetworkingVpcDhcp `pulumi:"dhcp"`
	// Settings affecting traffic leaving the VPC.
	Egress *NetworkingVpcEgress `pulumi:"egress"`
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
	// This field is immutable once set.
	//
	// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
	HostPrefix *string `pulumi:"hostPrefix"`
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes []NetworkingVpcHostPrefix `pulumi:"hostPrefixes"`
	// Settings affecting traffic entering the VPC.
	Ingress *NetworkingVpcIngress `pulumi:"ingress"`
	// The name of the VPC. Must not be longer than 30 characters.
	Name *string `pulumi:"name"`
	// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
	VpcPrefixes []NetworkingVpcVpcPrefix `pulumi:"vpcPrefixes"`
	// The Availability Zone in which the VPC is located.
	Zone string `pulumi:"zone"`
}

// The set of arguments for constructing a NetworkingVpc resource.
type NetworkingVpcArgs struct {
	// Settings affecting DHCP behavior within the VPC.
	Dhcp NetworkingVpcDhcpPtrInput
	// Settings affecting traffic leaving the VPC.
	Egress NetworkingVpcEgressPtrInput
	// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
	// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
	// This field is immutable once set.
	//
	// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
	HostPrefix pulumi.StringPtrInput
	// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
	HostPrefixes NetworkingVpcHostPrefixArrayInput
	// Settings affecting traffic entering the VPC.
	Ingress NetworkingVpcIngressPtrInput
	// The name of the VPC. Must not be longer than 30 characters.
	Name pulumi.StringPtrInput
	// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
	VpcPrefixes NetworkingVpcVpcPrefixArrayInput
	// The Availability Zone in which the VPC is located.
	Zone pulumi.StringInput
}

func (NetworkingVpcArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkingVpcArgs)(nil)).Elem()
}

type NetworkingVpcInput interface {
	pulumi.Input

	ToNetworkingVpcOutput() NetworkingVpcOutput
	ToNetworkingVpcOutputWithContext(ctx context.Context) NetworkingVpcOutput
}

func (*NetworkingVpc) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkingVpc)(nil)).Elem()
}

func (i *NetworkingVpc) ToNetworkingVpcOutput() NetworkingVpcOutput {
	return i.ToNetworkingVpcOutputWithContext(context.Background())
}

func (i *NetworkingVpc) ToNetworkingVpcOutputWithContext(ctx context.Context) NetworkingVpcOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingVpcOutput)
}

// NetworkingVpcArrayInput is an input type that accepts NetworkingVpcArray and NetworkingVpcArrayOutput values.
// You can construct a concrete instance of `NetworkingVpcArrayInput` via:
//
//	NetworkingVpcArray{ NetworkingVpcArgs{...} }
type NetworkingVpcArrayInput interface {
	pulumi.Input

	ToNetworkingVpcArrayOutput() NetworkingVpcArrayOutput
	ToNetworkingVpcArrayOutputWithContext(context.Context) NetworkingVpcArrayOutput
}

type NetworkingVpcArray []NetworkingVpcInput

func (NetworkingVpcArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkingVpc)(nil)).Elem()
}

func (i NetworkingVpcArray) ToNetworkingVpcArrayOutput() NetworkingVpcArrayOutput {
	return i.ToNetworkingVpcArrayOutputWithContext(context.Background())
}

func (i NetworkingVpcArray) ToNetworkingVpcArrayOutputWithContext(ctx context.Context) NetworkingVpcArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingVpcArrayOutput)
}

// NetworkingVpcMapInput is an input type that accepts NetworkingVpcMap and NetworkingVpcMapOutput values.
// You can construct a concrete instance of `NetworkingVpcMapInput` via:
//
//	NetworkingVpcMap{ "key": NetworkingVpcArgs{...} }
type NetworkingVpcMapInput interface {
	pulumi.Input

	ToNetworkingVpcMapOutput() NetworkingVpcMapOutput
	ToNetworkingVpcMapOutputWithContext(context.Context) NetworkingVpcMapOutput
}

type NetworkingVpcMap map[string]NetworkingVpcInput

func (NetworkingVpcMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkingVpc)(nil)).Elem()
}

func (i NetworkingVpcMap) ToNetworkingVpcMapOutput() NetworkingVpcMapOutput {
	return i.ToNetworkingVpcMapOutputWithContext(context.Background())
}

func (i NetworkingVpcMap) ToNetworkingVpcMapOutputWithContext(ctx context.Context) NetworkingVpcMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingVpcMapOutput)
}

type NetworkingVpcOutput struct{ *pulumi.OutputState }

func (NetworkingVpcOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkingVpc)(nil)).Elem()
}

func (o NetworkingVpcOutput) ToNetworkingVpcOutput() NetworkingVpcOutput {
	return o
}

func (o NetworkingVpcOutput) ToNetworkingVpcOutputWithContext(ctx context.Context) NetworkingVpcOutput {
	return o
}

// Settings affecting DHCP behavior within the VPC.
func (o NetworkingVpcOutput) Dhcp() NetworkingVpcDhcpPtrOutput {
	return o.ApplyT(func(v *NetworkingVpc) NetworkingVpcDhcpPtrOutput { return v.Dhcp }).(NetworkingVpcDhcpPtrOutput)
}

// Settings affecting traffic leaving the VPC.
func (o NetworkingVpcOutput) Egress() NetworkingVpcEgressOutput {
	return o.ApplyT(func(v *NetworkingVpc) NetworkingVpcEgressOutput { return v.Egress }).(NetworkingVpcEgressOutput)
}

// An IPv4 CIDR range used to allocate host addresses when booting compute into a VPC.
// This CIDR must be have a mask size of /18. If left unspecified, a Zone-specific default value will be applied by the server.
// This field is immutable once set.
//
// Deprecated: `hostPrefix` is deprecated. Use `hostPrefixes` instead. The field will be removed in a future version. The equivalent expression for a given resource may be found by refreshing state and running `terraform state show coreweave_networking_vpc.example`.
func (o NetworkingVpcOutput) HostPrefix() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkingVpc) pulumi.StringOutput { return v.HostPrefix }).(pulumi.StringOutput)
}

// The IPv4 or IPv6 CIDR ranges used to allocate host addresses when booting compute into a VPC.
func (o NetworkingVpcOutput) HostPrefixes() NetworkingVpcHostPrefixArrayOutput {
	return o.ApplyT(func(v *NetworkingVpc) NetworkingVpcHostPrefixArrayOutput { return v.HostPrefixes }).(NetworkingVpcHostPrefixArrayOutput)
}

// Settings affecting traffic entering the VPC.
func (o NetworkingVpcOutput) Ingress() NetworkingVpcIngressOutput {
	return o.ApplyT(func(v *NetworkingVpc) NetworkingVpcIngressOutput { return v.Ingress }).(NetworkingVpcIngressOutput)
}

// The name of the VPC. Must not be longer than 30 characters.
func (o NetworkingVpcOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkingVpc) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// A list of additional prefixes associated with the VPC. For example, CKS clusters use these prefixes for Pod and service CIDR ranges.
func (o NetworkingVpcOutput) VpcPrefixes() NetworkingVpcVpcPrefixArrayOutput {
	return o.ApplyT(func(v *NetworkingVpc) NetworkingVpcVpcPrefixArrayOutput { return v.VpcPrefixes }).(NetworkingVpcVpcPrefixArrayOutput)
}

// The Availability Zone in which the VPC is located.
func (o NetworkingVpcOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkingVpc) pulumi.StringOutput { return v.Zone }).(pulumi.StringOutput)
}

type NetworkingVpcArrayOutput struct{ *pulumi.OutputState }

func (NetworkingVpcArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NetworkingVpc)(nil)).Elem()
}

func (o NetworkingVpcArrayOutput) ToNetworkingVpcArrayOutput() NetworkingVpcArrayOutput {
	return o
}

func (o NetworkingVpcArrayOutput) ToNetworkingVpcArrayOutputWithContext(ctx context.Context) NetworkingVpcArrayOutput {
	return o
}

func (o NetworkingVpcArrayOutput) Index(i pulumi.IntInput) NetworkingVpcOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NetworkingVpc {
		return vs[0].([]*NetworkingVpc)[vs[1].(int)]
	}).(NetworkingVpcOutput)
}

type NetworkingVpcMapOutput struct{ *pulumi.OutputState }

func (NetworkingVpcMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NetworkingVpc)(nil)).Elem()
}

func (o NetworkingVpcMapOutput) ToNetworkingVpcMapOutput() NetworkingVpcMapOutput {
	return o
}

func (o NetworkingVpcMapOutput) ToNetworkingVpcMapOutputWithContext(ctx context.Context) NetworkingVpcMapOutput {
	return o
}

func (o NetworkingVpcMapOutput) MapIndex(k pulumi.StringInput) NetworkingVpcOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NetworkingVpc {
		return vs[0].(map[string]*NetworkingVpc)[vs[1].(string)]
	}).(NetworkingVpcOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkingVpcInput)(nil)).Elem(), &NetworkingVpc{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkingVpcArrayInput)(nil)).Elem(), NetworkingVpcArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkingVpcMapInput)(nil)).Elem(), NetworkingVpcMap{})
	pulumi.RegisterOutputType(NetworkingVpcOutput{})
	pulumi.RegisterOutputType(NetworkingVpcArrayOutput{})
	pulumi.RegisterOutputType(NetworkingVpcMapOutput{})
}
