// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package coreweave

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-coreweave/sdk/go/coreweave/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ObjectStorageOrganizationAccessPolicy struct {
	pulumi.CustomResourceState

	// The name of the organization access policy, must be unique.
	Name pulumi.StringOutput `pulumi:"name"`
	// The list of access policy statements associated with this policy. At least one statement is required.
	Statements ObjectStorageOrganizationAccessPolicyStatementArrayOutput `pulumi:"statements"`
}

// NewObjectStorageOrganizationAccessPolicy registers a new resource with the given unique name, arguments, and options.
func NewObjectStorageOrganizationAccessPolicy(ctx *pulumi.Context,
	name string, args *ObjectStorageOrganizationAccessPolicyArgs, opts ...pulumi.ResourceOption) (*ObjectStorageOrganizationAccessPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Statements == nil {
		return nil, errors.New("invalid value for required argument 'Statements'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ObjectStorageOrganizationAccessPolicy
	err := ctx.RegisterResource("coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetObjectStorageOrganizationAccessPolicy gets an existing ObjectStorageOrganizationAccessPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetObjectStorageOrganizationAccessPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ObjectStorageOrganizationAccessPolicyState, opts ...pulumi.ResourceOption) (*ObjectStorageOrganizationAccessPolicy, error) {
	var resource ObjectStorageOrganizationAccessPolicy
	err := ctx.ReadResource("coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ObjectStorageOrganizationAccessPolicy resources.
type objectStorageOrganizationAccessPolicyState struct {
	// The name of the organization access policy, must be unique.
	Name *string `pulumi:"name"`
	// The list of access policy statements associated with this policy. At least one statement is required.
	Statements []ObjectStorageOrganizationAccessPolicyStatement `pulumi:"statements"`
}

type ObjectStorageOrganizationAccessPolicyState struct {
	// The name of the organization access policy, must be unique.
	Name pulumi.StringPtrInput
	// The list of access policy statements associated with this policy. At least one statement is required.
	Statements ObjectStorageOrganizationAccessPolicyStatementArrayInput
}

func (ObjectStorageOrganizationAccessPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStorageOrganizationAccessPolicyState)(nil)).Elem()
}

type objectStorageOrganizationAccessPolicyArgs struct {
	// The name of the organization access policy, must be unique.
	Name *string `pulumi:"name"`
	// The list of access policy statements associated with this policy. At least one statement is required.
	Statements []ObjectStorageOrganizationAccessPolicyStatement `pulumi:"statements"`
}

// The set of arguments for constructing a ObjectStorageOrganizationAccessPolicy resource.
type ObjectStorageOrganizationAccessPolicyArgs struct {
	// The name of the organization access policy, must be unique.
	Name pulumi.StringPtrInput
	// The list of access policy statements associated with this policy. At least one statement is required.
	Statements ObjectStorageOrganizationAccessPolicyStatementArrayInput
}

func (ObjectStorageOrganizationAccessPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*objectStorageOrganizationAccessPolicyArgs)(nil)).Elem()
}

type ObjectStorageOrganizationAccessPolicyInput interface {
	pulumi.Input

	ToObjectStorageOrganizationAccessPolicyOutput() ObjectStorageOrganizationAccessPolicyOutput
	ToObjectStorageOrganizationAccessPolicyOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyOutput
}

func (*ObjectStorageOrganizationAccessPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (i *ObjectStorageOrganizationAccessPolicy) ToObjectStorageOrganizationAccessPolicyOutput() ObjectStorageOrganizationAccessPolicyOutput {
	return i.ToObjectStorageOrganizationAccessPolicyOutputWithContext(context.Background())
}

func (i *ObjectStorageOrganizationAccessPolicy) ToObjectStorageOrganizationAccessPolicyOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStorageOrganizationAccessPolicyOutput)
}

// ObjectStorageOrganizationAccessPolicyArrayInput is an input type that accepts ObjectStorageOrganizationAccessPolicyArray and ObjectStorageOrganizationAccessPolicyArrayOutput values.
// You can construct a concrete instance of `ObjectStorageOrganizationAccessPolicyArrayInput` via:
//
//	ObjectStorageOrganizationAccessPolicyArray{ ObjectStorageOrganizationAccessPolicyArgs{...} }
type ObjectStorageOrganizationAccessPolicyArrayInput interface {
	pulumi.Input

	ToObjectStorageOrganizationAccessPolicyArrayOutput() ObjectStorageOrganizationAccessPolicyArrayOutput
	ToObjectStorageOrganizationAccessPolicyArrayOutputWithContext(context.Context) ObjectStorageOrganizationAccessPolicyArrayOutput
}

type ObjectStorageOrganizationAccessPolicyArray []ObjectStorageOrganizationAccessPolicyInput

func (ObjectStorageOrganizationAccessPolicyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (i ObjectStorageOrganizationAccessPolicyArray) ToObjectStorageOrganizationAccessPolicyArrayOutput() ObjectStorageOrganizationAccessPolicyArrayOutput {
	return i.ToObjectStorageOrganizationAccessPolicyArrayOutputWithContext(context.Background())
}

func (i ObjectStorageOrganizationAccessPolicyArray) ToObjectStorageOrganizationAccessPolicyArrayOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStorageOrganizationAccessPolicyArrayOutput)
}

// ObjectStorageOrganizationAccessPolicyMapInput is an input type that accepts ObjectStorageOrganizationAccessPolicyMap and ObjectStorageOrganizationAccessPolicyMapOutput values.
// You can construct a concrete instance of `ObjectStorageOrganizationAccessPolicyMapInput` via:
//
//	ObjectStorageOrganizationAccessPolicyMap{ "key": ObjectStorageOrganizationAccessPolicyArgs{...} }
type ObjectStorageOrganizationAccessPolicyMapInput interface {
	pulumi.Input

	ToObjectStorageOrganizationAccessPolicyMapOutput() ObjectStorageOrganizationAccessPolicyMapOutput
	ToObjectStorageOrganizationAccessPolicyMapOutputWithContext(context.Context) ObjectStorageOrganizationAccessPolicyMapOutput
}

type ObjectStorageOrganizationAccessPolicyMap map[string]ObjectStorageOrganizationAccessPolicyInput

func (ObjectStorageOrganizationAccessPolicyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (i ObjectStorageOrganizationAccessPolicyMap) ToObjectStorageOrganizationAccessPolicyMapOutput() ObjectStorageOrganizationAccessPolicyMapOutput {
	return i.ToObjectStorageOrganizationAccessPolicyMapOutputWithContext(context.Background())
}

func (i ObjectStorageOrganizationAccessPolicyMap) ToObjectStorageOrganizationAccessPolicyMapOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ObjectStorageOrganizationAccessPolicyMapOutput)
}

type ObjectStorageOrganizationAccessPolicyOutput struct{ *pulumi.OutputState }

func (ObjectStorageOrganizationAccessPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (o ObjectStorageOrganizationAccessPolicyOutput) ToObjectStorageOrganizationAccessPolicyOutput() ObjectStorageOrganizationAccessPolicyOutput {
	return o
}

func (o ObjectStorageOrganizationAccessPolicyOutput) ToObjectStorageOrganizationAccessPolicyOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyOutput {
	return o
}

// The name of the organization access policy, must be unique.
func (o ObjectStorageOrganizationAccessPolicyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ObjectStorageOrganizationAccessPolicy) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The list of access policy statements associated with this policy. At least one statement is required.
func (o ObjectStorageOrganizationAccessPolicyOutput) Statements() ObjectStorageOrganizationAccessPolicyStatementArrayOutput {
	return o.ApplyT(func(v *ObjectStorageOrganizationAccessPolicy) ObjectStorageOrganizationAccessPolicyStatementArrayOutput {
		return v.Statements
	}).(ObjectStorageOrganizationAccessPolicyStatementArrayOutput)
}

type ObjectStorageOrganizationAccessPolicyArrayOutput struct{ *pulumi.OutputState }

func (ObjectStorageOrganizationAccessPolicyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (o ObjectStorageOrganizationAccessPolicyArrayOutput) ToObjectStorageOrganizationAccessPolicyArrayOutput() ObjectStorageOrganizationAccessPolicyArrayOutput {
	return o
}

func (o ObjectStorageOrganizationAccessPolicyArrayOutput) ToObjectStorageOrganizationAccessPolicyArrayOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyArrayOutput {
	return o
}

func (o ObjectStorageOrganizationAccessPolicyArrayOutput) Index(i pulumi.IntInput) ObjectStorageOrganizationAccessPolicyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ObjectStorageOrganizationAccessPolicy {
		return vs[0].([]*ObjectStorageOrganizationAccessPolicy)[vs[1].(int)]
	}).(ObjectStorageOrganizationAccessPolicyOutput)
}

type ObjectStorageOrganizationAccessPolicyMapOutput struct{ *pulumi.OutputState }

func (ObjectStorageOrganizationAccessPolicyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ObjectStorageOrganizationAccessPolicy)(nil)).Elem()
}

func (o ObjectStorageOrganizationAccessPolicyMapOutput) ToObjectStorageOrganizationAccessPolicyMapOutput() ObjectStorageOrganizationAccessPolicyMapOutput {
	return o
}

func (o ObjectStorageOrganizationAccessPolicyMapOutput) ToObjectStorageOrganizationAccessPolicyMapOutputWithContext(ctx context.Context) ObjectStorageOrganizationAccessPolicyMapOutput {
	return o
}

func (o ObjectStorageOrganizationAccessPolicyMapOutput) MapIndex(k pulumi.StringInput) ObjectStorageOrganizationAccessPolicyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ObjectStorageOrganizationAccessPolicy {
		return vs[0].(map[string]*ObjectStorageOrganizationAccessPolicy)[vs[1].(string)]
	}).(ObjectStorageOrganizationAccessPolicyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStorageOrganizationAccessPolicyInput)(nil)).Elem(), &ObjectStorageOrganizationAccessPolicy{})
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStorageOrganizationAccessPolicyArrayInput)(nil)).Elem(), ObjectStorageOrganizationAccessPolicyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ObjectStorageOrganizationAccessPolicyMapInput)(nil)).Elem(), ObjectStorageOrganizationAccessPolicyMap{})
	pulumi.RegisterOutputType(ObjectStorageOrganizationAccessPolicyOutput{})
	pulumi.RegisterOutputType(ObjectStorageOrganizationAccessPolicyArrayOutput{})
	pulumi.RegisterOutputType(ObjectStorageOrganizationAccessPolicyMapOutput{})
}
