// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface CksClusterAuthnWebhook {
    /**
     * The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
     */
    ca?: string;
    /**
     * The URL of the webhook server.
     */
    server: string;
}

export interface CksClusterAuthzWebhook {
    /**
     * The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
     */
    ca?: string;
    /**
     * The URL of the webhook server.
     */
    server: string;
}

export interface CksClusterNodePortRange {
    end: number;
    start: number;
}

export interface CksClusterOidc {
    /**
     * The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
     */
    adminGroupBinding?: string;
    /**
     * The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
     */
    ca?: string;
    /**
     * The client ID for the OIDC client.
     */
    clientId: string;
    /**
     * The claim to use as the groups.
     */
    groupsClaim?: string;
    /**
     * The prefix to use for the groups.
     */
    groupsPrefix?: string;
    /**
     * The URL of the OIDC issuer.
     */
    issuerUrl: string;
    /**
     * The claim to require for authentication.
     */
    requiredClaim?: string;
    /**
     * A list of signing algorithms that the OpenID Connect discovery endpoint uses.
     */
    signingAlgs?: string[];
    /**
     * The claim to use as the username.
     */
    usernameClaim?: string;
    /**
     * The prefix to use for the username.
     */
    usernamePrefix?: string;
}

export interface GetCksClusterAuthnWebhook {
    /**
     * The CA certificate of the authentication webhook.
     */
    ca: string;
    /**
     * The server URL of the authentication webhook.
     */
    server: string;
}

export interface GetCksClusterAuthzWebhook {
    /**
     * The CA certificate of the authorization webhook.
     */
    ca: string;
    /**
     * The server URL of the authorization webhook.
     */
    server: string;
}

export interface GetCksClusterNodePortRange {
    /**
     * End of the NodePort range.
     */
    end: number;
    /**
     * Start of the NodePort range.
     */
    start: number;
}

export interface GetCksClusterOidc {
    /**
     * The client ID of the OIDC configuration.
     */
    clientId: string;
    /**
     * The issuer URL of the OIDC configuration.
     */
    issuerUrl: string;
}

export interface GetNetworkingVpcDhcp {
    /**
     * Settings affecting DNS for DHCP within the VPC
     */
    dns: outputs.GetNetworkingVpcDhcpDns;
}

export interface GetNetworkingVpcDhcpDns {
    /**
     * The DNS servers advertised to DHCP clients within the VPC.
     */
    servers?: string[];
}

export interface GetNetworkingVpcEgress {
    /**
     * True if the VPC is blocked from consuming public Internet. False otherwise.
     */
    disablePublicAccess: boolean;
}

export interface GetNetworkingVpcHostPrefix {
    /**
     * The configuration for a secondary host prefix.
     */
    ipam: outputs.GetNetworkingVpcHostPrefixIpam;
    /**
     * The user-specified name of the host prefix.
     */
    name: string;
    /**
     * The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
     */
    prefixes: string[];
    /**
     * Controls network connectivity from the prefix to the host.
     */
    type: string;
}

export interface GetNetworkingVpcHostPrefixIpam {
    /**
     * Describes which IP address from the prefix is allocated to the network gateway.
     */
    gatewayAddressPolicy: string;
    /**
     * The desired length for each Node's allocation from the VPC-wide aggregate prefix.
     */
    prefixLength: number;
}

export interface GetNetworkingVpcIngress {
    /**
     * True if the VPC will prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet. False otherwise.
     */
    disablePublicServices: boolean;
}

export interface GetNetworkingVpcVpcPrefix {
    name: string;
    value: string;
}

export interface GetObjectStorageBucketPolicyDocumentStatement {
    /**
     * List of action strings, e.g. `["s3:PutObject"]`
     */
    actions?: string[];
    /**
     * Map of condition operators to JSON expressions
     */
    condition?: {[key: string]: {[key: string]: string}};
    /**
     * `Allow` or `Deny`
     */
    effect?: string;
    /**
     * Map of principal types to ARNs
     */
    principal?: {[key: string]: string[]};
    /**
     * List of resource ARNs, e.g. `["arn:aws:s3:::bucket/*"]`
     */
    resources?: string[];
    /**
     * An optional statement identifier
     */
    sid?: string;
}

export interface NetworkingVpcDhcp {
    /**
     * Settings affecting DNS for DHCP within the VPC
     */
    dns?: outputs.NetworkingVpcDhcpDns;
}

export interface NetworkingVpcDhcpDns {
    /**
     * The DNS servers to be used by DHCP clients within the VPC.
     */
    servers?: string[];
}

export interface NetworkingVpcEgress {
    /**
     * Specifies whether the VPC should be blocked from consuming public Internet.
     */
    disablePublicAccess?: boolean;
}

export interface NetworkingVpcHostPrefix {
    /**
     * The configuration for a secondary host prefix.
     */
    ipam?: outputs.NetworkingVpcHostPrefixIpam;
    /**
     * The user-specified name of the host prefix.
     */
    name: string;
    /**
     * The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
     */
    prefixes: string[];
    /**
     * Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
     */
    type: string;
}

export interface NetworkingVpcHostPrefixIpam {
    /**
     * Describes which IP address from the prefix is allocated to the network gateway. Must be one of: `UNSPECIFIED`, `EUI64`, `FIRST_IP`, `LAST_IP`.
     */
    gatewayAddressPolicy: string;
    /**
     * The desired length for each Node's allocation from the VPC-wide aggregate prefix.
     */
    prefixLength: number;
}

export interface NetworkingVpcIngress {
    /**
     * Specifies whether the VPC should prevent public prefixes advertised from Nodes from being imported into public-facing networks, making them inaccessible from the Internet.
     */
    disablePublicServices?: boolean;
}

export interface NetworkingVpcVpcPrefix {
    name: string;
    value: string;
}

export interface ObjectStorageBucketLifecycleConfigurationRule {
    abortIncompleteMultipartUpload?: outputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload;
    expiration?: outputs.ObjectStorageBucketLifecycleConfigurationRuleExpiration;
    filter?: outputs.ObjectStorageBucketLifecycleConfigurationRuleFilter;
    /**
     * Unique identifier for the rule
     */
    id?: string;
    noncurrentVersionExpiration?: outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration;
    noncurrentVersionTransitions?: outputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition[];
    /**
     * Object key prefix to which the rule applies
     */
    prefix?: string;
    /**
     * Rule status: Enabled or Disabled
     */
    status: string;
    transitions?: outputs.ObjectStorageBucketLifecycleConfigurationRuleTransition[];
}

export interface ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUpload {
    /**
     * Days after initiation to abort multipart uploads
     */
    daysAfterInitiation?: number;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleExpiration {
    /**
     * ISO8601 date when objects expire
     */
    date?: string;
    /**
     * Number of days after object creation for expiration
     */
    days?: number;
    /**
     * Whether to remove expired delete markers
     */
    expiredObjectDeleteMarker?: boolean;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleFilter {
    /**
     * Configuration block used to apply a logical AND to two or more predicates. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
     */
    and?: outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterAnd;
    /**
     * Minimum object size (in bytes) to which the rule applies.
     */
    objectSizeGreaterThan?: number;
    /**
     * Maximum object size (in bytes) to which the rule applies.
     */
    objectSizeLessThan?: number;
    /**
     * Prefix filter
     */
    prefix?: string;
    tag?: outputs.ObjectStorageBucketLifecycleConfigurationRuleFilterTag;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleFilterAnd {
    /**
     * Minimum object size (in bytes) to which the rule applies.
     */
    objectSizeGreaterThan?: number;
    /**
     * Maximum object size (in bytes) to which the rule applies.
     */
    objectSizeLessThan?: number;
    /**
     * Prefix identifying one or more objects to which the rule applies.
     */
    prefix?: string;
    /**
     * Map for specifying tag keys and values.
     */
    tags?: {[key: string]: string};
}

export interface ObjectStorageBucketLifecycleConfigurationRuleFilterTag {
    /**
     * Tag key filter
     */
    key?: string;
    /**
     * Tag value filter
     */
    value?: string;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpiration {
    /**
     * Number of noncurrent versions to retain
     */
    newerNoncurrentVersions?: number;
    /**
     * Days after becoming noncurrent before deletion
     */
    noncurrentDays?: number;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransition {
    /**
     * Number of noncurrent versions to retain
     */
    newerNoncurrentVersions?: number;
    /**
     * Number of days after object becomes noncurrent before the transition may occur
     */
    noncurrentDays: number;
    /**
     * Storage class to transition noncurrent objects to
     */
    storageClass: string;
}

export interface ObjectStorageBucketLifecycleConfigurationRuleTransition {
    /**
     * ISO8601 date when objects transition
     */
    date?: string;
    /**
     * Number of days after object creation for transition
     */
    days?: number;
    /**
     * Storage class to transition objects to
     */
    storageClass: string;
}

export interface ObjectStorageBucketVersioningVersioningConfiguration {
    /**
     * Versioning state of the bucket. Valid values: Enabled, Suspended, or Disabled. Disabled should only be used when creating or importing resources that correspond to unversioned S3 buckets since the S3 API does not allow setting an Enabled/Suspended bucket to Disabled.
     */
    status: string;
}

export interface ObjectStorageOrganizationAccessPolicyStatement {
    /**
     * Defines which operations the policy allows or denies. Organization access policies can include actions from two APIs - S3 (s3:*) and AI Object Storage API (cwobject:*). You can use wildcards (like s3:* or cwobject:*) to cover multiple actions at once.
     */
    actions: string[];
    /**
     * Must be either Allow or Deny (case-sensitive). Determines whether the statement grants or denies the specified actions on the listed resources for the designated principals. By default, all access is denied.
     */
    effect: string;
    /**
     * A short, human-readable identifier for this specific policy statement, similar to Sid in bucket access policies.
     */
    name: string;
    /**
     * Defines which users, roles, or groups the policy applies to. Only short-form identifiers are supported. If you use a full ARN, the policy will fail with an error. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining principals.
     */
    principals: string[];
    /**
     * Defines which resources the policy applies to. See the [AI Object Storage documentation](https://docs.coreweave.com/products/storage/object-storage/concepts/policies/organization-policies#resources) for guidelines on defining resources.
     */
    resources: string[];
}

