// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class CksClusterOidcArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The OIDC group that is bound to the cluster-admin role for bootstrap access to the cluster.
        /// </summary>
        [Input("adminGroupBinding")]
        public Input<string>? AdminGroupBinding { get; set; }

        /// <summary>
        /// The CA certificate for the OIDC issuer. Must be a base64-encoded PEM-encoded certificate.
        /// </summary>
        [Input("ca")]
        public Input<string>? Ca { get; set; }

        /// <summary>
        /// The client ID for the OIDC client.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The claim to use as the groups.
        /// </summary>
        [Input("groupsClaim")]
        public Input<string>? GroupsClaim { get; set; }

        /// <summary>
        /// The prefix to use for the groups.
        /// </summary>
        [Input("groupsPrefix")]
        public Input<string>? GroupsPrefix { get; set; }

        /// <summary>
        /// The URL of the OIDC issuer.
        /// </summary>
        [Input("issuerUrl", required: true)]
        public Input<string> IssuerUrl { get; set; } = null!;

        /// <summary>
        /// The claim to require for authentication.
        /// </summary>
        [Input("requiredClaim")]
        public Input<string>? RequiredClaim { get; set; }

        [Input("signingAlgs")]
        private InputList<string>? _signingAlgs;

        /// <summary>
        /// A list of signing algorithms that the OpenID Connect discovery endpoint uses.
        /// </summary>
        public InputList<string> SigningAlgs
        {
            get => _signingAlgs ?? (_signingAlgs = new InputList<string>());
            set => _signingAlgs = value;
        }

        /// <summary>
        /// The claim to use as the username.
        /// </summary>
        [Input("usernameClaim")]
        public Input<string>? UsernameClaim { get; set; }

        /// <summary>
        /// The prefix to use for the username.
        /// </summary>
        [Input("usernamePrefix")]
        public Input<string>? UsernamePrefix { get; set; }

        public CksClusterOidcArgs()
        {
        }
        public static new CksClusterOidcArgs Empty => new CksClusterOidcArgs();
    }
}
