// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class CksClusterNodePortRangeGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("end")]
        public Input<int>? End { get; set; }

        [Input("start")]
        public Input<int>? Start { get; set; }

        public CksClusterNodePortRangeGetArgs()
        {
        }
        public static new CksClusterNodePortRangeGetArgs Empty => new CksClusterNodePortRangeGetArgs();
    }
}
