// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class CksClusterAuthzWebhookGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The CA certificate for the webhook server. Must be a base64-encoded PEM-encoded certificate.
        /// </summary>
        [Input("ca")]
        public Input<string>? Ca { get; set; }

        /// <summary>
        /// The URL of the webhook server.
        /// </summary>
        [Input("server", required: true)]
        public Input<string> Server { get; set; } = null!;

        public CksClusterAuthzWebhookGetArgs()
        {
        }
        public static new CksClusterAuthzWebhookGetArgs Empty => new CksClusterAuthzWebhookGetArgs();
    }
}
