// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class GetObjectStorageBucketPolicyDocumentStatementInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("actions")]
        private InputList<string>? _actions;

        /// <summary>
        /// List of action strings, e.g. `["s3:PutObject"]`
        /// </summary>
        public InputList<string> Actions
        {
            get => _actions ?? (_actions = new InputList<string>());
            set => _actions = value;
        }

        [Input("condition")]
        private InputMap<ImmutableDictionary<string, string>>? _condition;

        /// <summary>
        /// Map of condition operators to JSON expressions
        /// </summary>
        public InputMap<ImmutableDictionary<string, string>> Condition
        {
            get => _condition ?? (_condition = new InputMap<ImmutableDictionary<string, string>>());
            set => _condition = value;
        }

        /// <summary>
        /// `Allow` or `Deny`
        /// </summary>
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        [Input("principal")]
        private InputMap<ImmutableArray<string>>? _principal;

        /// <summary>
        /// Map of principal types to ARNs
        /// </summary>
        public InputMap<ImmutableArray<string>> Principal
        {
            get => _principal ?? (_principal = new InputMap<ImmutableArray<string>>());
            set => _principal = value;
        }

        [Input("resources")]
        private InputList<string>? _resources;

        /// <summary>
        /// List of resource ARNs, e.g. `["arn:aws:s3:::bucket/*"]`
        /// </summary>
        public InputList<string> Resources
        {
            get => _resources ?? (_resources = new InputList<string>());
            set => _resources = value;
        }

        /// <summary>
        /// An optional statement identifier
        /// </summary>
        [Input("sid")]
        public Input<string>? Sid { get; set; }

        public GetObjectStorageBucketPolicyDocumentStatementInputArgs()
        {
        }
        public static new GetObjectStorageBucketPolicyDocumentStatementInputArgs Empty => new GetObjectStorageBucketPolicyDocumentStatementInputArgs();
    }
}
