// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class NetworkingVpcDhcpArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Settings affecting DNS for DHCP within the VPC
        /// </summary>
        [Input("dns")]
        public Input<Inputs.NetworkingVpcDhcpDnsArgs>? Dns { get; set; }

        public NetworkingVpcDhcpArgs()
        {
        }
        public static new NetworkingVpcDhcpArgs Empty => new NetworkingVpcDhcpArgs();
    }
}
