// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class NetworkingVpcHostPrefixArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The configuration for a secondary host prefix.
        /// </summary>
        [Input("ipam")]
        public Input<Inputs.NetworkingVpcHostPrefixIpamArgs>? Ipam { get; set; }

        /// <summary>
        /// The user-specified name of the host prefix.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("prefixes", required: true)]
        private InputList<string>? _prefixes;

        /// <summary>
        /// The VPC-wide aggregates from which host-specific prefixes are allocated. May be IPv4 or IPv6.
        /// </summary>
        public InputList<string> Prefixes
        {
            get => _prefixes ?? (_prefixes = new InputList<string>());
            set => _prefixes = value;
        }

        /// <summary>
        /// Controls network connectivity from the prefix to the host. Must be one of: `PRIMARY`, `ROUTED`, `ATTACHED`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public NetworkingVpcHostPrefixArgs()
        {
        }
        public static new NetworkingVpcHostPrefixArgs Empty => new NetworkingVpcHostPrefixArgs();
    }
}
