// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class NetworkingVpcEgressArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies whether the VPC should be blocked from consuming public Internet.
        /// </summary>
        [Input("disablePublicAccess")]
        public Input<bool>? DisablePublicAccess { get; set; }

        public NetworkingVpcEgressArgs()
        {
        }
        public static new NetworkingVpcEgressArgs Empty => new NetworkingVpcEgressArgs();
    }
}
