// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("abortIncompleteMultipartUpload")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadGetArgs>? AbortIncompleteMultipartUpload { get; set; }

        [Input("expiration")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleExpirationGetArgs>? Expiration { get; set; }

        [Input("filter")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterGetArgs>? Filter { get; set; }

        /// <summary>
        /// Unique identifier for the rule
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("noncurrentVersionExpiration")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationGetArgs>? NoncurrentVersionExpiration { get; set; }

        [Input("noncurrentVersionTransitions")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionGetArgs>? _noncurrentVersionTransitions;
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionGetArgs> NoncurrentVersionTransitions
        {
            get => _noncurrentVersionTransitions ?? (_noncurrentVersionTransitions = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionGetArgs>());
            set => _noncurrentVersionTransitions = value;
        }

        /// <summary>
        /// Object key prefix to which the rule applies
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// Rule status: Enabled or Disabled
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        [Input("transitions")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionGetArgs>? _transitions;
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionGetArgs> Transitions
        {
            get => _transitions ?? (_transitions = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionGetArgs>());
            set => _transitions = value;
        }

        public ObjectStorageBucketLifecycleConfigurationRuleGetArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleGetArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleGetArgs();
    }
}
