// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Days after initiation to abort multipart uploads
        /// </summary>
        [Input("daysAfterInitiation")]
        public Input<int>? DaysAfterInitiation { get; set; }

        public ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs();
    }
}
