// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleExpirationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ISO8601 date when objects expire
        /// </summary>
        [Input("date")]
        public Input<string>? Date { get; set; }

        /// <summary>
        /// Number of days after object creation for expiration
        /// </summary>
        [Input("days")]
        public Input<int>? Days { get; set; }

        /// <summary>
        /// Whether to remove expired delete markers
        /// </summary>
        [Input("expiredObjectDeleteMarker")]
        public Input<bool>? ExpiredObjectDeleteMarker { get; set; }

        public ObjectStorageBucketLifecycleConfigurationRuleExpirationGetArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleExpirationGetArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleExpirationGetArgs();
    }
}
