// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("abortIncompleteMultipartUpload")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs>? AbortIncompleteMultipartUpload { get; set; }

        [Input("expiration")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleExpirationArgs>? Expiration { get; set; }

        [Input("filter")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleFilterArgs>? Filter { get; set; }

        /// <summary>
        /// Unique identifier for the rule
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("noncurrentVersionExpiration")]
        public Input<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs>? NoncurrentVersionExpiration { get; set; }

        [Input("noncurrentVersionTransitions")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionArgs>? _noncurrentVersionTransitions;
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionArgs> NoncurrentVersionTransitions
        {
            get => _noncurrentVersionTransitions ?? (_noncurrentVersionTransitions = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionTransitionArgs>());
            set => _noncurrentVersionTransitions = value;
        }

        /// <summary>
        /// Object key prefix to which the rule applies
        /// </summary>
        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        /// <summary>
        /// Rule status: Enabled or Disabled
        /// </summary>
        [Input("status", required: true)]
        public Input<string> Status { get; set; } = null!;

        [Input("transitions")]
        private InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionArgs>? _transitions;
        public InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionArgs> Transitions
        {
            get => _transitions ?? (_transitions = new InputList<Inputs.ObjectStorageBucketLifecycleConfigurationRuleTransitionArgs>());
            set => _transitions = value;
        }

        public ObjectStorageBucketLifecycleConfigurationRuleArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleArgs();
    }
}
