// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of noncurrent versions to retain
        /// </summary>
        [Input("newerNoncurrentVersions")]
        public Input<int>? NewerNoncurrentVersions { get; set; }

        /// <summary>
        /// Days after becoming noncurrent before deletion
        /// </summary>
        [Input("noncurrentDays")]
        public Input<int>? NoncurrentDays { get; set; }

        public ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs();
    }
}
