// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Coreweave.Inputs
{

    public sealed class ObjectStorageBucketLifecycleConfigurationRuleFilterTagGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Tag key filter
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Tag value filter
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public ObjectStorageBucketLifecycleConfigurationRuleFilterTagGetArgs()
        {
        }
        public static new ObjectStorageBucketLifecycleConfigurationRuleFilterTagGetArgs Empty => new ObjectStorageBucketLifecycleConfigurationRuleFilterTagGetArgs();
    }
}
