// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export class CksCluster extends pulumi.CustomResource {
    /**
     * Get an existing CksCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CksClusterState, opts?: pulumi.CustomResourceOptions): CksCluster {
        return new CksCluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'coreweave:index/cksCluster:CksCluster';

    /**
     * Returns true if the given object is an instance of CksCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CksCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CksCluster.__pulumiType;
    }

    /**
     * Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
     */
    declare public readonly additionalServerSans: pulumi.Output<string[] | undefined>;
    /**
     * The endpoint for the cluster's api-server.
     */
    declare public /*out*/ readonly apiServerEndpoint: pulumi.Output<string>;
    /**
     * Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
     */
    declare public readonly auditPolicy: pulumi.Output<string | undefined>;
    /**
     * Authentication webhook configuration for the cluster.
     */
    declare public readonly authnWebhook: pulumi.Output<outputs.CksClusterAuthnWebhook | undefined>;
    /**
     * Authorization webhook configuration for the cluster.
     */
    declare public readonly authzWebhook: pulumi.Output<outputs.CksClusterAuthzWebhook | undefined>;
    /**
     * The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
     * The prefixes must exist in the cluster's VPC. This field is append-only.
     */
    declare public readonly internalLbCidrNames: pulumi.Output<string[]>;
    /**
     * IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    declare public readonly internalLbCidrNamesV6s: pulumi.Output<string[] | undefined>;
    /**
     * The name of the cluster. Must not be longer than 30 characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster.
     */
    declare public readonly nodePortRange: pulumi.Output<outputs.CksClusterNodePortRange>;
    /**
     * OpenID Connect (OIDC) configuration for authentication to the api-server.
     */
    declare public readonly oidc: pulumi.Output<outputs.CksClusterOidc | undefined>;
    /**
     * The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
     */
    declare public readonly podCidrName: pulumi.Output<string>;
    /**
     * IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    declare public readonly podCidrNameV6: pulumi.Output<string | undefined>;
    /**
     * Whether the cluster's api-server is publicly accessible from the internet.
     */
    declare public readonly public: pulumi.Output<boolean>;
    /**
     * The URL of the OIDC issuer for the cluster's service account tokens. This value corresponds to the `--service-account-issuer` flag on the kube-apiserver.
     */
    declare public /*out*/ readonly serviceAccountOidcIssuerUrl: pulumi.Output<string>;
    /**
     * The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
     */
    declare public readonly serviceCidrName: pulumi.Output<string>;
    /**
     * IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    declare public readonly serviceCidrNameV6: pulumi.Output<string | undefined>;
    /**
     * The `clusterId` of the cluster to share storage with. Must be enabled by CoreWeave suppport. Contact CoreWeave support if you are interested in this feature.
     */
    declare public readonly sharedStorageClusterId: pulumi.Output<string | undefined>;
    /**
     * The current status of the cluster.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
     */
    declare public readonly version: pulumi.Output<string>;
    /**
     * The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
     */
    declare public readonly vpcId: pulumi.Output<string>;
    /**
     * The Availability Zone in which the cluster is located.
     */
    declare public readonly zone: pulumi.Output<string>;

    /**
     * Create a CksCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CksClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CksClusterArgs | CksClusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CksClusterState | undefined;
            resourceInputs["additionalServerSans"] = state?.additionalServerSans;
            resourceInputs["apiServerEndpoint"] = state?.apiServerEndpoint;
            resourceInputs["auditPolicy"] = state?.auditPolicy;
            resourceInputs["authnWebhook"] = state?.authnWebhook;
            resourceInputs["authzWebhook"] = state?.authzWebhook;
            resourceInputs["internalLbCidrNames"] = state?.internalLbCidrNames;
            resourceInputs["internalLbCidrNamesV6s"] = state?.internalLbCidrNamesV6s;
            resourceInputs["name"] = state?.name;
            resourceInputs["nodePortRange"] = state?.nodePortRange;
            resourceInputs["oidc"] = state?.oidc;
            resourceInputs["podCidrName"] = state?.podCidrName;
            resourceInputs["podCidrNameV6"] = state?.podCidrNameV6;
            resourceInputs["public"] = state?.public;
            resourceInputs["serviceAccountOidcIssuerUrl"] = state?.serviceAccountOidcIssuerUrl;
            resourceInputs["serviceCidrName"] = state?.serviceCidrName;
            resourceInputs["serviceCidrNameV6"] = state?.serviceCidrNameV6;
            resourceInputs["sharedStorageClusterId"] = state?.sharedStorageClusterId;
            resourceInputs["status"] = state?.status;
            resourceInputs["version"] = state?.version;
            resourceInputs["vpcId"] = state?.vpcId;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as CksClusterArgs | undefined;
            if (args?.internalLbCidrNames === undefined && !opts.urn) {
                throw new Error("Missing required property 'internalLbCidrNames'");
            }
            if (args?.podCidrName === undefined && !opts.urn) {
                throw new Error("Missing required property 'podCidrName'");
            }
            if (args?.serviceCidrName === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceCidrName'");
            }
            if (args?.version === undefined && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            if (args?.vpcId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            if (args?.zone === undefined && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["additionalServerSans"] = args?.additionalServerSans;
            resourceInputs["auditPolicy"] = args?.auditPolicy;
            resourceInputs["authnWebhook"] = args?.authnWebhook;
            resourceInputs["authzWebhook"] = args?.authzWebhook;
            resourceInputs["internalLbCidrNames"] = args?.internalLbCidrNames;
            resourceInputs["internalLbCidrNamesV6s"] = args?.internalLbCidrNamesV6s;
            resourceInputs["name"] = args?.name;
            resourceInputs["nodePortRange"] = args?.nodePortRange;
            resourceInputs["oidc"] = args?.oidc;
            resourceInputs["podCidrName"] = args?.podCidrName;
            resourceInputs["podCidrNameV6"] = args?.podCidrNameV6;
            resourceInputs["public"] = args?.public;
            resourceInputs["serviceCidrName"] = args?.serviceCidrName;
            resourceInputs["serviceCidrNameV6"] = args?.serviceCidrNameV6;
            resourceInputs["sharedStorageClusterId"] = args?.sharedStorageClusterId;
            resourceInputs["version"] = args?.version;
            resourceInputs["vpcId"] = args?.vpcId;
            resourceInputs["zone"] = args?.zone;
            resourceInputs["apiServerEndpoint"] = undefined /*out*/;
            resourceInputs["serviceAccountOidcIssuerUrl"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CksCluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CksCluster resources.
 */
export interface CksClusterState {
    /**
     * Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
     */
    additionalServerSans?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The endpoint for the cluster's api-server.
     */
    apiServerEndpoint?: pulumi.Input<string>;
    /**
     * Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
     */
    auditPolicy?: pulumi.Input<string>;
    /**
     * Authentication webhook configuration for the cluster.
     */
    authnWebhook?: pulumi.Input<inputs.CksClusterAuthnWebhook>;
    /**
     * Authorization webhook configuration for the cluster.
     */
    authzWebhook?: pulumi.Input<inputs.CksClusterAuthzWebhook>;
    /**
     * The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
     * The prefixes must exist in the cluster's VPC. This field is append-only.
     */
    internalLbCidrNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    internalLbCidrNamesV6s?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the cluster. Must not be longer than 30 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster.
     */
    nodePortRange?: pulumi.Input<inputs.CksClusterNodePortRange>;
    /**
     * OpenID Connect (OIDC) configuration for authentication to the api-server.
     */
    oidc?: pulumi.Input<inputs.CksClusterOidc>;
    /**
     * The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
     */
    podCidrName?: pulumi.Input<string>;
    /**
     * IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    podCidrNameV6?: pulumi.Input<string>;
    /**
     * Whether the cluster's api-server is publicly accessible from the internet.
     */
    public?: pulumi.Input<boolean>;
    /**
     * The URL of the OIDC issuer for the cluster's service account tokens. This value corresponds to the `--service-account-issuer` flag on the kube-apiserver.
     */
    serviceAccountOidcIssuerUrl?: pulumi.Input<string>;
    /**
     * The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
     */
    serviceCidrName?: pulumi.Input<string>;
    /**
     * IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    serviceCidrNameV6?: pulumi.Input<string>;
    /**
     * The `clusterId` of the cluster to share storage with. Must be enabled by CoreWeave suppport. Contact CoreWeave support if you are interested in this feature.
     */
    sharedStorageClusterId?: pulumi.Input<string>;
    /**
     * The current status of the cluster.
     */
    status?: pulumi.Input<string>;
    /**
     * The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
     */
    version?: pulumi.Input<string>;
    /**
     * The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
     */
    vpcId?: pulumi.Input<string>;
    /**
     * The Availability Zone in which the cluster is located.
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CksCluster resource.
 */
export interface CksClusterArgs {
    /**
     * Additional Subject Alternative Names (SANs) to include in the Kubernetes API server TLS certificate. Maximum 10 entries.
     */
    additionalServerSans?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Audit policy for the cluster. Must be provided as a base64-encoded JSON/YAML string.
     */
    auditPolicy?: pulumi.Input<string>;
    /**
     * Authentication webhook configuration for the cluster.
     */
    authnWebhook?: pulumi.Input<inputs.CksClusterAuthnWebhook>;
    /**
     * Authorization webhook configuration for the cluster.
     */
    authzWebhook?: pulumi.Input<inputs.CksClusterAuthzWebhook>;
    /**
     * The names of the vpc prefixes to use as internal load balancer CIDR ranges. Internal load balancers are reachable within the VPC but not accessible from the internet.
     * The prefixes must exist in the cluster's VPC. This field is append-only.
     */
    internalLbCidrNames: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * IPv6 Internal Load Balancer CIDR names. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    internalLbCidrNamesV6s?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the cluster. Must not be longer than 30 characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Kubernetes Service NodePort range. NodePort range can be expanded in existing clusters but not shrunk. Updating the NodePort range to a smaller range will require a replacement of the cluster.
     */
    nodePortRange?: pulumi.Input<inputs.CksClusterNodePortRange>;
    /**
     * OpenID Connect (OIDC) configuration for authentication to the api-server.
     */
    oidc?: pulumi.Input<inputs.CksClusterOidc>;
    /**
     * The name of the vpc prefix to use as the pod CIDR range. The prefix must exist in the cluster's VPC.
     */
    podCidrName: pulumi.Input<string>;
    /**
     * IPv6 Pod CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    podCidrNameV6?: pulumi.Input<string>;
    /**
     * Whether the cluster's api-server is publicly accessible from the internet.
     */
    public?: pulumi.Input<boolean>;
    /**
     * The name of the vpc prefix to use as the service CIDR range. The prefix must exist in the cluster's VPC.
     */
    serviceCidrName: pulumi.Input<string>;
    /**
     * IPv6 Service CIDR name. If any IPv6 field is set, then ALL IPv6 fields must be set.
     */
    serviceCidrNameV6?: pulumi.Input<string>;
    /**
     * The `clusterId` of the cluster to share storage with. Must be enabled by CoreWeave suppport. Contact CoreWeave support if you are interested in this feature.
     */
    sharedStorageClusterId?: pulumi.Input<string>;
    /**
     * The version of Kubernetes to run on the cluster, in minor version format (e.g. 'v1.35'). Patch versions are automatically applied by CKS as they are released.
     */
    version: pulumi.Input<string>;
    /**
     * The ID of the VPC in which the cluster is located. Must be a VPC in the same Availability Zone as the cluster.
     */
    vpcId: pulumi.Input<string>;
    /**
     * The Availability Zone in which the cluster is located.
     */
    zone: pulumi.Input<string>;
}
