// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCksCluster(args: GetCksClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetCksClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coreweave:index/getCksCluster:getCksCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCksCluster.
 */
export interface GetCksClusterArgs {
    id: string;
}

/**
 * A collection of values returned by getCksCluster.
 */
export interface GetCksClusterResult {
    readonly additionalServerSans: string[];
    readonly apiServerEndpoint: string;
    readonly auditPolicy: string;
    readonly authnWebhook: outputs.GetCksClusterAuthnWebhook;
    readonly authzWebhook: outputs.GetCksClusterAuthzWebhook;
    readonly id: string;
    readonly internalLbCidrNames: string[];
    readonly internalLbCidrNamesV6s: string[];
    readonly name: string;
    readonly nodePortRange: outputs.GetCksClusterNodePortRange;
    readonly oidc: outputs.GetCksClusterOidc;
    readonly podCidrName: string;
    readonly podCidrNameV6: string;
    readonly public: boolean;
    readonly serviceAccountOidcIssuerUrl: string;
    readonly serviceCidrName: string;
    readonly serviceCidrNameV6: string;
    readonly sharedStorageClusterId: string;
    readonly status: string;
    readonly version: string;
    readonly vpcId: string;
    readonly zone: string;
}
export function getCksClusterOutput(args: GetCksClusterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCksClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coreweave:index/getCksCluster:getCksCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCksCluster.
 */
export interface GetCksClusterOutputArgs {
    id: pulumi.Input<string>;
}
