// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Query information about an existing CoreWeave Kubernetes Service (CKS) cluster by ID. See the [CKS API reference](https://docs.coreweave.com/products/cks/reference/cks-api).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as coreweave from "@pulumi/coreweave";
 *
 * const _default = coreweave.getCksCluster({
 *     id: "1063bce6-6e5b-4b0a-b73a-7e6106b2a77c",
 * });
 * ```
 */
export function getCksCluster(args: GetCksClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetCksClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coreweave:index/getCksCluster:getCksCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCksCluster.
 */
export interface GetCksClusterArgs {
    /**
     * The ID of the cluster.
     */
    id: string;
}

/**
 * A collection of values returned by getCksCluster.
 */
export interface GetCksClusterResult {
    /**
     * Additional Subject Alternative Names (SANs) included in the Kubernetes API server TLS certificate.
     */
    readonly additionalServerSans: string[];
    /**
     * The API server endpoint of the cluster.
     */
    readonly apiServerEndpoint: string;
    /**
     * The audit policy of the cluster.
     */
    readonly auditPolicy: string;
    /**
     * The authentication webhook configuration of the cluster.
     */
    readonly authnWebhook: outputs.GetCksClusterAuthnWebhook;
    /**
     * The authorization webhook configuration of the cluster.
     */
    readonly authzWebhook: outputs.GetCksClusterAuthzWebhook;
    /**
     * The ID of the cluster.
     */
    readonly id: string;
    /**
     * The internal load balancer CIDR names of the cluster.
     */
    readonly internalLbCidrNames: string[];
    /**
     * The IPv6 internal load balancer CIDR names of the cluster.
     */
    readonly internalLbCidrNamesV6s: string[];
    /**
     * The name of the cluster.
     */
    readonly name: string;
    /**
     * The Kubernetes Service NodePort range.
     */
    readonly nodePortRange: outputs.GetCksClusterNodePortRange;
    /**
     * The OIDC configuration of the cluster.
     */
    readonly oidc: outputs.GetCksClusterOidc;
    /**
     * The pod CIDR name of the cluster.
     */
    readonly podCidrName: string;
    /**
     * The IPv6 pod CIDR name of the cluster.
     */
    readonly podCidrNameV6: string;
    /**
     * Whether the cluster is public.
     */
    readonly public: boolean;
    /**
     * The URL of the OIDC issuer for the cluster's service account tokens. This value corresponds to the `--service-account-issuer` flag on the kube-apiserver.
     */
    readonly serviceAccountOidcIssuerUrl: string;
    /**
     * The service CIDR name of the cluster.
     */
    readonly serviceCidrName: string;
    /**
     * The IPv6 service CIDR name of the cluster.
     */
    readonly serviceCidrNameV6: string;
    /**
     * The `clusterId` of the cluster to share storage with. Must be enabled by CoreWeave suppport. Contact CoreWeave support if you are interested in this feature.
     */
    readonly sharedStorageClusterId: string;
    /**
     * The status of the cluster.
     */
    readonly status: string;
    /**
     * The version of the cluster.
     */
    readonly version: string;
    /**
     * The VPC ID of the cluster.
     */
    readonly vpcId: string;
    /**
     * The zone of the cluster.
     */
    readonly zone: string;
}
/**
 * Query information about an existing CoreWeave Kubernetes Service (CKS) cluster by ID. See the [CKS API reference](https://docs.coreweave.com/products/cks/reference/cks-api).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as coreweave from "@pulumi/coreweave";
 *
 * const _default = coreweave.getCksCluster({
 *     id: "1063bce6-6e5b-4b0a-b73a-7e6106b2a77c",
 * });
 * ```
 */
export function getCksClusterOutput(args: GetCksClusterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCksClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coreweave:index/getCksCluster:getCksCluster", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getCksCluster.
 */
export interface GetCksClusterOutputArgs {
    /**
     * The ID of the cluster.
     */
    id: pulumi.Input<string>;
}
