// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getNetworkingVpc(args: GetNetworkingVpcArgs, opts?: pulumi.InvokeOptions): Promise<GetNetworkingVpcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coreweave:index/getNetworkingVpc:getNetworkingVpc", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getNetworkingVpc.
 */
export interface GetNetworkingVpcArgs {
    id: string;
}

/**
 * A collection of values returned by getNetworkingVpc.
 */
export interface GetNetworkingVpcResult {
    readonly dhcp: outputs.GetNetworkingVpcDhcp;
    readonly egress: outputs.GetNetworkingVpcEgress;
    /**
     * @deprecated Configure hostPrefixes instead.
     */
    readonly hostPrefix: string;
    readonly hostPrefixes: outputs.GetNetworkingVpcHostPrefix[];
    readonly id: string;
    readonly ingress: outputs.GetNetworkingVpcIngress;
    readonly name: string;
    readonly vpcPrefixes: outputs.GetNetworkingVpcVpcPrefix[];
    readonly zone: string;
}
export function getNetworkingVpcOutput(args: GetNetworkingVpcOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNetworkingVpcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coreweave:index/getNetworkingVpc:getNetworkingVpc", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getNetworkingVpc.
 */
export interface GetNetworkingVpcOutputArgs {
    id: pulumi.Input<string>;
}
