// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * [Bucket access policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/bucket-policies) allow you to define precise, S3-compatible access control for one bucket. They are evaluated after organization access policies. See [Manage Bucket Policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/manage-bucket-policies#example-policies) for examples and further information. This data source provides a type-safe data structure for creating an S3-compatible JSON bucket policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as coreweave from "@pulumi/coreweave";
 *
 * const _default = coreweave.getObjectStorageBucketPolicyDocument({
 *     version: "2012-10-17",
 *     statements: [{
 *         sid: "allow-all",
 *         effect: "Allow",
 *         actions: ["s3:*"],
 *         resources: ["arn:aws:s3:::*"],
 *         principal: {
 *             CW: ["*"],
 *         },
 *     }],
 * });
 * ```
 */
export function getObjectStorageBucketPolicyDocument(args?: GetObjectStorageBucketPolicyDocumentArgs, opts?: pulumi.InvokeOptions): Promise<GetObjectStorageBucketPolicyDocumentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("coreweave:index/getObjectStorageBucketPolicyDocument:getObjectStorageBucketPolicyDocument", {
        "id": args.id,
        "statements": args.statements,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getObjectStorageBucketPolicyDocument.
 */
export interface GetObjectStorageBucketPolicyDocumentArgs {
    /**
     * An optional policy identifier
     */
    id?: string;
    /**
     * The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
     */
    statements?: inputs.GetObjectStorageBucketPolicyDocumentStatement[];
    /**
     * The policy version, e.g. `"2012-10-17"`
     */
    version?: string;
}

/**
 * A collection of values returned by getObjectStorageBucketPolicyDocument.
 */
export interface GetObjectStorageBucketPolicyDocumentResult {
    /**
     * An optional policy identifier
     */
    readonly id?: string;
    /**
     * The rendered policy document as JSON
     */
    readonly json: string;
    /**
     * The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
     */
    readonly statements?: outputs.GetObjectStorageBucketPolicyDocumentStatement[];
    /**
     * The policy version, e.g. `"2012-10-17"`
     */
    readonly version?: string;
}
/**
 * [Bucket access policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/bucket-policies) allow you to define precise, S3-compatible access control for one bucket. They are evaluated after organization access policies. See [Manage Bucket Policies](https://docs.coreweave.com/products/storage/object-storage/auth-access/bucket-access/manage-bucket-policies#example-policies) for examples and further information. This data source provides a type-safe data structure for creating an S3-compatible JSON bucket policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as coreweave from "@pulumi/coreweave";
 *
 * const _default = coreweave.getObjectStorageBucketPolicyDocument({
 *     version: "2012-10-17",
 *     statements: [{
 *         sid: "allow-all",
 *         effect: "Allow",
 *         actions: ["s3:*"],
 *         resources: ["arn:aws:s3:::*"],
 *         principal: {
 *             CW: ["*"],
 *         },
 *     }],
 * });
 * ```
 */
export function getObjectStorageBucketPolicyDocumentOutput(args?: GetObjectStorageBucketPolicyDocumentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetObjectStorageBucketPolicyDocumentResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("coreweave:index/getObjectStorageBucketPolicyDocument:getObjectStorageBucketPolicyDocument", {
        "id": args.id,
        "statements": args.statements,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getObjectStorageBucketPolicyDocument.
 */
export interface GetObjectStorageBucketPolicyDocumentOutputArgs {
    /**
     * An optional policy identifier
     */
    id?: pulumi.Input<string>;
    /**
     * The main policy element that defines the access rules for buckets and objects. Multiple statement blocks can be specified.
     */
    statements?: pulumi.Input<pulumi.Input<inputs.GetObjectStorageBucketPolicyDocumentStatementArgs>[]>;
    /**
     * The policy version, e.g. `"2012-10-17"`
     */
    version?: pulumi.Input<string>;
}
