// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CksClusterArgs, CksClusterState } from "./cksCluster";
export type CksCluster = import("./cksCluster").CksCluster;
export const CksCluster: typeof import("./cksCluster").CksCluster = null as any;
utilities.lazyLoad(exports, ["CksCluster"], () => require("./cksCluster"));

export { GetCksClusterArgs, GetCksClusterResult, GetCksClusterOutputArgs } from "./getCksCluster";
export const getCksCluster: typeof import("./getCksCluster").getCksCluster = null as any;
export const getCksClusterOutput: typeof import("./getCksCluster").getCksClusterOutput = null as any;
utilities.lazyLoad(exports, ["getCksCluster","getCksClusterOutput"], () => require("./getCksCluster"));

export { GetNetworkingVpcArgs, GetNetworkingVpcResult, GetNetworkingVpcOutputArgs } from "./getNetworkingVpc";
export const getNetworkingVpc: typeof import("./getNetworkingVpc").getNetworkingVpc = null as any;
export const getNetworkingVpcOutput: typeof import("./getNetworkingVpc").getNetworkingVpcOutput = null as any;
utilities.lazyLoad(exports, ["getNetworkingVpc","getNetworkingVpcOutput"], () => require("./getNetworkingVpc"));

export { GetObjectStorageBucketPolicyDocumentArgs, GetObjectStorageBucketPolicyDocumentResult, GetObjectStorageBucketPolicyDocumentOutputArgs } from "./getObjectStorageBucketPolicyDocument";
export const getObjectStorageBucketPolicyDocument: typeof import("./getObjectStorageBucketPolicyDocument").getObjectStorageBucketPolicyDocument = null as any;
export const getObjectStorageBucketPolicyDocumentOutput: typeof import("./getObjectStorageBucketPolicyDocument").getObjectStorageBucketPolicyDocumentOutput = null as any;
utilities.lazyLoad(exports, ["getObjectStorageBucketPolicyDocument","getObjectStorageBucketPolicyDocumentOutput"], () => require("./getObjectStorageBucketPolicyDocument"));

export { NetworkingVpcArgs, NetworkingVpcState } from "./networkingVpc";
export type NetworkingVpc = import("./networkingVpc").NetworkingVpc;
export const NetworkingVpc: typeof import("./networkingVpc").NetworkingVpc = null as any;
utilities.lazyLoad(exports, ["NetworkingVpc"], () => require("./networkingVpc"));

export { ObjectStorageBucketArgs, ObjectStorageBucketState } from "./objectStorageBucket";
export type ObjectStorageBucket = import("./objectStorageBucket").ObjectStorageBucket;
export const ObjectStorageBucket: typeof import("./objectStorageBucket").ObjectStorageBucket = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucket"], () => require("./objectStorageBucket"));

export { ObjectStorageBucketLifecycleConfigurationArgs, ObjectStorageBucketLifecycleConfigurationState } from "./objectStorageBucketLifecycleConfiguration";
export type ObjectStorageBucketLifecycleConfiguration = import("./objectStorageBucketLifecycleConfiguration").ObjectStorageBucketLifecycleConfiguration;
export const ObjectStorageBucketLifecycleConfiguration: typeof import("./objectStorageBucketLifecycleConfiguration").ObjectStorageBucketLifecycleConfiguration = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucketLifecycleConfiguration"], () => require("./objectStorageBucketLifecycleConfiguration"));

export { ObjectStorageBucketPolicyArgs, ObjectStorageBucketPolicyState } from "./objectStorageBucketPolicy";
export type ObjectStorageBucketPolicy = import("./objectStorageBucketPolicy").ObjectStorageBucketPolicy;
export const ObjectStorageBucketPolicy: typeof import("./objectStorageBucketPolicy").ObjectStorageBucketPolicy = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucketPolicy"], () => require("./objectStorageBucketPolicy"));

export { ObjectStorageBucketSettingsArgs, ObjectStorageBucketSettingsState } from "./objectStorageBucketSettings";
export type ObjectStorageBucketSettings = import("./objectStorageBucketSettings").ObjectStorageBucketSettings;
export const ObjectStorageBucketSettings: typeof import("./objectStorageBucketSettings").ObjectStorageBucketSettings = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucketSettings"], () => require("./objectStorageBucketSettings"));

export { ObjectStorageBucketVersioningArgs, ObjectStorageBucketVersioningState } from "./objectStorageBucketVersioning";
export type ObjectStorageBucketVersioning = import("./objectStorageBucketVersioning").ObjectStorageBucketVersioning;
export const ObjectStorageBucketVersioning: typeof import("./objectStorageBucketVersioning").ObjectStorageBucketVersioning = null as any;
utilities.lazyLoad(exports, ["ObjectStorageBucketVersioning"], () => require("./objectStorageBucketVersioning"));

export { ObjectStorageOrganizationAccessPolicyArgs, ObjectStorageOrganizationAccessPolicyState } from "./objectStorageOrganizationAccessPolicy";
export type ObjectStorageOrganizationAccessPolicy = import("./objectStorageOrganizationAccessPolicy").ObjectStorageOrganizationAccessPolicy;
export const ObjectStorageOrganizationAccessPolicy: typeof import("./objectStorageOrganizationAccessPolicy").ObjectStorageOrganizationAccessPolicy = null as any;
utilities.lazyLoad(exports, ["ObjectStorageOrganizationAccessPolicy"], () => require("./objectStorageOrganizationAccessPolicy"));

export * from "./provider";
import { Provider } from "./provider";


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "coreweave:index/cksCluster:CksCluster":
                return new CksCluster(name, <any>undefined, { urn })
            case "coreweave:index/networkingVpc:NetworkingVpc":
                return new NetworkingVpc(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageBucket:ObjectStorageBucket":
                return new ObjectStorageBucket(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageBucketLifecycleConfiguration:ObjectStorageBucketLifecycleConfiguration":
                return new ObjectStorageBucketLifecycleConfiguration(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageBucketPolicy:ObjectStorageBucketPolicy":
                return new ObjectStorageBucketPolicy(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageBucketSettings:ObjectStorageBucketSettings":
                return new ObjectStorageBucketSettings(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageBucketVersioning:ObjectStorageBucketVersioning":
                return new ObjectStorageBucketVersioning(name, <any>undefined, { urn })
            case "coreweave:index/objectStorageOrganizationAccessPolicy:ObjectStorageOrganizationAccessPolicy":
                return new ObjectStorageOrganizationAccessPolicy(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("coreweave", "index/cksCluster", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/networkingVpc", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageBucket", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageBucketLifecycleConfiguration", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageBucketPolicy", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageBucketSettings", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageBucketVersioning", _module)
pulumi.runtime.registerResourceModule("coreweave", "index/objectStorageOrganizationAccessPolicy", _module)
pulumi.runtime.registerResourcePackage("coreweave", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:coreweave") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
